### PR TITLE
[unicree/cross] Increase retry number of vcs import

### PR DESCRIPTION
**Pull request by tkmtnt7000**
This is the one solution of https://github.com/jsk-ros-pkg/jsk_robot/issues/1857 with reflecting the comment https://github.com/jsk-ros-pkg/jsk_robot/issues/1857#issuecomment-1749862073.

I increased vcs import retry number from 3 to 10 (Is it too many?).

### CODE REVIEW

**Review by sktometometo — APPROVED** [review]

**Comment by k-okada** [comment]
@sktometometo Has this solved your problem?

**Comment by sktometometo** [comment]
Not yet, still trying.

**Comment by sktometometo** [comment]
`make user` has succeeded.

**Comment by k-okada** [comment]
image

they are called with `make system`, not `make user`
https://github.com/jsk-ros-pkg/jsk_robot/blob/9a1da3dccba70a646dc42c81f911ef2dd2a5475c/jsk_unitree_robot/cross/Makefile#L12-L15

**Pull request merged**
