### PR TITLE
[jsk_pr2_startup] use new battery warning

### PR DESCRIPTION
**Pull request by knorth55**
split from #1081 
this battery warning is written by @furushchev and used in PR1040.
cc. @YutoUchimi

### CODE REVIEW

**Comment by knorth55** [comment]
@YutoUchimi 
in this document, we need at least 56V.
so it is better to output error when voltage is lower than 14V ( 56 / 4).
http://www.clearpathrobotics.com/wp-content/downloads/pr2//pr2_power_board_rr.pdf

**Comment by knorth55** [comment]
@YutoUchimi 
also, you can get voltage info from `pr2_power_board`.
when PR2 is down because of power shortage, voltage of CPU, arms and base is around 59-60V.
http://wiki.ros.org/pr2_power_board

**Comment by YutoUchimi** [comment]
Note: battery log (2019.5.23) is here.
https://drive.google.com/drive/u/1/folders/14QrFi53zJJgZTEjqmford_730Xaii3Ra

**Comment by k-okada** [comment]
@YutoUchimi Is this depends on (or related to) https://github.com/jsk-ros-pkg/jsk_common/pull/1628 ? Or these two tools are completely different system?

**Comment by YutoUchimi** [comment]
@k-okada They are completely different.

**Pull request merged**
