### PR TITLE
[jsk_fetch_startup] Publish diagnostics for important topics and nodes

### PR DESCRIPTION
**Pull request by 708yamaguchi**
This is refined version of https://github.com/jsk-ros-pkg/jsk_robot/pull/1460
Copied from https://github.com/knorth55/jsk_robot/pull/222
This depends on https://github.com/jsk-ros-pkg/jsk_common/pull/1727

I want fetch to indicate that topic has not come or node does not exist.
For example, I want to check existence of `/audio` or `/insta360`, whose publisher does not publish `/diagnostics`.

What I did in this PR is as follows:
- Change diagnostics aggregator prefix according to node name change.
- Add node to publish /diagnostics

### CODE REVIEW

**Comment by k-okada** [comment]
wait for upstream release ??

**Comment by 708yamaguchi** [comment]
Sorry, I force-pushed commits because https://github.com/knorth55/jsk_robot/pull/222 is force-pushed.

**Comment by 708yamaguchi** [comment]
@k-okada

> wait for upstream release ??

We do not need to wait for upstream release.

In fetch PC, we use `knorth55/jsk_common`'s `fetch15` branch.
https://github.com/jsk-ros-pkg/jsk_robot/blob/3d65836ae698680df509cae54a7c150555f2f93b/jsk_fetch_robot/jsk_fetch.rosinstall.melodic#L31-L34

In this branch, `sanity_diagnostics.py` is already merged.
https://github.com/knorth55/jsk_common/pull/4

**Comment by 708yamaguchi** [comment]
Cherry-pick https://github.com/knorth55/jsk_robot/pull/240 to publish diagnostics for more topics.

**Review by k-okada — COMMENTED** [review]
please resolve confllicts and pass CI

**Comment by 708yamaguchi** [comment]
The kinetic test fails.
https://github.com/jsk-ros-pkg/jsk_robot/runs/7748594263?check_suite_focus=true

This is because `jsk_tools/sanity_diagnotics.py` (new in jsk_tools 2.2.12) is not installed in kinetic.

```
2022-08-09T14:59:52.6084488Z Setting up ros-kinetic-jsk-tools (2.2.11-1xenial-20210503-140551-0800) ...
```

```
2022-08-09T15:11:11.6772391Z FAILURE:
2022-08-09T15:11:11.6772530Z 
2022-08-09T15:11:11.6772650Z                                                                                 
2022-08-09T15:11:11.6773098Z [/github/home/ros/ws_jsk_robot/src/jsk_robot/jsk_fetch_robot/jsk_fetch_startup/launch/fetch_gazebo_bringup.launch]:
2022-08-09T15:11:11.6773383Z 
2022-08-09T15:11:11.6773516Z                                                                                 
2022-08-09T15:11:11.6773869Z 	cannot find node [sanity_diagnostics.py] in package [jsk_tools]
2022-08-09T15:11:11.8218475Z -- run_tests.py: verify result "/github/home/ros/ws_jsk_robot/build/jsk_fetch_startup/test_results/jsk_fetch_startup/roslaunch-check_launch_rviz.launch.xml"
2022-08-09T15:11:11.8218832Z 
2022-08-09T15:11:11.8218838Z 
2022-08-09T15:11:11.8219007Z                                                                                 
2022-08-09T15:11:11.8219431Z Built target _run_tests_jsk_fetch_startup_roslaunch-check_launch_rviz.launch
2022-08-09T15:11:11.8219642Z 
2022-08-09T15:11:11.8219648Z 
2022-08-09T15:11:11.8219766Z                                                                                 
2022-08-09T15:11:11.8220433Z Scanning dependencies of target _run_tests_jsk_fetch_startup_roslaunch-check_launch_fetch_gazebo_bringup.launch
2022-08-09T15:11:11.8220681Z 
2022-08-09T15:11:11.8220686Z 
2022-08-09T15:11:11.8220803Z                                                                                 
2022-08-09T15:11:11.8221113Z -- run_tests.py: execute commands
2022-08-09T15:11:11.8221263Z 
2022-08-09T15:11:11.8221394Z                                                                                 
2022-08-09T15:11:11.8221880Z   /usr/bin/cmake -E make_directory /github/home/ros/ws_jsk_robot/build/jsk_fetch_startup/test_results/jsk_fetch_startup
2022-08-09T15:11:11.8222115Z 
2022-08-09T15:11:11.8222230Z                                                                                 
2022-08-09T15:11:11.8223210Z   /github/home/ros/ws_jsk_robot/src/jsk_robot/jsk_fetch_robot/jsk_fetch_startup/scripts/roslaunch-check -o '/github/home/ros/ws_jsk_robot/build/jsk_fetch_startup/test_results/jsk_fetch_startup/roslaunch-check_launch_fetch_gazebo_bringup.launch.xml' '/github/home/ros/ws_jsk_robot/src/jsk_robot/jsk_fetch_robot/jsk_fetch_startup/launch/fetch_gazebo_bringup.launch' 
2022-08-09T15:11:11.8223740Z 
2022-08-09T15:11:11.8223745Z 
2022-08-09T15:11:11.8223863Z                                                                                 
2022-08-09T15:11:11.8224229Z checking /github/home/ros/ws_jsk_robot/src/jsk_robot/jsk_fetch_robot/jsk_fetch_startup/launch/fetch_gazebo_bringup.launch
2022-08-09T15:11:11.8224733Z 
2022-08-09T15:11:11.8224737Z 
2022-08-09T15:11:11.8224852Z                                                                                 
2022-08-09T15:11:11.8225178Z Missing package dependencies: fetch_gazebo/package.xml: robot_state_publisher, topic_tools
2022-08-09T15:11:11.8225409Z 
2022-08-09T15:11:11.8225523Z                                                                                 
2022-08-09T15:11:11.8225854Z Missing package dependencies: jsk_maps/package.xml: tf, map_server, roseus, topic_tools
2022-08-09T15:11:11.8226079Z 
2022-08-09T15:11:11.8226295Z                                                                                 
2022-08-09T15:11:11.8226720Z Missing package dependencies: jsk_fetch_startup/package.xml: jsk_network_tools, sound_play, jsk_fetch_diagnosis, fetch_gazebo, tf, jsk_tools, nodelet, gazebo_ros
2022-08-09T15:11:11.8227019Z 
2022-08-09T15:11:11.8227024Z 
2022-08-09T15:11:11.8227142Z                                                                                 
2022-08-09T15:11:11.8227498Z Missing package dependencies: jsk_robot_startup/package.xml: topic_tools, roseus, rosapi, rostwitter
2022-08-09T15:11:11.8227734Z 
2022-08-09T15:11:11.8227739Z 
2022-08-09T15:11:11.8227854Z                                                                                 
2022-08-09T15:11:11.8228439Z ...writing test results to /github/home/ros/ws_jsk_robot/build/jsk_fetch_startup/test_results/jsk_fetch_startup/roslaunch-check_launch_fetch_gazebo_bringup.launch.xml
2022-08-09T15:11:11.8228739Z 
2022-08-09T15:11:11.8228743Z 
2022-08-09T15:11:11.8228860Z                                                                                 
2022-08-09T15:11:11.8229437Z wrote test file to [/github/home/ros/ws_jsk_robot/build/jsk_fetch_startup/test_results/jsk_fetch_startup/roslaunch-check_launch_fetch_gazebo_bringup.launch.xml]
2022-08-09T15:11:11.8229735Z 
2022-08-09T15:11:11.8229740Z 
2022-08-09T15:11:11.8229857Z                                                                                 
2022-08-09T15:11:11.8230438Z -- run_tests.py: verify result "/github/home/ros/ws_jsk_robot/build/jsk_fetch_startup/test_results/jsk_fetch_startup/roslaunch-check_launch_fetch_gazebo_bringup.launch.xml"
```

**Comment by 708yamaguchi** [comment]
All tests have passed by adding `jsk_common` 2.2.12 to `.travis.rosinstall.kinetic`

**Comment by k-okada** [comment]
please add following code to `jsk_fetch_startup/package.xml`

```
  <run_depend version_gte="2.2.12">jsk_tools</run_depend>
  <run_depend>jsk_network_tools</run_depend>
  <run_depend>sound_play</run_depend>
  <run_depend>jsk_fetch_diagnosis</run_depend>
  <run_depend>tf</run_depend>
  <run_depend>nodelet</run_depend>

```
the list of packages is taken from https://github.com/jsk-ros-pkg/jsk_robot/runs/7748594263?check_suite_focus=true and inteintinally removed gazebo packages, because it is not necessary for real application.
```
2022-08-09T15:11:11.8226720Z Missing package dependencies: jsk_fetch_startup/package.xml: jsk_network_tools, sound_play, jsk_fetch_diagnosis, fetch_gazebo, tf, jsk_tools, nodelet, gazebo_ros
```

**Comment by 708yamaguchi** [comment]
> please add following code to jsk_fetch_startup/package.xml

Thank you very much for your advice.
I updated. [`ea5bb8d` (#1481)](https://github.com/jsk-ros-pkg/jsk_robot/pull/1481/commits/ea5bb8de71b9f5fbe2ab2fe62a1f123ac33febda)

**Pull request merged**
