### PR TITLE
[baxtereus] Don't set DISPLAY to empty in baxter moveit test

### PR DESCRIPTION
**Pull request by pazeshun**
Updated version of #1058 
Includes #1065 

This fixes the issue detected with #1065 

Setting DISPLAY to empty kills /baxter_sim_io and causes error in joint trajectory servers.
cf. https://github.com/jsk-ros-pkg/jsk_robot/pull/1057#issuecomment-484455652, https://github.com/jsk-ros-pkg/jsk_robot/pull/1057#issuecomment-484456809, https://github.com/jsk-ros-pkg/jsk_robot/pull/1057#issuecomment-484458068

### CODE REVIEW

**Comment by pazeshun** [comment]
Test of this PR correctly passed.
Test of #1065 correctly failed.

**Comment by k-okada** [comment]
I will merge after we got someone's approval

FYI:

1) sometimes, people write dummy  publisher (in this case /robot/digital_io/right_lower_cuff) only for test code, disabling DISPLAY did not run any GUI program and expected to speed up the test code , or reduce CPU load
https://github.com/PR2/pr2_simulator/blob/kinetic-devel/pr2_gazebo/launch/pr2_bringup.launch#L7-L8

2) I'm interested in using `:fastest` keyword in test code, since you had a lot of work on speeding up `reset-pose` motions -> https://github.com/jsk-ros-pkg/jsk_pr2eus/blob/master/pr2eus/robot-interface.l#L380

**Comment by pazeshun** [comment]
>     1. sometimes, people write dummy  publisher (in this case /robot/digital_io/right_lower_cuff) only for test code, disabling DISPLAY did not run any GUI program and expected to speed up the test code , or reduce CPU load
>        https://github.com/PR2/pr2_simulator/blob/kinetic-devel/pr2_gazebo/launch/pr2_bringup.launch#L7-L8

I didn't come up with this idea. I will keep this in mind for the time when we need to speed up the test.



>     2\. I'm interested in using `:fastest` keyword in test code, since you had a lot of work on speeding up `reset-pose` motions -> https://github.com/jsk-ros-pkg/jsk_pr2eus/blob/master/pr2eus/robot-interface.l#L380

In `test-baxter-moveit.l`, we check setting `:fast` in `:angle-vector` which uses [:angle-vector-motion-plan](https://github.com/jsk-ros-pkg/jsk_pr2eus/blob/0.3.14/pr2eus_moveit/euslisp/robot-moveit.l#L554) works (https://github.com/jsk-ros-pkg/jsk_robot/pull/1066/files#diff-2596d441ca2d48980a34d032850b9181L89) as well as setting duration [ms] works.
I think both tests are required.
By the way, `:fastest` in https://github.com/jsk-ros-pkg/jsk_pr2eus/blob/master/pr2eus/robot-interface.l#L380 is typo....
cf. https://github.com/jsk-ros-pkg/jsk_pr2eus/blob/master/pr2eus/robot-interface.l#L399

**Comment by pazeshun** [comment]
@knorth55 Could you review this?

**Pull request merged**
