### PR TITLE
[kinovaeus] Coloring kinova eusmodel

### PR DESCRIPTION
**Pull request by tkmtnt7000**
Duplicate of https://github.com/sktometometo/jsk_robot/pull/113

Coloring kinova eusmodel with this PR.
|**gen3_lite_gen3_lite_2f**|**gen3_robotiq_2f_85**|**gen3_robotiq_2f_140**|
|:---:|:---:|:---:|
||||

I also colored the spotkinova model for my thesis in https://github.com/sktometometo/jsk_robot/pull/112

### CODE REVIEW

**Comment by 708yamaguchi** [comment]
Nice PR.

It would be better if you add reference of this code.
Like
```
Copied from https://github.com/jsk-ros-pkg/jsk_robot/pull/1263
```
or
```
Reference https://github.com/jsk-ros-pkg/jsk_robot/pull/1263
```

**Comment by tkmtnt7000** [comment]
Thank you for advice.
I added reference and comment. 
I put it in all the relevant parts for now, so it may look a little busy.

**Review by 708yamaguchi — APPROVED** [review]

**Comment by k-okada** [comment]
Does URDF file have color information? If not please send PR to them. I think @tkmtnt7000 is super busy on his thesis, so assigned to @708yamaguchi

**Comment by 708yamaguchi** [comment]
@k-okada @tkmtnt7000 

> Does URDF file have color information? If not please send PR to them. I think @tkmtnt7000 is super busy on his thesis, so assigned to @708yamaguchi

Yes, move to https://github.com/jsk-ros-pkg/jsk_robot/pull/1429

**Pull request merged**
