### PR TITLE
[baxtereus] Pass start-time to start-offset-time of :angle-vector-motion-plan

### PR DESCRIPTION
**Pull request by pazeshun**
Updated version of #956 
Includes #1067 

This PR fixes the issue detected by #1067 with the same method as `fetcheus`
cf. https://github.com/jsk-ros-pkg/jsk_robot/blob/master/jsk_fetch_robot/fetcheus/fetch-interface.l#L79
https://github.com/jsk-ros-pkg/jsk_robot/blob/master/jsk_fetch_robot/fetcheus/fetch-interface.l#L82
https://github.com/jsk-ros-pkg/jsk_robot/blob/master/jsk_fetch_robot/fetcheus/fetch-interface.l#L91

### CODE REVIEW

**Comment by pazeshun** [comment]
Travis correctly passed and #1067 correctly failed.

**Comment by pazeshun** [comment]
@knorth55 Could you review this?

**Comment by knorth55** [comment]
`start-time` and `start-offset-time` are same, so it is pretty difficult API... :(

**Comment by k-okada** [comment]
@pazeshun @knorth55 could you add documentation to https://github.com/jsk-ros-pkg/jsk_pr2eus/blob/master/pr2eus_moveit/euslisp/robot-moveit.l#L558? to explain what is `start-time-offset` and others.

**Comment by pazeshun** [comment]
> @pazeshun @knorth55 could you add documentation to https://github.com/jsk-ros-pkg/jsk_pr2eus/blob/master/pr2eus_moveit/euslisp/robot-moveit.l#L558? to explain what is `start-time-offset` and others.

@k-okada I made https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/392

**Comment by pazeshun** [comment]
@k-okada I think this PR is ready to be merged.
Could you review this?

**Comment by k-okada** [comment]
BTW when you need to pass :start-time?

**Comment by pazeshun** [comment]
> BTW when you need to pass :start-time?

Once I wanted to use `:start-time` to synchronize gripper and arm.
Joint trajectory action server of gripper drops the trajectory point too near the current time.
However, further investigation reveals this is due to the time synchronization problem of gripper PC, so currently I don't use :start-time.

**Pull request merged**
