### PR TITLE
[fetcheus] remove unnecessary ros node initialization in the first line

### PR DESCRIPTION
**Pull request by takayuki5168**
For https://github.com/jsk-ros-pkg/jsk_robot/issues/1216

### CODE REVIEW

**Comment by Affonso-Gui** [comment]
The original `(ros::roseus "fetch")` initialization seems to be present since the first commit at https://github.com/jsk-ros-pkg/jsk_robot/commit/d77ffcb5937754345deb99bddc876e280f738b44#diff-d7eb7619176f5641c713e05e846088d4

@k-okada Any particular reason you can remember of for initializing the node when loading instead of from within `fetch-init` ? If not I think this PR is valid and might be a nice idea to integrate it before we have several fetch demos with the both machines that can possibly depend on the node name

@708yamaguchi @knorth55

**Comment by knorth55** [comment]
how about just removing this, but change like `pr2-interface.l`?
https://github.com/jsk-ros-pkg/jsk_pr2eus/blob/master/pr2eus/pr2-interface.l#L644

**Comment by Affonso-Gui** [comment]
@knorth55 

What do you mean? `fetch-init` is already like the `pr2-interface.l` one:
https://github.com/takayuki5168/jsk_robot/blob/remove-first-ros-node-initialization/jsk_fetch_robot/fetcheus/fetch-interface.l#L334

Or are you saying that we should change the `pr2-init` syntax to something else?

**Comment by knorth55** [comment]
@Affonso-Gui Oh, I didn't know that.

**Review by knorth55 — APPROVED** [review]

**Pull request merged**
