### PR TITLE
[fetch] Correct head orientation for look-at

### PR DESCRIPTION
**Pull request by Affonso-Gui**
Rotates head end-coords such that z axis faces forward in order to fix look-at method glitch (always faces down).

### CODE REVIEW

**Comment by k-okada** [comment]
please past irtviewer image showing before and after head end coordinates, also code that reproduce  your problem will help us (then I'll add test code to https://github.com/jsk-ros-pkg/jsk_robot/blob/master/jsk_fetch_robot/fetcheus/test/test-fetcheus.l)

**Comment by Affonso-Gui** [comment]
The following images show fetch's `head-end-coords` and `(orient-coords-to-axis (send *fetch* :rarm-end-coords) (v- (send (send *fetch* :rarm-end-coords) :worldpos) (send (send *fetch* :head-end-coords) :worldpos)))`, used on look-at inverse-kinematics-loop-for-look-at calculation, before and after changes, respectively, when submitted to:
```
(send *fetch* :init-pose)
(send *fetch* :look-at-hand :rarm)
```

BEFORE
look-at-hand-before


AFTER
look-at-hand-after

**Comment by k-okada** [comment]
Thank you, committed with test code #773

**Comment by k-okada** [comment]
@Affonso-Gui please create branches within your repository.

screenshot from 2017-04-28 21 07 33

**Comment by Affonso-Gui** [comment]
Sorry about that, my mistake.

**Comment by knorth55** [comment]
Can I remove these branches?

jsk_robot_branch

**Comment by k-okada** [comment]
I have removed closed/merged branch, @Affonso-Gui please check 
https://github.com/jsk-ros-pkg/jsk_robot/commit/dce7806d01dce7ac631be7e1cf9fce54ac1da676
https://github.com/jsk-ros-pkg/jsk_robot/commit/00c44be053c4d5b4fbf5cdd7bc39f6feb1a4492e
https://github.com/jsk-ros-pkg/jsk_robot/commit/b4421e813f2428ddae0619bd6d869f672f27346c

**Comment by Affonso-Gui** [comment]
@k-okada Checked.
@knorth55 Deleted 1 to 4. patch5 seems to still be active on #774 . (Apologize for the mistake on uploading several similar and with non-clear name branchs)

**Comment by pazeshun** [comment]
You can change PR branch.
So you can move patch5 branch to your fork repository, change PR branch to that branch and remove patch5 from this repository.

**Pull request closed without merging**
