### PR TITLE
PR2 Noetic Branch

### PR DESCRIPTION
**Pull request by knorth55**
PR2 Noetic branch

Now PR1040 is using this branch.

### CODE REVIEW

**Review by tkmtnt7000 — COMMENTED** [review]
Just a quick look, but I may not think pr1040 is publishing `speech_to_text`.

**Comment by knorth55** [comment]
`/speech_to_text` is published from `/speech_to_text_mux`.
`mux` does not register publisher until the topic arrived.

**Comment by tkmtnt7000** [comment]
Thank you. I understand.

**Comment by tkmtnt7000** [comment]
That's why we have to speak to PR2, "ねえねえ" twice when we are going to launch applications from dialogflow task executive.

**Comment by knorth55** [comment]
yes.
and the problem can be solved by this PR.

https://github.com/ros/ros_comm/pull/2305

**Pull request closed without merging**
