### PR TITLE
[jsk_pr2_startup/pr2_gazebo.launch] add pr2_gazebo.launch

### PR DESCRIPTION
**Pull request by furushchev**
pr2_gazebo.launch is gazebo version of pr2.launch with disabling hardware dependent nodes

Now it works at the development level like image below:

pr2_gazebo

### CODE REVIEW

**Comment by furushchev** [comment]
BTW, when launching pr2_gazebo.launch and RViZ on my macbook pro retina, it takes cpu load about 33.0 and real time factor 0.22, wow...

**Comment by k-okada** [comment]
why we need
https://github.com/jsk-ros-pkg/jsk_robot/pull/365/files#diff-84a1a248eceac3613a6243f31cc35f6dR23

please compare with pr2_empty_world.launch, I assume it is mainly python
code take more cpu resources the we expecting, see to
http://answers.ros.org/question/29425/rospy-horrible-performance-with-sim_time/

Can we try slow simulation or clock step?

--
◉ Kei Okada

**Comment by furushchev** [comment]
in `roslaunch pr2_gazebo pr2_empty_world.launch`:

```bash
$ rostopic list|grep kinect
/head_mount_kinect/depth/camera_info
/head_mount_kinect/depth/image_raw
/head_mount_kinect/depth/image_raw/compressed
/head_mount_kinect/depth/image_raw/compressed/parameter_descriptions
/head_mount_kinect/depth/image_raw/compressed/parameter_updates
/head_mount_kinect/depth/image_raw/compressedDepth
/head_mount_kinect/depth/image_raw/compressedDepth/parameter_descriptions
/head_mount_kinect/depth/image_raw/compressedDepth/parameter_updates
/head_mount_kinect/depth/image_raw/theora
/head_mount_kinect/depth/image_raw/theora/parameter_descriptions
/head_mount_kinect/depth/image_raw/theora/parameter_updates
/head_mount_kinect/depth/points
/head_mount_kinect/depth_registered/points
/head_mount_kinect/rgb/camera_info
/head_mount_kinect/rgb/image_raw
/head_mount_kinect/rgb/image_raw/compressed
/head_mount_kinect/rgb/image_raw/compressed/parameter_descriptions
/head_mount_kinect/rgb/image_raw/compressed/parameter_updates
/head_mount_kinect/rgb/image_raw/compressedDepth
/head_mount_kinect/rgb/image_raw/compressedDepth/parameter_descriptions
/head_mount_kinect/rgb/image_raw/compressedDepth/parameter_updates
/head_mount_kinect/rgb/image_raw/theora
/head_mount_kinect/rgb/image_raw/theora/parameter_descriptions
/head_mount_kinect/rgb/image_raw/theora/parameter_updates
/head_mount_kinect_ir/parameter_descriptions
/head_mount_kinect_ir/parameter_updates
/head_mount_kinect_rgb/parameter_descriptions
/head_mount_kinect_rgb/parameter_updates
```

```bash
rostopic echo -n1 /head_mount_kinect/rgb/image_raw |head
header: 
  seq: 0
  stamp: 
    secs: 175
    nsecs: 953000000
  frame_id: head_mount_kinect_rgb_optical_frame
height: 480
width: 640
encoding: rgb8  # <- this is rgb8!
is_bigendian: 0
```

On the other hand, in real robot pr1012,

```bash
rostopic echo -n1 /kinect_head/rgb/image_raw |head
header: 
  seq: 1014993
  stamp: 
    secs: 1436150079
    nsecs: 912600756
  frame_id: /head_mount_kinect_rgb_optical_frame
height: 480
width: 640
encoding: bayer_grbg8  # <- bayer image
is_bigendian: 0
```

and I assumes that `image_raw` on gazebo and real robot is already different, so I copied the part which you quoted from `rgbd_launch/launch/includes/rgb.launch.xml` included in `openni_launch/openni.launch`

**Comment by k-okada** [comment]
include rgb.launch.xml ?

--
◉ Kei Okada

**Comment by furushchev** [comment]
I included rgb.launch.xml instead of copying.
https://github.com/jsk-ros-pkg/jsk_robot/commit/0918bf0544169e8f352dffb06e142bee3b3efe3c

**Comment by k-okada** [comment]
@YuOhara @otsubo シミュレーションが重いのは以下の話の可能性が高いので
 
http://answers.ros.org/question/29425/rospy-horrible-performance-with-sim_time/

クロックを200hzぐらいにしてどうなるか確認してみて下さい．

--
◉ Kei Okada

**Pull request merged**
