### PR TITLE
[jsk_pr2_startup] fix typo in pr2.launch

### PR DESCRIPTION
**Pull request by h-kamada**
In #368 , 
typo
defualt --> default

### CODE REVIEW

**Comment by k-okada** [comment]
good catch, I created test code to catch this situation see #373

**Comment by h-kamada** [comment]
created baxter version of checker in #375

**Comment by h-kamada** [comment]
pepper #377 
nao #376

**Comment by k-okada** [comment]
thanks, #373, #375, #377, #376 is much more difficult than we expected, see some fix at https://github.com/ros/ros_comm/pulls,  so I'll merge this without waiting for test code

**Comment by h-kamada** [comment]
You showed me PR list, and I'm searching. But I can't find the PR related with this issue.
Is there any related PR?

**Comment by k-okada** [comment]
https://github.com/ros/ros_comm/pull/641,

--
◉ Kei Okada

**Pull request merged**
