### PR TITLE
[jsk_robot_startup] add check_use_sim_time app

### PR DESCRIPTION
**Pull request by knorth55**
this PR adds `app` for checking and overriding `/use_sim_time` parameter on real robot.
we run this app every 10 minutes on PR1040.

@shmpwk

### CODE REVIEW

**Comment by knorth55** [comment]
@708yamaguchi maybe this is useful for fetch, too.

**Comment by shmpwk** [comment]
Interesting! Does [thie picture](https://github.com/jsk-ros-pkg/jsk_robot/pull/1381/files#diff-f00f01aa3455c50843b56a0bb2cad2f0ee6a7e724b344af3f0ea6bff89874912) show up somewhere? 
I cannot get one even when I set `rosparam set /use_sim_time true` in PR2 and he say he will  overwrite /use_sim_time with false.

**Comment by knorth55** [comment]
what do you mean? the picture?

**Comment by knorth55** [comment]
PR2 run this app every 10 minutes, so tou need to wait for it

**Comment by shmpwk** [comment]
I mean [check_use_sim_time.png](https://github.com/jsk-ros-pkg/jsk_robot/blob/cd22f837f2e6688db6ed84aabe5c18d6918ae2e2/jsk_robot_common/jsk_robot_startup/apps/check_use_sim_time/check_use_sim_time.png) won't show up in 10 minutes at all.

**Comment by knorth55** [comment]
?
the png is just an icon for rwt_app_chooser

**Comment by shmpwk** [comment]
Thank you for teaching me rwt_app_chooser, I didn't now that.

**Comment by k-okada** [comment]
Nice. note that the icon is copied from https://www.irasutoya.com/2018/07/blog-post_935.html. I believe newness of software or paper is not important, but icon and picture must be unique and original.

c.f. https://www.youtube.com/watch?v=W3w0ZtGw5fQ&t=1845s

**Pull request merged**
