### PR TITLE
add light off app

### PR DESCRIPTION
**Pull request by 708yamaguchi**
cherry-picked from https://github.com/knorth55/jsk_robot/pull/123

Add app for light-on and light-off.

### CODE REVIEW

**Review by knorth55 — APPROVED** [review]

**Comment by 708yamaguchi** [comment]
I resolved the conflicts and rebased the current `origin/master` .

**Review by k-okada — CHANGES_REQUESTED** [review]
@708yamaguchi please consider using original/unique image https://github.com/jsk-ros-pkg/jsk_robot/pull/1459/files#diff-ced654aaa73e45265322a01051d8a015fc29cee724c4de5b2bfcf80555870629

**Comment by 708yamaguchi** [comment]
Thanks to @MiyabiTane , original icon is added.

**Review by k-okada — APPROVED** [review]

**Comment by k-okada** [comment]
💯 !!!

**Pull request merged**
