### PR TITLE
[Wait for upstream] [jsk_pr2_startup, jsk_fetch_startup] use app_manager as plugin

### PR DESCRIPTION
**Pull request by knorth55**
split from #1081 
load `apps` as plugin 
cc. @furushchev

### CODE REVIEW

**Comment by k-okada** [comment]
@708yamaguchi please check on Fetch robot

**Comment by knorth55** [comment]
@708yamaguchi @k-okada 
```
fetch@fetch15:~/ros/indigo/src/jsk-ros-pkg/jsk_robot/jsk_fetch_robot/jsk_fetch_startup$ rospack plugins --attrib=app_dir app_manager
jsk_fetch_startup /home/fetch/ros/indigo/src/jsk-ros-pkg/jsk_robot/jsk_fetch_robot/jsk_fetch_startup/apps
jsk_pr2_startup /home/fetch/ros/indigo/src/jsk-ros-pkg/jsk_robot/jsk_pr2_robot/jsk_pr2_startup/apps
```

`/var/log/upstart/jsk-fetch-startup.log`
```
[INFO] [WallTime: 1558612901.923929] Client connected.  1 clients total.
[INFO] [WallTime: 1558612902.273419] [Client 0] Subscribed to /fetch15/app_list
[INFO] [WallTime: 1558612911.194977] start_app: jsk_fetch_startup/hello_world
[INFO] [WallTime: 1558612911.195209] Loading app: jsk_fetch_startup/hello_world
[INFO] [WallTime: 1558612912.072172] Launching: /home/fetch/ros/indigo/src/jsk-ros-pkg/jsk_robot/jsk_fetch_robot/jsk_fetch_startup/apps/hello_world/hello_world.xml
started roslaunch server http://fetch15:55140/

SUMMARY
========

PARAMETERS
 * /rosdistro: indigo
 * /rosversion: 1.11.21

NODES
  /
    run_hello_world (jsk_fetch_startup/boot_sound.py)

ROS_MASTER_URI=http://localhost:11311
core service [/rosout] found
process[run_hello_world-1]: started with pid [13437]
[INFO] [WallTime: 1558612912.522123] Waiting for foreign master [http://localhost:11313] to come up...
[INFO] [WallTime: 1558612912.523723] Foreign master is available
[run_hello_world-1] process has finished cleanly
log file: /home/fetch/.ros/log/6a608bf8-7d52-11e9-a43b-d8cb8a40210c/run_hello_world-1*.log
all processes on machine have died, roslaunch will exit
[INFO] [WallTime: 1558612926.165813] handle stop app: stopping app [jsk_fetch_startup/hello_world]
[INFO] [WallTime: 1558612926.545750] handle stop app: app [jsk_fetch_startup/hello_world] stopped
```

**Comment by 708yamaguchi** [comment]
I also tested `app_manager` with `knorth55/app-manager` branch.

I did hello world app on real Fetch robot.

**Comment by knorth55** [comment]
Test failed because `app_manager` `1.1.1` is not released in both `kinetic` and `melodic`.
I made a release request `1.1.1` in `app_manager`.
However, we need to install `app_manger` by source because inddigo which runs in PR2 and fetch is EOL.
https://github.com/PR2/app_manager/issues/12

**Comment by knorth55** [comment]
We need this release for build passing.
https://github.com/PR2/app_manager/issues/12

**Pull request merged**
