### PR TITLE
[jsk_pr2_startup] fix ntp monitor in pr2_bringup.launch

### PR DESCRIPTION
**Pull request by knorth55**
split from #1081 
disable ntp monitoer in `pr2_bringup.launch`
cc. @furushchev

### CODE REVIEW

**Comment by k-okada** [comment]
why did you remove this. I think time synchronization between c2 and c2 is veery important...

**Comment by knorth55** [comment]
i have no idea why it is disabled in `PR1040` but it is disabled by @furushchev .
i will test if it works with `launch_ntp_monitor:=true`.

**Comment by knorth55** [comment]
i update to fix ntp monitor, and now it works!
ntp_robot_monitor

**Comment by knorth55** [comment]
@k-okada can you merge this PR?

**Pull request merged**
