### PR TITLE
[WIP] [jsk_pr2_robot] Add PR2 teleop command list

### PR DESCRIPTION
**Pull request by YutoUchimi**

### CODE REVIEW

**Comment by furushchev** [comment]
I recommend to remap `/teleop/joy_vel` to `/base_controller/command_unchecked` for teleop node and just remove the `rosrun` part from the pics.

**Comment by furushchev** [comment]
The comment above is wrong, sorry, please revert the change.
You might have to create a node to dynamically switch `/teleop/joy_vel` to `/base_controller/command_unchecked` only when follow hand mode instead.

**Comment by knorth55** [comment]
@YutoUchimi what is status of this issue?

**Comment by YutoUchimi** [comment]
I reverted the remap commit and pushed only document addition commit.
The remapping should be fixed in another PR, so this PR is ready to be merged.

**Pull request merged**
