### PR TITLE
[jsk_pr2_startup/package.xml] add run_dependency.

### PR DESCRIPTION
**Pull request by mmurooka**
https://github.com/jsk-ros-pkg/jsk_robot/issues/576

### CODE REVIEW

**Comment by mmurooka** [comment]
travis error
https://s3.amazonaws.com/archive.travis-ci.org/jobs/118187854/log.txt
```
[jsk_fetch_startup] checking /workspace/ros/ws_jsk_robot/src/jsk_robot/jsk_fetch_robot/jsk_fetch_startup/launch/fetch_bringup.launch 
[jsk_fetch_startup] ...writing test results to /workspace/ros/ws_jsk_robot/build/jsk_fetch_startup/test_results/jsk_fetch_startup/roslaunch-check_launch_fetch_bringup.launch.xml 
[jsk_fetch_startup] FAILURE:                                                    
[jsk_fetch_startup] [/workspace/ros/ws_jsk_robot/src/jsk_robot/jsk_fetch_robot/jsk_fetch_startup/launch/fetch_bringup.launch]: 
[jsk_fetch_startup] 	Invalid <arg> tag: jsk_maps                                
[jsk_fetch_startup] ROS path [0]=/opt/ros/indigo/share/ros                      
[jsk_fetch_startup] ROS path [1]=/workspace/ros/ws_jsk_robot/src/jsk_robot/jsk_baxter_robot/baxtereus 
[jsk_fetch_startup] ROS path [2]=/workspace/ros/ws_jsk_robot/src/jsk_robot/jsk_fetch_robot/jsk_fetch_startup 
[jsk_fetch_startup] ROS path [3]=/workspace/ros/ws_jsk_robot/src/jsk_robot/jsk_baxter_robot/baxtereus 
[jsk_fetch_startup] ROS path [4]=/workspace/ros/ws_jsk_robot/src/jsk_robot/jsk_fetch_robot/jsk_fetch_startup 
[jsk_fetch_startup] ROS path [5]=/workspace/ros/ws_jsk_robot/src/jsk_robot/jsk_naoqi_robot/jsk_nao_startup 
[jsk_fetch_startup] ROS path [6]=/workspace/ros/ws_jsk_robot/src/jsk_robot/jsk_baxter_robot/jsk_baxter_startup 
[jsk_fetch_startup] ROS path [7]=/workspace/ros/ws_jsk_robot/src/jsk_robot/jsk_pr2_robot/jsk_pr2_calibration 
[jsk_fetch_startup] ROS path [8]=/workspace/ros/ws_jsk_robot/src/jsk_robot/jsk_robot_common/jsk_robot_startup 
[jsk_fetch_startup] ROS path [9]=/workspace/ros/ws_jsk_robot/src/jsk_robot/jsk_robot_common/jsk_robot_utils 
[jsk_fetch_startup] ROS path [10]=/workspace/ros/ws_jsk_robot/src/jsk_robot/jsk_naoqi_robot/naoqieus 
[jsk_fetch_startup] ROS path [11]=/workspace/ros/ws_jsk_robot/src/jsk_robot/jsk_pr2_robot/pr2_base_trajectory_action 
[jsk_fetch_startup] ROS path [12]=/workspace/ros/ws_jsk_robot/src/jsk_robot/jsk_robot_common/roseus_remote 
[jsk_fetch_startup] ROS path [13]=/workspace/ros/ws_jsk_robot/src/jsk_robot/jsk_baxter_robot/jsk_baxter_desktop 
[jsk_fetch_startup] ROS path [14]=/workspace/ros/ws_jsk_robot/src/jsk_robot/jsk_naoqi_robot/naoeus 
[jsk_fetch_startup] ROS path [15]=/workspace/ros/ws_jsk_robot/src/jsk_robot/jsk_naoqi_robot/peppereus 
[jsk_fetch_startup] ROS path [16]=/workspace/ros/ws_jsk_robot/src/jsk_robot/jsk_pr2_robot/jsk_pr2_startup 
[jsk_fetch_startup] ROS path [17]=/workspace/ros/ws_jsk_robot/src/jsk_robot/jsk_naoqi_robot/jsk_pepper_startup 
[jsk_fetch_startup] ROS path [18]=/workspace/ros/ws_jsk_robot/src/jsk_robot/jsk_fetch_robot/fetcheus 
[jsk_fetch_startup] ROS path [19]=/workspace/ros/ws_jsk_robot/src/jsk_robot/jsk_baxter_robot/jsk_baxter_web 
[jsk_fetch_startup] ROS path [20]=/workspace/ros/ws_jsk_robot/src/jsk_robot/jsk_naoqi_robot/jsk_201504_miraikan 
[jsk_fetch_startup] ROS path [21]=/opt/ros/indigo/share                         
[jsk_fetch_startup] ROS path [22]=/opt/ros/indigo/stacks.                       
[jsk_fetch_startup]                                                             
[jsk_fetch_startup] Arg xml is <arg default="$(find jsk_maps)/raw_maps/eng2-7f-0.05.yaml" name="map_file"/> 
```

**Comment by k-okada** [comment]
please look into the problem...

```
executing command [sudo -H apt-get install -y -qq ros-indigo-jsk-maps]
E: Unable to locate package ros-indigo-jsk-maps
```
could not install jsk_maps, but that should be released...
http://repositories.ros.org/status_page/ros_indigo_default.html?q=jsk_maps

failed to compile, look inside again...

http://build.ros.org/view/Ibin_uT64/job/Ibin_uT64__jsk_maps__ubuntu_trusty_amd64__binary/
tells the blocker is jsk_rviz_plugins. 
http://build.ros.org/view/Ibin_uT64/job/Ibin_uT64__jsk_rviz_plugins__ubuntu_trusty_amd64__binary/

**Comment by k-okada** [comment]
ok, finally fixed in https://github.com/jsk-ros-pkg/jsk_visualization/pull/586

**Comment by mmurooka** [comment]
Thank you.
https://github.com/jsk-ros-pkg/jsk_control/pull/574#issuecomment-200491601 is also same problem, and should be passed by jsk_rviz_plugins fix.

**Comment by mmurooka** [comment]
Jenkins fails at `sudo docker rmi`.
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis-jsk-ros-pkg-jsk_robot-indigo-deb-true/816/console
```
...
13:55:56 + git submodule init
13:55:56 Submodule '.travis' (https://github.com/jsk-ros-pkg/jsk_travis.git) registered for path '.travis'
13:55:56 + git submodule update
13:55:56 Cloning into '.travis'...
13:55:59 Submodule path '.travis': checked out '38a90723016599b528f13d6699cac402420101ca'
13:55:59 + sudo docker images
13:55:59 + awk /^<none>/ { print $3 }
13:55:59 + sudo docker rmi b3214481f00b
15:55:43 Build timed out (after 120 minutes). Marking the build as failed.
15:55:43 Build was aborted
15:55:43 Finished: FAILURE
```

**Comment by mmurooka** [comment]
Jenkins test passed after @wkentaro did `restart docker`. Thank you.

Please merge if no problem.

**Pull request merged**
