### PR TITLE
[jsk_robot_startup] Use parameter_yaml arg instead of ROBOT environmental value for odometry params

### PR DESCRIPTION
**Pull request by orikuma**
Related with https://github.com/jsk-ros-pkg/jsk_robot/pull/401#issuecomment-167803804

### CODE REVIEW

**Comment by k-okada** [comment]
need rebase

**Comment by orikuma** [comment]
Please wait until check in real robot.

**Comment by orikuma** [comment]
Checked in JAXON_RED.
Please merge with https://github.com/start-jsk/rtmros_hrp2/pull/352 and https://github.com/jsk-ros-pkg/trans_system/pull/586

**Comment by orikuma** [comment]
Fixed PR, too

**Comment by orikuma** [comment]
please merge

**Comment by k-okada** [comment]
do we still have to use ROBOT environment, even if we merged ->
https://github.com/start-jsk/rtmros_common/pull/944


--
◉ Kei Okada

**Comment by k-okada** [comment]
sorry this PR remove ROBOT environment, but introduced new scheme.

**Pull request merged**
