### PR TITLE
[.travis] update travis to 0.4.25

### PR DESCRIPTION
**Pull request by furushchev**
- update `.travis` to 0.4.23
- cleanup `.travis.yml`

### CODE REVIEW

**Comment by furushchev** [comment]
```bash
Loading extension GLX
(EE) 
Fatal server error:
(EE) no screens found(EE) 
(EE) 
Please consult the The X.Org Foundation support 
	 at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/xorg.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
+ grep GLX
+ glxinfo
Error: unable to open display :0
```

still cannot open display. That is strange because my another repository successfully opens display.
https://github.com/furushchev/travis-test/tree/x11
https://travis-ci.org/furushchev/travis-test/jobs/199481290

```
Loading extension GLX
    GLX_ARB_multisample, GLX_EXT_import_context, GLX_EXT_texture_from_pixmap, 
    GLX_EXT_visual_info, GLX_EXT_visual_rating, GLX_MESA_copy_sub_buffer, 
    GLX_OML_swap_method, GLX_SGIS_multisample, GLX_SGIX_fbconfig, 
    GLX_SGIX_pbuffer, GLX_SGI_make_current_read
    GLX_ARB_create_context, GLX_ARB_create_context_profile, 
    GLX_ARB_create_context_robustness, GLX_ARB_fbconfig_float, 
    GLX_ARB_framebuffer_sRGB, GLX_ARB_get_proc_address, GLX_ARB_multisample, 
    GLX_EXT_create_context_es2_profile, GLX_EXT_fbconfig_packed_float, 
    GLX_EXT_framebuffer_sRGB, GLX_EXT_import_context, 
    GLX_EXT_texture_from_pixmap, GLX_EXT_visual_info, GLX_EXT_visual_rating, 
    GLX_INTEL_swap_event, GLX_MESA_copy_sub_buffer, 
    GLX_MESA_multithread_makecurrent, GLX_MESA_query_renderer, 
    GLX_MESA_swap_control, GLX_OML_swap_method, GLX_OML_sync_control, 
    GLX_SGIS_multisample, GLX_SGIX_fbconfig, GLX_SGIX_pbuffer, 
    GLX_SGIX_visual_select_group, GLX_SGI_make_current_read, 
    GLX_SGI_swap_control, GLX_SGI_video_sync
GLX version: 1.4
GLX extensions:
    GLX_ARB_get_proc_address, GLX_ARB_multisample, GLX_EXT_import_context, 
    GLX_EXT_texture_from_pixmap, GLX_EXT_visual_info, GLX_EXT_visual_rating, 
    GLX_MESA_copy_sub_buffer, GLX_MESA_multithread_makecurrent, 
    GLX_OML_swap_method, GLX_SGIS_multisample, GLX_SGIX_fbconfig, 
    GLX_SGIX_pbuffer, GLX_SGI_make_current_read
120 GLX Visuals
180 GLXFBConfigs:
```

**Comment by furushchev** [comment]
wait for jsk-ros-pkg/jsk_travis#323

**Comment by k-okada** [comment]
ok, merged and released

--
◉ Kei Okada


2017-02-17 11:22 GMT+09:00 Furushchev <notifications@github.com>:

**Comment by furushchev** [comment]
@k-okada Thank you!
Updated travis and now waiting for result.

**Comment by furushchev** [comment]
test passed. @k-okada Please review and merge if there is no problem.

**Comment by k-okada** [comment]
can we add kinetic test?

**Comment by furushchev** [comment]
MEMO:

on `jade`:

```
Errors << jsk_baxter_startup:cmake /home/travis/ros/ws_jsk_robot/logs/jsk_baxter_startup/build.cmake.000.log
CMake Warning at /opt/ros/jade/share/catkin/cmake/catkinConfig.cmake:76 (find_package):
  Could not find a package configuration file provided by "baxter_core_msgs"
  with any of the following names:

    baxter_core_msgsConfig.cmake
    baxter_core_msgs-config.cmake

  Add the installation prefix of "baxter_core_msgs" to CMAKE_PREFIX_PATH or
  set "baxter_core_msgs_DIR" to a directory containing one of the above
  files.  If "baxter_core_msgs" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:4 (find_package)


CMake Error at /opt/ros/jade/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "baxter_core_msgs"
  with any of the following names:

    baxter_core_msgsConfig.cmake
    baxter_core_msgs-config.cmake

  Add the installation prefix of "baxter_core_msgs" to CMAKE_PREFIX_PATH or
  set "baxter_core_msgs_DIR" to a directory containing one of the above
  files.  If "baxter_core_msgs" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:4 (find_package)
```

on `kinetic`:

```
Errors << fetcheus:cmake /home/travis/ros/ws_jsk_robot/logs/fetcheus/build.cmake.000.log
CMake Warning at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:76 (find_package):
  Could not find a package configuration file provided by "fetch_description"
  with any of the following names:

    fetch_descriptionConfig.cmake
    fetch_description-config.cmake

  Add the installation prefix of "fetch_description" to CMAKE_PREFIX_PATH or
  set "fetch_description_DIR" to a directory containing one of the above
  files.  If "fetch_description" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:10 (find_package)


CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "fetch_description"
  with any of the following names:

    fetch_descriptionConfig.cmake
    fetch_description-config.cmake

  Add the installation prefix of "fetch_description" to CMAKE_PREFIX_PATH or
  set "fetch_description_DIR" to a directory containing one of the above
  files.  If "fetch_description" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:10 (find_package)
```

Both added to `allow_failures`

**Comment by furushchev** [comment]
ok, now test passed.

**Pull request merged**
