### PR TITLE
add rocon chatter sample between pr1012/pr1040 launch/configs

### PR DESCRIPTION
**Pull request by aginika**
add the chatter sample for two pr2 communication.

This need the third machine to execute.

Please make the environment like below.
I didn't confirm but if you try to communicate with pr2s, topic might not come even when node is copied. (Because of VPN?)

pr2_rocon

If you successed to launch, the below will be shown in terminal for chatter_pr1012_rocon.launch
```
core service [/rosout] found
process[zeroconf/zeroconf-1]: started with pid [28166]
process[gateway-2]: started with pid [28167]
process[talker_pr1012-3]: started with pid [28171]
[INFO] [WallTime: 1449067598.154576] Gateway : generated unique hash name [jsk_pr1012_ece95d2b544747649998290766aba3de]
[INFO] [WallTime: 1449067598.159295] Gateway : adding rule to public watchlist [publisher][/hoge][]
[WARN] [WallTime: 1449067598.161820] Interface wan0 requested, but I  was unabled to find it on the system. I will try  and auto-detect the interface.
[INFO] [WallTime: 1449067598.207123] Gateway : checking if zeroconf services are available...
[ INFO] [1449067598.219405770]: Zeroconf: added a listener [_ros-multimaster-hub._tcp]
[ INFO] [1449067605.310407072]: Zeroconf: discovered new service [Rocon Hub][_ros-multimaster-hub._tcp][local][3][ipv4]
[ INFO] [1449067605.810628492]: Zeroconf: resolved service [Rocon Hub][_ros-multimaster-hub._tcp][local][3][ipv4][133.11.216.158:6380]
[INFO] [WallTime: 1449067606.472161] Gateway : Found existing mismatched public key on the hub. Requesting resend for all flip-ins.
[INFO] [WallTime: 1449067606.477081] Gateway : registering on the hub [Rocon Hub]
[INFO] [WallTime: 1449067606.480864] Gateway : discovered hub via zeroconf [localhost:6380]
[INFO] [WallTime: 1449067606.988567] Gateway : blacklisting hub [already connected to this hub]
[INFO] [WallTime: 1449067608.467120] Gateway : adding connection to public interface [publisher][/hoge][/talker_pr1012]
[INFO] [WallTime: 1449067620.798275] Gateway : pulling in connection [publisher][/fuga][/talker_pr1040][jsk_pr1040_cc1b1458a9914902a8fdefc9808e8743]
```

and in chatter_pr1040_rocon.launch
```
process[hub-1]: started with pid [28197]
process[zeroconf/zeroconf-2]: started with pid [28198]
process[gateway-3]: started with pid [28199]
process[talker_pr1040-4]: started with pid [28203]
[INFO] [WallTime: 1449067604.279589] Gateway : generated unique hash name [jsk_pr1040_cc1b1458a9914902a8fdefc9808e8743]
[INFO] [WallTime: 1449067604.283719] Gateway : adding rule to public watchlist [publisher][/fuga][]
[WARN] [WallTime: 1449067604.285554] Interface wan0 requested, but I  was unabled to find it on the system. I will try  and auto-detect the interface.
[INFO] [WallTime: 1449067604.329128] Gateway : checking if zeroconf services are available...
[ INFO] [1449067604.340335326]: Zeroconf: added a listener [_ros-multimaster-hub._tcp]
Established under name 'Rocon Hub'
[ INFO] [1449067605.310119182]: Zeroconf: discovered new service [Rocon Hub][_ros-multimaster-hub._tcp][local][3][ipv4]
[ INFO] [1449067605.810435658]: Zeroconf: resolved service [Rocon Hub][_ros-multimaster-hub._tcp][local][3][ipv4][133.11.216.158:6380]
[INFO] [WallTime: 1449067605.958515] Gateway : Found existing mismatched public key on the hub. Requesting resend for all flip-ins.
[INFO] [WallTime: 1449067605.962064] Gateway : registering on the hub [Rocon Hub]
[INFO] [WallTime: 1449067605.964350] Gateway : discovered hub via zeroconf [localhost:6380]
[INFO] [WallTime: 1449067606.470755] Gateway : blacklisting hub [already connected to this hub]
[INFO] [WallTime: 1449067614.498957] Gateway : adding connection to public interface [publisher][/fuga][/talker_pr1040]
[INFO] [WallTime: 1449067614.502054] Gateway : pulling in connection [publisher][/hoge][/talker_pr1012][jsk_pr1012_ece95d2b544747649998290766aba3de]

```

### CODE REVIEW

**Comment by k-okada** [comment]
Please add sending robot position example too

**Comment by aginika** [comment]
add two samples.
- look sample
pr1012_look

- cameraman sample

**Comment by Horimotsu** [comment]
@k-okada Thankyou!

**Comment by snozawa** [comment]
@k-okada
Thanks!!!

**Pull request merged**
