### PR TITLE
add tweet app for fetch

### PR DESCRIPTION
**Pull request by knorth55**
i add tweet app for fetch.
we can run tweet by saying "ツイートして", "写真をとってください".

### CODE REVIEW

**Comment by k-okada** [comment]
@knorth55 please resolve conflicts

**Comment by knorth55** [comment]
I resolved the conflict.

**Comment by k-okada** [comment]
@knorth55 @708yamaguchi 
please resolve conflicts, what is the difference between `dock` and `simple-dock`
https://github.com/jsk-ros-pkg/jsk_robot/pull/1105/files

**Comment by knorth55** [comment]
I resolved the conflict.
`simple-dock` is to dock Fetch in front of the station, and `dock` is to dock anywhere from 73B2 room.

`simple-dock`: just dock
`dock`: load 73B2 map, go in front of fetch station and dock (`simple-dock`)

**Pull request merged**
