### PR TITLE
[jsk_nao_startup] delete nao_apps/speech.launch

### PR DESCRIPTION
**Pull request by kochigami**
speech.launch was added in https://github.com/jsk-ros-pkg/jsk_robot/commit/ae87138191b56d315d053af07bfd5174b4707654, 
which is before speech function was added in naoqi_driver.launch (https://github.com/ros-naoqi/naoqi_driver/pull/43).

This causes nao speaks twice. (https://github.com/jsk-ros-pkg/jsk_robot/issues/674)

### CODE REVIEW

**Comment by k-okada** [comment]
@kochigami can you fix the conflict ?

**Comment by kochigami** [comment]
Sorry, I'll fix it on Sunday or Monday.

**Comment by kochigami** [comment]
Sorry, I failed to fix conflicts, please wait a minute...

**Comment by k-okada** [comment]
Closed via #694

**Pull request closed without merging**
