### PR TITLE
[fetch] Exclude specific collision-check-pairs to ignore insignificant collisions

### PR DESCRIPTION
**Pull request by 708yamaguchi**
Before
======
When I send fetch `:reset-pose` and calculate `:self-collision-check` in euslisp, some collision pairs are always output like below.
```
2.irteusgl$ (send *fetch* :reset-pose)
#f(20.0 75.6304 80.2141 -11.4592 98.5487 0.0 95.111 0.0 0.0 0.0)
3.irteusgl$ (send *fetch* :self-collision-check)
((#<bodyset-link #X56d8ca8 base_link  0.0 0.0 0.0 / 0.0 0.0 0.0> . #<bodyset-link #X57bc388 bellows_link2  -86.875 0.0 397.43 / 0.0 0.0 0.0>) (#<bodyset-link #X56d8ca8 base_link  0.0 0.0 0.0 / 0.0 0.0 0.0> . #<bodyset-link #X57b7788 bellows_link  -86.875 0.0 397.43 / 0.0 0.0 0.0>) (#<bodyset-link #X57a00b0 torso_fixed_link  -86.875 0.0 377.425 / 0.0 0.0 0.0> . #<bodyset-link #X56d9a28 torso_lift_link  -86.875 0.0 397.43 / 0.0 0.0 0.0>) (#<bodyset-link #X57a00b0 torso_fixed_link  -86.875 0.0 377.425 / 0.0 0.0 0.0> . #<bodyset-link #X57bc388 bellows_link2  -86.875 0.0 397.43 / 0.0 0.0 0.0>) (#<bodyset-link #X57a00b0 torso_fixed_link  -86.875 0.0 377.425 / 0.0 0.0 0.0> . #<bodyset-link #X57b7788 bellows_link  -86.875 0.0 397.43 / 0.0 0.0 0.0>) (#<bodyset-link #X57bc388 bellows_link2  -86.875 0.0 397.43 / 0.0 0.0 0.0> . #<bodyset-link #X57b7788 bellows_link  -86.875 0.0 397.43 / 0.0 0.0 0.0>) (#<bodyset-link #X58b6458 r_gripper_finger_link  35.009 -126.734 756.756 / 1.961 -1.492 -0.445> . #<bodyset-link #X58ad070 l_gripper_finger_link  65.797 -128.387 757.797 / 1.961 -1.492 -0.445>))
```

Figure of `reset-pose` of fetch is shown below.
The output of `:self-collision-check` says that base link, bellows links and torso link collide, but this information seems to be meaningless.
fetch

After
=====
In this Pull Request, I exclude the specific pairs from `:collision-check-pairs`. With this Pull Request, output of `:self-collision-check` is below.
```
2.irteusgl$ (send *fetch* :reset-pose)
#f(20.0 75.6304 80.2141 -11.4592 98.5487 0.0 95.111 0.0 0.0 0.0)
3.irteusgl$ (send *fetch* :self-collision-check)
nil
```

### CODE REVIEW

**Comment by 708yamaguchi** [comment]
thank you for your cooperation, @itohdak

**Comment by Affonso-Gui** [comment]
Have you considered extracting the list of pairs to ignore from the moveit configuration file? 
https://github.com/fetchrobotics/fetch_ros/blob/melodic-devel/fetch_moveit_config/config/fetch.srdf

It seems that you have all the pairs marked as `Default` + the gripper one

**Comment by Affonso-Gui** [comment]
I do not believe we have any kind of utility to parse xml in euslisp (@k-okada please correct me if I am mistaken).
Being so, you could try one of the below:
1. Make your own parser
2. Parse in other language and provide the result through FFI / ROS/ save to file
3. Try to reproduce other xml-parsing common lisp packages (not very recommended, though)

This case should be simple enough to go for a custom parser, reading strings line-by-line or by delimiter

**Comment by Affonso-Gui** [comment]
Could also be interesting to give the .srdf config file as an optional parameter in `euscollada` and include collision information directly in the `robot.l`

**Comment by knorth55** [comment]
SRDF might be not enough because euslisp makes convex for each link as below link.
SRDF uses collision link written in URDF, and euslisp makes convex from euslisp robot model.
https://github.com/start-jsk/jsk_apc/pull/2624

I think writing SRDF parser is not a good idea, and just manually write and check various angle-vectors for checking.

**Comment by knorth55** [comment]
See also here https://github.com/jsk-ros-pkg/jsk_robot/pull/895

**Comment by Affonso-Gui** [comment]
Something like checking the collision pairs in reset-pose and adding them to collision-ignore (probably in the instance :init) ?

Since there should be no collision links in the reset-pose all pairs appearing in collision are interpreted as `Always in collision`

**Comment by k-okada** [comment]
@708yamaguchi please resolve conflicts

**Comment by 708yamaguchi** [comment]
I force-pushed the commit and resolved the conflicts.

**Pull request merged**
