### PR TITLE
Refactoring lifelog nodes

### PR DESCRIPTION
**Pull request by furushchev**
This PR is part of https://github.com/jsk-ros-pkg/jsk_robot/pull/696

- Enable test for logging nodes (using gazebo)
- Use TF2 to resolve frames (fallback TF1 on failure)
- Enable non-blocking insertion to database (needs https://github.com/strands-project/mongodb_store/pull/184, release requested https://github.com/strands-project/mongodb_store/issues/187 )
- Update launch files (for PR2 / Fetch)

### CODE REVIEW

**Comment by k-okada** [comment]
> release requested strands-project/mongodb_store#187 

it's already released. so this should pass the test?

**Comment by furushchev** [comment]
@k-okada Yes.

**Comment by wkentaro** [comment]
Maybe this one also blocks release of 1.0.10.

**Comment by furushchev** [comment]
So please skip

**Comment by furushchev** [comment]
```bash
[drc_task_common] Scanning dependencies of target manipulation_data_server
[drc_task_common] [100%] Building CXX object CMakeFiles/manipulation_data_server.dir/src/drc_task_common/manipulation_data_server.cpp.o
[drc_task_common] /home/travis/ros/ws_jsk_robot/src/jsk-ros-pkg/jsk_demos/jsk_2015_06_hrp_drc/drc_task_common/src/drc_task_common/manipulation_data_server.cpp:40:50: fatal error: jsk_recognition_msgs/ICPAlignWithBox.h: No such file or directory
[drc_task_common] compilation terminated.
[drc_task_common] make[2]: *** [CMakeFiles/manipulation_data_server.dir/src/drc_task_common/manipulation_data_server.cpp.o] Error 1
[drc_task_common] make[1]: *** [CMakeFiles/manipulation_data_server.dir/all] Error 2
[drc_task_common] make: *** [all] Error 2
[drc_task_common] <== '/home/travis/ros/ws_jsk_robot/build/drc_task_common/build_env.sh /usr/bin/make --jobserver-fds=3,4 -j' failed with return code '2'
```

Build failed with another error..

**Comment by furushchev** [comment]
Test passed.

**Comment by furushchev** [comment]
@k-okada Please review and merge if there is no problem. :+1:

**Comment by furushchev** [comment]
@k-okada Thx!!

**Pull request merged**
