### PR TITLE
[WIP] [jsk_robot_startup] add common launch file for app manager / add samples

### PR DESCRIPTION
**Pull request by furushchev**
fetch_apps
pr2_apps

### CODE REVIEW

**Comment by k-okada** [comment]
```
Full test results for 'jsk_fetch_startup/test_results/jsk_fetch_startup/roslaunch-check_launch_fetch_gazebo_bringup.launch.xml'
-------------------------------------------------
<?xml version="1.0" encoding="UTF-8"?>
<testsuite tests="1" failures="1" time="1" errors="0" name="roslaunch-check_launch_fetch_gazebo_bringup.launch.xml">
  <testcase name="test_ran" status="run" time="1" classname="Results">
  <failure message="roslaunch check [/home/travis/ros/ws_jsk_robot/src/jsk_robot/jsk_fetch_robot/jsk_fetch_startup/launch/fetch_gazebo_bringup.launch] failed" type=""/>
  </testcase>
  <system-out><![CDATA[[
[/home/travis/ros/ws_jsk_robot/src/jsk_robot/jsk_fetch_robot/jsk_fetch_startup/launch/fetch_gazebo_bringup.launch]:
	Unknown substitution command [param robot/name]. Valid commands are ['find', 'env', 'optenv', 'anon', 'arg']
]]></system-out>
</testsuite>
```

**Comment by furushchev** [comment]
@k-okada Updated pics to NICE one. Also fixed the error. Please review again!

**Comment by furushchev** [comment]
@708yamaguchi I heard from @k-okada that you took a REALLY NICE picture for our fetch robot. Could you please share with me? (via Email is better since I will have to crop into icon size)

**Comment by 708yamaguchi** [comment]
@furushchev 
I sent you email with EXTREMELY NICE picture of our fetch. :smile:

**Pull request merged**
