### PR TITLE
[fetcheus] add fetch-navigation.test

### PR DESCRIPTION
**Pull request by knorth55**
add fetcheus test for navigation functions

### CODE REVIEW

**Comment by 708yamaguchi** [comment]
I think these test have no problem. These tests are useful and pass in my melodic environment.

By the way, how about defining `(shortest-angle)` function?
https://github.com/jsk-ros-pkg/jsk_robot/pull/1212/files#diff-559e9fc3cd2919da0cff6d7464a087f2R14-R15

This function is used in fetcheus, too.
https://github.com/jsk-ros-pkg/jsk_robot/blob/master/jsk_fetch_robot/fetcheus/fetch-interface.l#L249-L251

**Comment by 708yamaguchi** [comment]
Sorry, I found PR https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/428 (added shortest angle)

**Comment by knorth55** [comment]
yes, `shortest-angle` will be added in `pr2eus`.

**Comment by knorth55** [comment]
kinetic test failure

```
gzserver: /build/ogre-1.9-mqY1wq/ogre-1.9-1.9.0+dfsg1/OgreMain/src/OgreRenderSystem.cpp:546: virtual void Ogre::RenderSystem::setDepthBufferFor(Ogre::RenderTarget*): Assertion `bAttached && "A new DepthBuffer for a RenderTarget was created, but after creation" "it says it's incompatible with that RT"' failed.

Aborted (core dumped)
```

**Comment by knorth55** [comment]
indigo test failure
https://travis-ci.org/github/jsk-ros-pkg/jsk_robot/jobs/670984249

```
start testing [test-move-to]

[ERROR] [1586026746.234094972, 39.054000000]: too far from goal position 216.314 mm (> 200mm)

[ERROR] [1586026746.234457233, 39.054000000]: :move-to try to send /move_base_simple/goal

[ERROR] test (< (abs (- (elt (send pos0 :pos) 0) (* 1000 x))) 100) failed ... (move-to moves incorrectly in x axis: 300.0 != 402.479 ^[0mmstart testing [test-move-to]

ty-wait]

ait]

ld/fetcheus/test_results/fetcheus/rosunit-fetch_navigation_test.xml

).

[ERROR] test (< (abs (- (elt (send pos0 :pos) 1) (* 1000 y))) 100) failed ... (move-to moves incorrectly in y axis: 300.0 != 404.395 ^[0m

.479 ^[0mmstart testing [test-move-to]

ty-wait]

ait]

ld/fetcheus/test_results/fetcheus/rosunit-fetch_navigation_test.xml
```

**Comment by knorth55** [comment]
@k-okada could you review and merge this PR?

**Comment by knorth55** [comment]
i fixed and travis passed.
@k-okada could you review and merge this PR?

**Pull request merged**
