### PR TITLE
[fetch] add monitor fixture to guard side of monitor

### PR DESCRIPTION
**Pull request by 708yamaguchi**
I add monitor fixture to guard side of the monitor.

fixture

fixture_side

### CODE REVIEW

**Comment by knorth55** [comment]
Good.
For further improvement, it is better to think about ordering this part to some company, not making by 3D printer.

**Comment by 708yamaguchi** [comment]
Thank you.

I will watch Fetch with these new parts for a few days.
If there is no problem, I want to outsource these parts after adding some improvements.

**Comment by 708yamaguchi** [comment]
I added the imprint "fetch" to the left side of the part and spray-painted the fetch letters blue.

monitor_fixture_cad
monitor_fixture1
monitor_fixture2

CC @mmwise

**Comment by 708yamaguchi** [comment]
I think this is OK to be merged.

**Pull request merged**
