### PR TITLE
[jsk_denso_robot] Support COBOTTA OSS type

### PR DESCRIPTION
**Pull request by pazeshun**
Currently, `jsk_cobotta_startup` and `cobottaeus` assume that our COBOTTA is not OSS type.
This PR adds support of COBOTTA OSS type.

## TODOs
- [x] Implement `(send *cobotta* :angle-vector (send *ri* :state :potentio-vector))` and `(send *ri* :angle-vector (send *cobotta* :angle-vector) 1000)`
- [x] Add `cobotta_bringup.launch` for COBOTTA OSS type
- [x] Implement gripper interface to `*ri*`
- [x] Add error recovery
- [x] Update README

### CODE REVIEW

**Comment by pazeshun** [comment]
@k-okada 
Could you tell me why https://github.com/jsk-ros-pkg/jsk_robot/blob/eac815173b8f0e0df3a1f230dd9b68ec937fddfe/jsk_denso_robot/README.md?plain=1#L18-L19 is required?
My first assumption is that you don't want to place whole `denso_cobotta_ros` to your workspace only for `cobotta_descriptions`.
However, `denso.rosinstall` includes `denso_cobotta_ros`, so my assumption seems wrong:
https://github.com/jsk-ros-pkg/jsk_robot/blob/eac815173b8f0e0df3a1f230dd9b68ec937fddfe/jsk_denso_robot/denso.rosinstall#L5-L7

**Comment by pazeshun** [comment]
@k-okada 
> Could you tell me why
> 
> https://github.com/jsk-ros-pkg/jsk_robot/blob/eac815173b8f0e0df3a1f230dd9b68ec937fddfe/jsk_denso_robot/README.md?plain=1#L18-L19

Sorry, maybe I understand.
https://github.com/jsk-ros-pkg/jsk_robot/blob/eac815173b8f0e0df3a1f230dd9b68ec937fddfe/jsk_denso_robot/jsk_cobotta_startup/launch/cobotta_bringup.launch#L4-L9 calls https://github.com/DENSORobot/denso_robot_ros/blob/3.2.0/denso_robot_control/launch/denso_robot_control.launch#L34, which assumes `cobotta.urdf` is placed under `denso_robot_descriptions/cobotta_description/`.

**Comment by k-okada** [comment]
@pazeshun if you're ok with whit PR, please remove [WIP] ? or Draft label? from this PR. 

Screenshot from 2022-07-14 17-19-17

**Comment by pazeshun** [comment]
@k-okada 
I think noetic test becomes failed due to this PR currently.
This is because Segmentation Fault occurs in euslisp model generation of cobottaeus.
Previously, this generation is skipped because denso_cobotta_descriptions is not included in .travis.rosinstall.*.
I have to debug this before this PR becomes ready for review.
So please wait.

**Comment by k-okada** [comment]
@pazeshun can we remove Draft?

**Comment by pazeshun** [comment]
@k-okada No, noetic test failure seems not fixed.
And fixing this has lower priority than some parts of #1544 for me.
So please wait (about 1 week?).

**Comment by pazeshun** [comment]
I made this PR ready for review because CI passed thanks to @k-okada , but I'm not confident because we ignore https://github.com/jsk-ros-pkg/jsk_robot/blob/69f1bd504eec3bab0a61c3885c70648216f70e92/.travis.rosinstall.noetic#L20

**Review by k-okada — APPROVED** [review]
LGTM
```
I made this PR ready for review because CI passed thanks to @k-okada , but I'm not confident because current state of this PR ignores

 # compile euscollada for installed collada_urdf
```
I think this is ok, because the problems is  wrong path in `/opt/ros/noetic/share/collada_urdf/cmake/collada_urdfConfig.cmake` , so it does not need to recompile euscollada.
(see https://github.com/ros/collada_urdf/issues/43#issuecomment-883441579 )

**Comment by pazeshun** [comment]
> I think this is ok, because the problems is wrong path in `/opt/ros/noetic/share/collada_urdf/cmake/collada_urdfConfig.cmake` , so it does not need to recompile euscollada.
> (see [ros/collada_urdf#43 (comment)](https://github.com/ros/collada_urdf/issues/43#issuecomment-883441579) )

Oh, I see.
Thank you very much!

**Pull request merged**
