### PR TITLE
[baxtereus] add collision links for baxter-robot-safe

### PR DESCRIPTION
**Pull request by knorth55**
baxter_collision_check
```lisp
1.irteusgl$ (setq *baxter* (instance baxter-robot-safe :init))
#<baxter-robot-safe #X67ec9a0 baxter  0.0 0.0 0.0 / 0.0 0.0 0.0>
2.irteusgl$ (objects (list *baxter*))
;; (make-irtviewer) executed
(#<baxter-robot-safe #X67ec9a0 baxter  0.0 0.0 0.0 / 0.0 0.0 0.0>)
3.irteusgl$ (send-all (send *baxter* :collision-avoidance-links) :draw-on :flush t)
(nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil)
4.irteusgl$ (send *baxter* :self-collision-check)
nil
```

### CODE REVIEW

**Comment by knorth55** [comment]
Previous collision check
baxter_collision_check_prev

**Comment by knorth55** [comment]
`upper_elbow` and `uppper_forearm` collides in `:tuck-pose`

```lisp
1.irteusgl$ (send *baxter* :tuck-pose)
#f(0.0 -57.0 -119.0 152.0 146.0 0.0 0.0 0.0 57.0 -119.0 -152.0 136.0 0.0 0.0 0.0)
2.irteusgl$ (send *baxter* :self-collision-check)
((#<bodyset-link #X62d5fd8 left_upper_forearm  -84.056 351.423 589.26 / -0.613 0.135 -2.91> . #<bodyset-link #X64a3970 left_upper_elbow  83.149 254.963 489.187 / 2.386 0.442 -0.255>) (#<bodyset-link #X633f3d0 right_upper_forearm  -98.675 -361.265 593.192 / 0.571 0.304 2.901> . #<bodyset-link #X6485cd0 right_upper_elbow  83.149 -254.963 489.187 / -2.386 0.442 0.255>))
3.irteusgl$ pprint (mapcar #'(lambda (x) (list (send (car x) :name) (send (cdr x) :name))) (send *baxter* :self-collision-check)))
(("left_upper_forearm" "left_upper_elbow")
 ("right_upper_forearm" "right_upper_elbow"))
nil
```

**Comment by knorth55** [comment]
Updated to add `:collision-ignore-pairs` and ignore the collision

```lisp
1.irteusgl$ (setq *baxter* (instance baxter-robot-safe :init))
#<baxter-robot-safe #X62779a0 baxter  0.0 0.0 0.0 / 0.0 0.0 0.0>
2.irteusgl$ (send *baxter* :tuck-pose)
#f(0.0 -57.0 -119.0 152.0 146.0 0.0 0.0 0.0 57.0 -119.0 -152.0 136.0 0.0 0.0 0.0)
3.irteusgl$ (send *baxter* :self-collision-check)
nil
4.irteusgl$ (send *baxter* :collision-ignore-pairs)
((#<bodyset-link #X52cf8f0 left_upper_elbow  83.149 254.963 489.187 / 2.386 0.442 -0.255> . #<bodyset-link #X50d0fd8 left_upper_forearm  -84.056 351.423 589.26 / -0.613 0.135 -2.91>) (#<bodyset-link #X62ef0c0 right_upper_elbow  83.149 -254.963 489.187 / -2.386 0.442 0.255> . #<bodyset-link #X513af58 right_upper_forearm  -98.675 -361.265 593.192 / 0.571 0.304 2.901>))
5.irteusgl$ pprint (mapcar #'(lambda (x) (list (send (car x) :name) (send (cdr x) :name))) (send *baxter* :collision-ignore-pairs))
(("left_upper_elbow" "left_upper_forearm")
 ("right_upper_elbow" "right_upper_forearm"))
nil
```

**Comment by k-okada** [comment]
@knorth55 please add test code as new PR, including 
- check :self-collision-check returns nil when tuck pose
- check :self-collision-check returns t for some poses

BTW whey you need to include `upper_elbow` to the collision check? The original committer did not  describe anything, but it seems he want to avoid self-collision of `upper_elbow`https://github.com/jsk-ros-pkg/jsk_robot/pull/315 

If you include 'upper_elbow` and others, it is just to check all `links`, so you do not have to list up all links, please consider https://github.com/knorth55/jsk_robot/pull/2

**Comment by knorth55** [comment]
"Previous collision links" do not include wrist and shoulder links.
In this PR, I include all the links in two arms and add ignore-pairs to pass the test.

**Comment by knorth55** [comment]
test is already added in https://github.com/jsk-ros-pkg/jsk_robot/blob/master/jsk_baxter_robot/baxtereus/test/test-baxter.l#L7-L18

**Comment by knorth55** [comment]
I add new collision test.

```
$ (mapcar #'(lambda (x) (pprint (cons (send (car x) :name) (send (cdr x) :name)))) (send *baxter* :self-collision-check))
("left_upper_forearm" . "right_lower_forearm")
("left_lower_forearm" . "right_upper_forearm")
("left_lower_forearm" . "right_lower_forearm")
(nil nil nil)
```
baxter_collision_new

**Comment by knorth55** [comment]
please merge this

**Pull request merged**
