### PR TITLE
Update jsk_travis to 0.5.17 and fix travis

### PR DESCRIPTION
**Pull request by knorth55**
- use `jsk_travis` `0.5.17`
- remove released packages from `.travis.rosinstall.$ROS_DISTRO`
- add `fetch_ros` in `.travis.rosinstall.$ROS_DISTRO` (https://github.com/fetchrobotics/fetch_ros/pull/144, https://github.com/fetchrobotics/fetch_ros/pull/146)

### CODE REVIEW

**Comment by pazeshun** [comment]
`jsk_travis` lost backward compatibility since `0.5.15`.
At least, we have to use `.travis/travis.sh` instead of `source .travis/travis.sh` on `.travis.yml` like https://github.com/jsk-ros-pkg/jsk_travis/blob/0.5.17/.travis.yml#L102.
Please see https://github.com/jsk-ros-pkg/jsk_travis/pull/410#issue-491755997, https://github.com/jsk-ros-pkg/jsk_travis/pull/410#issuecomment-697348191, https://github.com/jsk-ros-pkg/jsk_travis/pull/410#issuecomment-698058111.
I'm not sure whether @k-okada prefers not updating `jsk_travis` on repositories other than `jsk_recognition` or he prefers fixing these repositories to use the latest `jsk_travis` at their convinience.

**Comment by k-okada** [comment]
> I'm not sure whether @k-okada prefers not updating jsk_travis on repositories other than jsk_recognition or he prefers fixing these repositories to use the latest jsk_travis at their convinience.

https://github.com/jsk-ros-pkg/jsk_travis/pull/410 simply cleanup travis result. I updatde jsk_recognition because at that time, I am working with that repository and having better travis output helps debugging.

But unless you have any strong reason, you do not have to update .travis.yml settings just for this. This is the advanteage of using submodules, instead of cloning ci module everytime (https://github.com/ros-planning/moveit_ros/blob/kinetic-devel/.travis.yml#L21).

updating jsk_travis in this PR seems nice to me.

スクリーンショット 2020-11-27 123913
スクリーンショット 2020-11-27 125936

**Comment by knorth55** [comment]
I preferred latter one because the out log is simpler and shorter.

**Comment by knorth55** [comment]
Travis passed! Current master branch test fails because we require the latest `jsk_maps`.

**Comment by knorth55** [comment]
- use `jsk_travis` `0.5.17`
- remove released packages from `.travis.rosinstall.$ROS_DISTRO`
- add `fetch_ros` in `.travis.rosinstall.$ROS_DISTRO` (https://github.com/fetchrobotics/fetch_ros/pull/146)

Travis passed.
https://travis-ci.org/github/jsk-ros-pkg/jsk_robot/builds/746261820

**Pull request merged**
