### PR TITLE
[jsk_robot_startup/util/mux_selector] Add wait option for topic

### PR DESCRIPTION
**Pull request by iory**
I added a wait option to wait for the topic of other nodes that are up at the same time.
- [x] Add `wait` option
- [x] Add docs

### CODE REVIEW

**Comment by k-okada** [comment]
please add documents to https://github.com/jsk-ros-pkg/jsk_robot/tree/master/doc/jsk_robot_common/jsk_robot_startup

**Comment by iory** [comment]
Thanks for the comment.
I added the document for the `mux_selector.py`. Please check it.

**Comment by knorth55** [comment]
@k-okada please merge this PR. this is useful.

**Comment by knorth55** [comment]
I close this PR because #1234 is merged

**Pull request closed without merging**
