### PR TITLE
[fetcheus] Fix :go-velocity to reject non-zero y correctly

### LINKED ISSUE #1154: [fetcheus] go-velocity does not work
```
(send *ri* :go-velocity 0.1 0 0.5)
[ERROR] [1571647540.324682228]: Setting velocity in y-axis is not valid for non-holonomic robot
nil
```

cc @Affonso-Gui  @YutoUchimi

### PR DESCRIPTION
**Pull request by pazeshun**
Includes #1155 
Fixes #1154

### CODE REVIEW

**Comment by pazeshun** [comment]
Travis test correctly failed in #1155, and correctly succeeded in this PR.
@knorth55 Could you review this?

**Comment by pazeshun** [comment]
> This PR is not checked on real robot and causes serious error in https://github.com/jsk-ros-pkg/jsk_pr2eus/blob/master/pr2eus/robot-interface.l#L1433 !!!
> Now fetch is always failed to move.

What is the error?

**Comment by knorth55** [comment]
`:go-velocity` returns `nil` everytime, so `:move-to` always fail.
so robot fails going to the kitchen.

**Comment by knorth55** [comment]
I'm fixing now.

**Comment by pazeshun** [comment]
> `:go-velocity` returns `nil` everytime, so `:move-to` always fail.
> so robot fails going to the kitchen.

I see.
So `:move-to-wait` should be updated for non-holonomic robots, or `:go-velocity` should accept non-zero `y` and just ignore it.
Sorry for your trouble.

**Comment by knorth55** [comment]
yes.
I'm wondering which is better.

**Comment by pazeshun** [comment]
How about printing warn message when non-zero y is passed?

**Comment by pazeshun** [comment]
This solution may not good if you want to make strict navigation because assuming non-zero y is wrong...

**Comment by knorth55** [comment]
I opened PR to fix the error https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/405

**Pull request merged**
