### PR TITLE
Add build map docs

### PR DESCRIPTION
**Pull request by 708yamaguchi**
Update README about building a map with Fetch robot.
Duplicate of https://github.com/knorth55/jsk_robot/pull/139

### CODE REVIEW

**Review by k-okada — CHANGES_REQUESTED** [review]
this PR includes fetch.launch, but could not find code to include '($find jsk_fetch_startup)/launch/fetch.launch'

**Comment by knorth55** [comment]
`fetch.launch` is added for melodic update and not merged yet to `jsk-ros-pkg/jsk_robot:master`.
https://github.com/jsk-ros-pkg/jsk_robot/pull/1316
https://github.com/jsk-ros-pkg/jsk_robot/pull/1328

**Review by k-okada — CHANGES_REQUESTED** [review]
Sorry, @708yamaguchi please resolve conflicts

**Comment by 708yamaguchi** [comment]
I think the conflict is resolved.

The diff is the following:
- Add README about creating map with fetch
- remove `imu_corrector` and `odom_corrector` in fetch_bringup.launch, which exists in fetch.launch too.
  - https://github.com/jsk-ros-pkg/jsk_robot/blob/master/jsk_fetch_robot/jsk_fetch_startup/launch/fetch.launch#L104-L115
  - https://github.com/jsk-ros-pkg/jsk_robot/blob/master/jsk_fetch_robot/jsk_fetch_startup/launch/fetch_bringup.launch#L213-L224
- move `slam_karto` out of `<group if="$(arg launch_move_base)">` because we do not use `slam_karto` with `move_base`

**Comment by k-okada** [comment]
@708yamaguchi please resolve conflicts and remove "PleaseResovleConflicts" label

**Comment by 708yamaguchi** [comment]
I rebased `origin/master` and I remove `PleaseResolveConflicts` label.

**Pull request merged**
