### PR TITLE
PR2 recalibrate with voice

### PR DESCRIPTION
**Pull request by iory**
Add recalibrate node with voice.
If pr2's joints stacked, pr2 will say stacked joint name.

### CODE REVIEW

**Comment by knorth55** [comment]
it looks good, but do we need to copy all calibrate script from pr2_bringup?

**Comment by iory** [comment]
I see.
original `calibrate_pr2.py` is just a script, not a library.
https://github.com/PR2/pr2_robot/tree/kinetic-devel/pr2_bringup/scripts
I think that we have three choices. 
Firstly, make it a library and send PR to pr2_bringup.
Secondly, append a path to `pr2_bringup` and import it (`sys.path.append`).
Thirdly, copy all calibrate script from pr2_bringup.

Which is the best choice?

**Comment by k-okada** [comment]
you can start rosrun pr2_bringup calibration_pr2.py from python code, (and
more easily from bash script) to start recalibration code.
If you want to clean/pretty python code to execute rosrun, roslaunch
program may help
--
◉ Kei Okada



2020年2月6日(木) 20:36 iory <notifications@github.com>:

**Comment by iory** [comment]
@k-okada 
Thanks for your reply.
However, this PR provides an additional function to warn by voice when a stack occurs while calibrating pr2. To implement it, I modified `CalibrateParallel` class in calibrate_pr2.py.
I don't think rosrun(roslaunch) is relevant to this discussion, and could you say that a little bit more easily for me?

**Comment by k-okada** [comment]
Oh, I thought you write code that calls functions defined in
calibrate_pr2.py and catch errors. Sorry that your update on
calibrate_pr2.py is not clear for me. You'd better keep the original
version and put your update on different commit.
If you simply add voice feature,
https://github.com/jsk-ros-pkg/jsk_robot/blob/68a565b59aa7ec8af8d7a7150d607a4122c176a6/jsk_pr2_robot/jsk_pr2_startup/scripts/calibrate_pr2.py#L267-L276

you'd better listen
https://github.com/PR2/pr2_robot/blob/kinetic-devel/pr2_bringup/scripts/calibrate_pr2.py#L210
and
let them speak.

1. do not rewrite code unless that is super important
2. ROS follows the UNIX philosophy, connection small programs to build
large systems
https://books.google.co.jp/books?id=Hnz5CgAAQBAJ&pg=PA4&lpg=PA4&dq=ros+unix+philosophy&source=bl&ots=-5xbHZUCM8&sig=ACfU3U15Z0EBffCvn0hd7fHeMKSLEAOgDQ&hl=en&sa=X&ved=2ahUKEwjz5YX29b7nAhU9wosBHRPlBWgQ6AEwCXoECAgQAQ#v=onepage&q=ros%20unix%20philosophy&f=false

3. Claim what is your contribution exactly, what is important not only for
writing code, but also for writing paper and proposal.s

- we may build a generalized version of
https://github.com/jsk-ros-pkg/jsk_robot/blob/master/jsk_fetch_robot/jsk_fetch_startup/scripts/warning.py
in
future.

stick-> stuck?
--
◉ Kei Okada



2020年2月7日(金) 15:13 iory <notifications@github.com>:

**Comment by iory** [comment]
OK. I'll create another PR.

**Pull request closed without merging**
