### PR TITLE
[jsk_naoqi_robot] add naoqi_speech_recognition

### PR DESCRIPTION
**Pull request by ayfujii**
In order to use speech_recognition with nao microphone, this PR changes naoqi_msgs/AudioBuffer to audio_common_msgs/AudioData and uses ros_speech_recognition.

cc. @708yamaguchi

### CODE REVIEW

**Comment by 708yamaguchi** [comment]
@ayfujii 

If you would like to launch naoqi_speech_recognition automatically, you can include this launch file at https://github.com/jsk-ros-pkg/jsk_robot/blob/master/jsk_naoqi_robot/jsk_nao_startup/launch/jsk_nao_startup.launch

This is my preference, but I don't think it's essential.

**Comment by kochigami** [comment]
@ayfujii 

Thank you very much for your useful PR.
(I'm very sorry to forget to respond your e-mail for a long time...)

If I'm misunderstanding, I'm sorry, but I think what we need is `publish_audiodata.py` (converting  naoqi audio topic from `naoqi_bridge_msgs/AudioBuffer` to `audio_common_msgs/AudioData`), and other files (`naoqi_speech_recognition.launch` and `naoqi_speech_recognition` package related files) are not necessary.
How about including `publish_audiodata.py` and `ros_speech_recognition` launch in `jsk_nao_startup.launch`?

**Comment by ayfujii** [comment]
@kochigami
@708yamaguchi

Thank you for your comments.
I thought this PR is not needed for every nao and pepper user, so I separated the directory.
If it is OK, I will close this PR and include this in jsk_nao_startup.launch in other PR.

**Comment by kochigami** [comment]
If you include your files using group name like this,
https://github.com/jsk-ros-pkg/jsk_robot/blob/master/jsk_naoqi_robot/jsk_nao_startup/launch/jsk_nao_startup.launch#L7
https://github.com/jsk-ros-pkg/jsk_robot/blob/master/jsk_naoqi_robot/jsk_nao_startup/launch/jsk_nao_startup.launch#L47
users can select whether they use speech recognition feature or not when they launch `jsk_nao/pepper_startup.launch`.

Anyway, thank you very much for adding a useful feature!

**Pull request closed without merging**
