### PR TITLE
[fetcheus] support :start-offset-time in fetcheus angle-vector and angle-vector-sequence

### PR DESCRIPTION
**Pull request by knorth55**
Fetch version of #1068 
Fetch support both `:start-time` and `start-offset-time` API as `baxtereus` in #1068.

- change not to ignore `:start-offset-time` 
- test `start-time` and `start-offset-time`

### CODE REVIEW

**Comment by knorth55** [comment]
I tested with real robot, and it works.

**Comment by knorth55** [comment]
Gazebo simulation is something weird... :thinking: 
When the robot wait for motion start, motors of the robot probably got servo off.

- :100: : `(send *ri* :angle-vector (send *fetch* :angle-vector) 2000 nil 0)`
fetch-moveit-start-time-0
- :thinking: :`(send *ri* :angle-vector (send *fetch* :angle-vector) 2000 nil 4)`
fetch-moveit-start-time-4

**Comment by pazeshun** [comment]
Question: Will servo off cause travis test failure?
Suggestion: Could you confirm new test fails in current code in another PR?

**Comment by knorth55** [comment]
> Question: Will servo off cause travis test failure?
Suggestion: Could you confirm new test fails in current code in another PR?

No, and I will fix this problem.

**Comment by pazeshun** [comment]
> Suggestion: Could you confirm new test fails in current code in another PR?

I made #1071

**Comment by knorth55** [comment]
I made PR to fix this fetch servo off problem.
https://github.com/fetchrobotics/robot_controllers/pull/40

**Pull request merged**
