### PR TITLE
add ik-prepared-poses in baxter class

### PR DESCRIPTION
**Pull request by k-okada**
c.f. https://github.com/start-jsk/jsk_apc/pull/1990

### CODE REVIEW

**Comment by pazeshun** [comment]
How can we set the return value of `:ik-prepared-poses` to nil with this?

**Comment by k-okada** [comment]
Sorry, I fixed coded as same interface as you used in jsk_apc, pleas check is you have time

**Comment by pazeshun** [comment]
Really updated?

**Comment by k-okada** [comment]
Yes

2017年1月10日(火) 17:40 Shun Hasegawa <notifications@github.com>:

**Comment by pazeshun** [comment]
> How can we set the return value of :ik-prepared-poses to nil with this?

So the answer of this question is `(setf (get self :ik-prepared-poses) nil)`?

**Comment by k-okada** [comment]
i see,
```
--- a/jsk_baxter_robot/baxtereus/baxter-util.l
+++ b/jsk_baxter_robot/baxtereus/baxter-util.l
@@ -2,9 +2,9 @@
 
 (defmethod baxter-robot
   (:ik-prepared-poses
-   (&optional poses)
+   (&optional (poses :null))
    (let ((ik-prepared-poses (or (get self :ik-prepared-poses) '(:untuck-pose))))
-     (if (null poses)
+     (if (eq poses :null)
          (return-from :ik-prepared-poses ik-prepared-poses)
        (setf (get self :ik-prepared-poses) poses))
      poses))
```

**Comment by pazeshun** [comment]
I understood, +1

**Pull request merged**
