### PR TITLE
[jsk_pr2_startup/jsk_pr2_move_base] revert nice value of move_base_node to default

### PR DESCRIPTION
**Pull request by furushchev**
- revert nice value of move_base_node to default
- remove duplicated param
- small local costmap size

### CODE REVIEW

**Comment by k-okada** [comment]
How can we fix this @garaemon @wkentaro 
```
Using /usr/local/lib/python2.7/dist-packages/pip-7.1.2-py2.7.egg
Processing dependencies for pip
Finished processing dependencies for pip
+++sudo pip install -U pip setuptools
The directory '/home/travis/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/travis/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
/usr/local/lib/python2.7/dist-packages/pip-7.1.2-py2.7.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Requirement already up-to-date: pip in /usr/local/lib/python2.7/dist-packages/pip-7.1.2-py2.7.egg
Collecting setuptools
  Downloading setuptools-19.1.1-py2.py3-none-any.whl (463kB)
    100% |████████████████████████████████| 466kB 1.1MB/s 
Installing collected packages: setuptools
  Found existing installation: setuptools 18.8.1
    Uninstalling setuptools-18.8.1:
      Successfully uninstalled setuptools-18.8.1
Successfully installed setuptools
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 9, in <module>
    load_entry_point('pip==7.1.2', 'console_scripts', 'pip')()
  File "/usr/local/lib/python2.7/dist-packages/pip-7.1.2-py2.7.egg/pip/__init__.py", line 217, in main
    return command.main(cmd_args)
  File "/usr/local/lib/python2.7/dist-packages/pip-7.1.2-py2.7.egg/pip/basecommand.py", line 248, in main
    pip_version_check(session)
  File "/usr/local/lib/python2.7/dist-packages/pip-7.1.2-py2.7.egg/pip/utils/outdated.py", line 102, in pip_version_check
    installed_version = get_installed_version("pip")
  File "/usr/local/lib/python2.7/dist-packages/pip-7.1.2-py2.7.egg/pip/utils/__init__.py", line 858, in get_installed_version
```

**Comment by furushchev** [comment]
@garaemon @wkentaro cc. @k-okada 
also need update to the latest to fix this problem?

**Comment by wkentaro** [comment]
probably, u need to upgrade jsk_travis.

**Comment by k-okada** [comment]
why we have to update jsk_travis? what was the problem?

**Comment by wkentaro** [comment]
I thought https://github.com/jsk-ros-pkg/jsk_robot/pull/523#issuecomment-164699366, no?

**Comment by k-okada** [comment]
My question is why jsk_travis breaks for all repositories and how can we avoid this type of situation, except debugging jsk_travis and force everyone to use latest one. 

https://github.com/jsk-ros-pkg/jsk_travis/pull/155 sounds like we use newer version of pip because of rosdep.
1) why latest pip did not working, we should no trust pypy ?
2) why rosdep in hydro did not work with python-pip provided by 12.04 ? if so we'd send information to upstream

**Comment by k-okada** [comment]
update jsk_travis itself is ok, for now.

--
◉ Kei Okada

**Comment by wkentaro** [comment]
I reported before about that problem with rosdep==0.11.3, and william said 0.11.4 fixed the problem.
https://github.com/jsk-ros-pkg/jsk_robot/pull/529#issuecomment-166309244

> why latest pip did not working

I don't know why, but fails with hydro on travis, maybe after changes of travis itself.
https://github.com/jsk-ros-pkg/jsk_robot/pull/523#issuecomment-164707422

> why rosdep in hydro did not work with python-pip provided by 12.04 ? if so we'd send information to upstream

Maybe it works at this time (the rosdep version is 0.11.4 for now), you can stop upgrading pip.

**Comment by furushchev** [comment]
rebased origin/master

**Comment by furushchev** [comment]
passed test.

**Pull request merged**
