### PR TITLE
Revert "[jsk_robot] unified database" and use param "robot/name"

### PR DESCRIPTION
**Pull request by furushchev**
Reverts jsk-ros-pkg/jsk_robot#387

### CODE REVIEW

**Comment by furushchev** [comment]
**NOTE** Please do not merge till I commit fixed version

**Comment by furushchev** [comment]
In https://github.com/jsk-ros-pkg/jsk_robot/blob/master/jsk_robot_common/jsk_robot_startup/lifelog/mongodb.launch#L16 ,
I use `robot_name` for passing argument, I think in this point we cannot use param.
What should I do?, hmm.

**Comment by furushchev** [comment]
OK, solved.

**Comment by k-okada** [comment]
> OK, solved.
how?

**Comment by k-okada** [comment]
```
[peppereus] -- catkin 0.6.14                                                    

[peppereus] CMake Error at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:75 (find_package): 

[peppereus]   Could not find a package configuration file provided by "naoqi_sensors" 

[peppereus]   with any of the following names:                                  

[peppereus]                                                                     

[peppereus]     naoqi_sensorsConfig.cmake                                       

[peppereus]     naoqi_sensors-config.cmake                                      

[peppereus]                                                    
```
ros-naoqi repo is changing.... be careful @kochigami 

https://github.com/jsk-ros-pkg/jsk_robot/pull/400

**Comment by k-okada** [comment]
please rebase origin/master

**Comment by furushchev** [comment]
I think it's ok to merge.

>> OK, solved.
> how?

I implemented periodic replicator node with reading params according with jsk仕様 (robot/name, robot/database)

**Comment by k-okada** [comment]
https://github.com/jsk-ros-pkg/jsk_robot/pull/397/files#diff-61957c8b5d1393e2b9bd2f8f6d82360dR29

--
◉ Kei Okada

**Comment by furushchev** [comment]
travis failed because of error in peppereus

```
[peppereus] CMake Error at CMakeLists.txt:35 (add_rostest):                     

[peppereus]   Unknown CMake command "add_rostest".                              

[peppereus]                                                                     

[peppereus]                                                                     

[peppereus] -- Configuring incomplete, errors occurred!                         

[peppereus] See also "/workspace/ros/ws_jsk_robot/build/peppereus/CMakeFiles/CMakeOutput.log". 

[peppereus] See also "/workspace/ros/ws_jsk_robot/build/peppereus/CMakeFiles/CMakeError.log". 

[peppereus] <== '/workspace/ros/ws_jsk_robot/build/peppereus/build_env.sh /usr/bin/cmake /workspace/ros/ws_jsk_robot/src/jsk_robot/jsk_pepper_robot/peppereus -DCATKIN_DEVEL_PREFIX=/workspace/ros/ws_jsk_robot/devel -DCMAKE_INSTALL_PREFIX=/workspace/ros/ws_jsk_robot/install' failed with return code '1' 

Failed   <== peppereus                  [ 1.8 seconds ] 
```

**Comment by furushchev** [comment]
this change is need to run on PR1040. if no problem, please restart travis, then merge after passed :)

**Comment by k-okada** [comment]
it failed again

--
◉ Kei Okada

**Comment by k-okada** [comment]
are really using latest origin/master? not latest .travis

**Comment by k-okada** [comment]
As I commented somewhere is it not a good idea to update .travis unless you do understand what's happening there

**Comment by furushchev** [comment]
It failed again because of the same error...
hmm, I use latest travis, and merged latest origin/master.
Maybe missing dep to `rostest` in peppereus? https://github.com/jsk-ros-pkg/jsk_robot/blob/master/jsk_pepper_robot/peppereus/CMakeLists.txt#L4
I wanted to test if travis pass or not by adding `rostest` on my fork branch,
https://travis-ci.org/furushchev/jsk_robot/builds/73989571
 but it also fails because of another problem on indigo... 

```
/opt/ros/indigo/share/euslisp/jskeus/eus/Linux64/bin/irteusgl roseus-error: no such package NAOQI_MSGS in (apply #'ros::load-org-for-ros ros::fullname args), exitting...
```

I could not found naoqi_msgs. Was it changed?

**Comment by k-okada** [comment]
see if #406 passed

at https://github.com/jsk-ros-pkg/jsk_robot/commit/293acf40ad2c73c98fe61d5ed82be40f513e45c1, I added to install pepper-mesh, this should use 0.0.7 of jsk_travis https://github.com/jsk-ros-pkg/jsk_robot/commit/c74c136f3eaaa0c2caba219344c12c55b20eae46


at https://github.com/jsk-ros-pkg/jsk_robot/pull/400, I have wrongly removed rostest from find_package, but this does not install pepper-mesh due to someone roll  jsk_travis back to 0.0.5

at https://github.com/jsk-ros-pkg/jsk_robot/pull/391 do not run rostest if mesh is not found


so I removed rostest from find_pakcage (that's wrong), someone roll back to jsk_travks (so mesh is not installed) and #391 check the existence of pepper mesh and skip test (so the test passed if you did not use latest travis)


I really want to check if newer commid did not wrongly changed .travis directory,...

**Comment by furushchev** [comment]
At last I found alternative package of `naoqi_msgs`
https://github.com/ros-naoqi/naoqi_bridge_msgs
So should I create PR to port `naoqi_msgs -> naoqi_bridge_msgs`?

**Comment by furushchev** [comment]
Also note that `naoqi_bridge_msgs` is not yet released.
I'm trying to test travis with port `naoqi_msgs` to `naoqi_bridge_msgs` and append it to `.rosinstall`
https://github.com/furushchev/jsk_robot/commit/e8bfb3d156ce56d377e918a3f2981b6bc6c375e9
https://github.com/furushchev/jsk_robot/commit/f1e31a408e9cb1d97c7668241470de9115955c1b
https://travis-ci.org/furushchev/jsk_robot

**Comment by k-okada** [comment]
yes, also we should disable compiling on hydro for naoqi related packages,
because they are only updated on indigo and later
http://www.ros.org/debbuild/indigo.html?q=naoqi

--
◉ Kei Okada

**Comment by k-okada** [comment]
deb=true hydro  since naoqi_bridge_msgs is not release and maybe not plan to release them
deb=true indigo naoqi_bridge_msgs is released
deb=false hydro you can use latest naoqi_bridge from source
deb=false indigo you can use latest naoqi_bridge from source

so I we should disable hydro for naoqi related jsk packages.

**Comment by furushchev** [comment]
how should I disable?
- remove from `env`
- add to `matrix: allow_failures:`

**Comment by k-okada** [comment]
how about writing something link
````
if($ENV{ROS_DISTRO} STREQUAL "hydro")
  return()
endif()
```

**Comment by furushchev** [comment]
Is it also effective when test?

**Comment by k-okada** [comment]
it works for devel test, but not working on install test so add TEST_PKGS or NO_TEST_INSTALL

https://github.com/jsk-ros-pkg/jsk_travis/blob/master/travis.sh

**Comment by k-okada** [comment]
or use BEFORE_INSTALL to hydro deb=true and force install latest naoqi from source

**Comment by k-okada** [comment]
or https://github.com/start-jsk/rtmros_tutorials/blob/master/.travis.yml#L23

but problem is how to keep old peppereus for buildfirm...

**Comment by k-okada** [comment]
ok, fixed in https://travis-ci.org/jsk-ros-pkg/jsk_robot/builds/74167074

depends on naoqi_driver, and that will be depends on naoqi_msgs on hydro deb and depends on naoqi_bridge_msgs on others, see https://github.com/k-okada/jsk_robot/commit/acdbc622f3deefa776921ac698f0fb35eb3d1245 to use euslisp program on both situatoin

adding naoqi_bridge_msgs .rosinstall may pass the hydro source test,


I do not think we need to add naoqi_bridge_msgs to pepper.rosinstall

**Comment by furushchev** [comment]
@k-okada Thank you very much! I'll rebase after merging https://github.com/jsk-ros-pkg/jsk_robot/pull/406

**Pull request merged**
