### PR TITLE
jsk_fetch_startup: support auto dock / undock

### PR DESCRIPTION
**Pull request by furushchev**
- Launch nodes for auto docking / undocking on `fetch_bringup.launch`
- Avoid disabling base breaker on auto undocking

### CODE REVIEW

**Comment by k-okada** [comment]
Please add changes that you made on real robot with `sudo emacs`, disabled rotation after  undock?

**Comment by furushchev** [comment]
@k-okada Sorry totally forgot. Is it enough to add to `README`?

```diff
# /opt/ros/indigo/lib/fetch_auto_dock/undock_on_button.py
44c44,47
<         goal.rotate_in_place = True
---
>         # fixed by furushchev (2017/11/1)
>         # Disabled rotate in place feature
>         # goal.rotate_in_place = True
>         goal.rotate_in_place = False
```

**Comment by k-okada** [comment]
yes please send PR ;-)

--
◉ Kei Okada


2017-11-02 10:53 GMT+09:00 Furushchev <notifications@github.com>:

**Comment by furushchev** [comment]
@k-okada Added to https://github.com/jsk-ros-pkg/jsk_robot/pull/862

**Pull request merged**
