### PR TITLE
fix too long file name in deb build

### PR DESCRIPTION
**Pull request by k-okada**
c.f. : https://github.com/jsk-ros-pkg/jsk_robot/pull/591 

this cause failing on deb builder -> http://build.ros.org/view/Ibin_uT64/job/Ibin_uT64__jsk_pr2_startup__ubuntu_trusty_amd64__binary/90/console

### CODE REVIEW

**Comment by k-okada** [comment]
To reproduce what's happens in build.ros.org
```
hub clone tork-a/jsk_robot-release
cd jsk_robot-release
git checkout debian/indigo/trusty/jsk_pr2_startup 
wget https://raw.githubusercontent.com/furushchev/jsk_robot/036348323990c6961e3358f189e3cde50e6b867d/jsk_pr2_robot/jsk_pr2_startup/CMakeLists.txt -O CMakeLists.txt
dpkg-buildpackage -rfakeroot -uc -b
```

**Comment by furushchev** [comment]
@k-okada Oh, it was actually my fault.. Thank you very much for fix this!

**Comment by furushchev** [comment]
Can we check this kind of error before merging to master branch...?

**Comment by k-okada** [comment]
https://github.com/jsk-ros-pkg/jsk_robot/pull/618#issuecomment-222039767 shows how to check rob build

**Pull request merged**
