### PR TITLE
[baxtereus] add baxter-softhand-interface for baxter+softhand

### PR DESCRIPTION
**Pull request by knorth55**
I add `baxter-softhand-interface` for `baxter` + `softhand` and `softhand v2`.
this program is originally from `knorth55/eus_vive`.
we can use `baxter` + `softhand` just by loading `baxter-softhand-interface.l`

https://github.com/knorth55/eus_vive/blob/master/euslisp/lib/baxter-interface.l

TODO: We need to update https://github.com/jsk-ros-pkg/jsk_control/pull/731, to use `baxter-softhand-interface.l`.

### CODE REVIEW

**Comment by pazeshun** [comment]
1. Is this really tested in real robot?
   Please put some sample code which is confirmed to work on real robot.
2. What is your plan to use thls in eus_vive? Do you just modify knorth55/eus_vive or move eus_vive to other place  and modify it?

**Comment by knorth55** [comment]
Yes I confirmed it works with robot, but just `start-grasp` and `stop-grasp`.
But I will check other stuff tomorrow.

`eus_vive` should be separated into several packages, and `eus_vive` can only be teleoperation scripts.
I'm openning a PR to merge `eus_vive` to `jsk_control`.
https://github.com/jsk-ros-pkg/jsk_control/pull/731

**Comment by pazeshun** [comment]
> Yes I confirmed it works with robot, but just `start-grasp` and `stop-grasp`.
> But I will check other stuff tomorrow.

OK, could you check the functions for `softhand`?
I assume testing `softhand-v2` immediately may be hard.

> `eus_vive` should be separated into several packages, and `eus_vive` can only be teleoperation scripts.
> I'm openning a PR to merge `eus_vive` to `jsk_control`.
> [jsk-ros-pkg/jsk_control#731](https://github.com/jsk-ros-pkg/jsk_control/pull/731)

Oh, sorry, I forgot this PR.
Could you add a comment about TODOs to this PR so that we do not forget to use `baxter-softhand-interface.l` of `jsk_robot` in future `eus_vive`?

**Comment by knorth55** [comment]
I update this PR and test that all methods except heater work!

**Review by pazeshun — APPROVED** [review]

**Pull request merged**
