### PR TITLE
travis.yaml: set ROS_PARALLEL_TEST_JOBS to 1

### PR DESCRIPTION
**Pull request by k-okada**
running two gazebo instance on test???

### CODE REVIEW

**Comment by furushchev** [comment]
@k-okada I tried the same thing and it seems that is not the only reason...
https://github.com/jsk-ros-pkg/jsk_robot/pull/834
https://travis-ci.org/jsk-ros-pkg/jsk_robot/jobs/283088941

**Comment by k-okada** [comment]
but my PullRequest passed without restart.....

**Comment by furushchev** [comment]
@k-okada Can I restart this test? I saw sometimes it passes and sometimes not.

**Comment by k-okada** [comment]
yes, but I'm suspect if you restart, it fails. and if I restart, it passes. :-)

**Comment by furushchev** [comment]
@k-okada Now, you might be correct ;-)

**Comment by k-okada** [comment]
@furushchev ok, i have added new commit and passed, can you restart that, to check if that REALLY works ;-)

**Comment by furushchev** [comment]
@k-okada Okay, this is the only thing only I can do! If it now passes, it means virtual display breaks moveit (or moveit with gazebo)?

**Comment by furushchev** [comment]
@k-okada I restarted and now it passed again!

**Comment by furushchev** [comment]
@k-okada Thanks a lot for debugging! :+

**Pull request merged**
