### PR TITLE
(wip) [naoqi] allow group namespace to naoqi/pepper/nao-interface.l

### PR DESCRIPTION
**Pull request by kochigami**
Purpose: When we want to use two same robots (Pepper, NAO), we separate topic names with group namespace. This pull-requst allows using a group-namespace at eus interface.

TODO list:
- [x] considerate speech, cmd_vel, move_base_simple/goal
They are subscribers. I want to add group-namespace to these as an option so that topics from robotA and robotB can be separated.
For example, if I send `send *ri* :speak "hello"`for one robot, two Pepper speaks now.
If I send `send *ri* :speak "hello"`for the other robot, none of them speaks now.
However,  if I send `send *ri* :servo-off` for one robot, the Pepper takes rest pose. (expected behavior)
That is because we can send `servo-off` topic to only one Pepper with group-namespace. 

- [x] considerate dcm-controller (I forgot the relationship between dcm and others now)
- [x] test with nao (only tried with Pepper)

### CODE REVIEW

**Comment by kochigami** [comment]
> For example, if I send send *ri* :speak "hello"for one robot, two Pepper speaks now.
If I send send *ri* :speak "hello"for the other robot, none of them speaks now.
However, if I send send *ri* :servo-off for one robot, the Pepper takes rest pose. (expected behavior)
That is because we can send servo-off topic to only one Pepper with group-namespace.

I couldn't follow what I meant in this sentence even though I wrote this...
Why did let one robot servo-off succeed?: 
servo-off is a service.
Maybe, only the topic names of subscriber at `naoqi_driver` is hard-coded.
In order to change these names, I had to modify `naoqi_driver`, but there is no explanation about this.

Anyway, I have to explain 
- why I need this
- what kind of change is required in `naoqi_driver` (subscriber side)
- how to change group name in `naoqi-interface` (publisher side)
- add a sample

At the same time, I have to check whether this has a bad effect on normal use (using only one robot).

**Comment by k-okada** [comment]
If you can start two robot under different namespace, then you can start your roseus program under the name space 
```
ROS_NAMESPACE roseus your-great-demo.l
```

c.f. 
http://wiki.ros.org/ROS/EnvironmentVariables#ROS_NAMESPACE

**Comment by kochigami** [comment]
>    why I need this

I want to launch two naoqi robots in one PC. 
For example, two robots conversation demo which I tackled in a few years ago. (At that time, I used two PCs, but using two PCs is heavy and expensive when considering going to outside lab.)

>   what kind of change is required in naoqi_driver (subscriber side)
- Problem
>> Maybe, only the topic names of subscriber at naoqi_driver is hard-coded.

When I use group-name to `pepper_full.launch` in `pepper_bringup` like [this](https://gist.github.com/kochigami/f0968f476a00967d3eaf5078d6dcac59),
`speech`, `cmd_vel`, `/move_base_simple/goal` (they are defined as subscribers in `naoqi_driver.launch`)  are not covered with the group-name.

If there are two robots (robot1, robot2), it means that:
`rostopic pub /robot1/speech ...` => no one speaks
`rostopic pub /speech ...` => two robots speak

```
rostopic list
/cmd_vel
/diagnostics
/joint_angles
/joint_states
/move_base_simple/goal
/robot1/pepper_robot/audio
/robot1/pepper_robot/bumper
/robot1/pepper_robot/camera/bottom/camera_info
/robot1/pepper_robot/camera/bottom/image_raw
/robot1/pepper_robot/camera/bottom/image_raw/compressed
/robot1/pepper_robot/camera/bottom/image_raw/compressed/parameter_descriptions
/robot1/pepper_robot/camera/bottom/image_raw/compressed/parameter_updates
/robot1/pepper_robot/camera/bottom/image_raw/theora
/robot1/pepper_robot/camera/bottom/image_raw/theora/parameter_descriptions
/robot1/pepper_robot/camera/bottom/image_raw/theora/parameter_updates
/robot1/pepper_robot/camera/bottom/image_rect_color
/robot1/pepper_robot/camera/bottom/image_rect_color/compressed
/robot1/pepper_robot/camera/bottom/image_rect_color/compressed/parameter_descriptions
/robot1/pepper_robot/camera/bottom/image_rect_color/compressed/parameter_updates
/robot1/pepper_robot/camera/bottom/image_rect_color/compressedDepth
/robot1/pepper_robot/camera/bottom/image_rect_color/compressedDepth/parameter_descriptions
/robot1/pepper_robot/camera/bottom/image_rect_color/compressedDepth/parameter_updates
/robot1/pepper_robot/camera/bottom/image_rect_color/theora
/robot1/pepper_robot/camera/bottom/image_rect_color/theora/parameter_descriptions
/robot1/pepper_robot/camera/bottom/image_rect_color/theora/parameter_updates
/robot1/pepper_robot/camera/bottom_rectify_color/parameter_descriptions
/robot1/pepper_robot/camera/bottom_rectify_color/parameter_updates
/robot1/pepper_robot/camera/depth/camera_info
/robot1/pepper_robot/camera/depth/image
/robot1/pepper_robot/camera/depth/image/compressed
/robot1/pepper_robot/camera/depth/image/compressed/parameter_descriptions
/robot1/pepper_robot/camera/depth/image/compressed/parameter_updates
/robot1/pepper_robot/camera/depth/image/compressedDepth
/robot1/pepper_robot/camera/depth/image/compressedDepth/parameter_descriptions
/robot1/pepper_robot/camera/depth/image/compressedDepth/parameter_updates
/robot1/pepper_robot/camera/depth/image/theora
/robot1/pepper_robot/camera/depth/image/theora/parameter_descriptions
/robot1/pepper_robot/camera/depth/image/theora/parameter_updates
/robot1/pepper_robot/camera/depth/image_raw
/robot1/pepper_robot/camera/depth/image_raw/compressed
/robot1/pepper_robot/camera/depth/image_raw/compressed/parameter_descriptions
/robot1/pepper_robot/camera/depth/image_raw/compressed/parameter_updates
/robot1/pepper_robot/camera/depth/image_raw/compressedDepth
/robot1/pepper_robot/camera/depth/image_raw/compressedDepth/parameter_descriptions
/robot1/pepper_robot/camera/depth/image_raw/compressedDepth/parameter_updates
/robot1/pepper_robot/camera/depth/image_raw/theora
/robot1/pepper_robot/camera/depth/image_raw/theora/parameter_descriptions
/robot1/pepper_robot/camera/depth/image_raw/theora/parameter_updates
/robot1/pepper_robot/camera/depth/image_rect
/robot1/pepper_robot/camera/depth/image_rect/compressed
/robot1/pepper_robot/camera/depth/image_rect/compressed/parameter_descriptions
/robot1/pepper_robot/camera/depth/image_rect/compressed/parameter_updates
/robot1/pepper_robot/camera/depth/image_rect/compressedDepth
/robot1/pepper_robot/camera/depth/image_rect/compressedDepth/parameter_descriptions
/robot1/pepper_robot/camera/depth/image_rect/compressedDepth/parameter_updates
/robot1/pepper_robot/camera/depth/image_rect/theora
/robot1/pepper_robot/camera/depth/image_rect/theora/parameter_descriptions
/robot1/pepper_robot/camera/depth/image_rect/theora/parameter_updates
/robot1/pepper_robot/camera/depth/image_rect_raw
/robot1/pepper_robot/camera/depth/image_rect_raw/compressed
/robot1/pepper_robot/camera/depth/image_rect_raw/compressed/parameter_descriptions
/robot1/pepper_robot/camera/depth/image_rect_raw/compressed/parameter_updates
/robot1/pepper_robot/camera/depth/image_rect_raw/compressedDepth
/robot1/pepper_robot/camera/depth/image_rect_raw/compressedDepth/parameter_descriptions
/robot1/pepper_robot/camera/depth/image_rect_raw/compressedDepth/parameter_updates
/robot1/pepper_robot/camera/depth/image_rect_raw/theora
/robot1/pepper_robot/camera/depth/image_rect_raw/theora/parameter_descriptions
/robot1/pepper_robot/camera/depth/image_rect_raw/theora/parameter_updates
/robot1/pepper_robot/camera/depth_rectify_depth/parameter_descriptions
/robot1/pepper_robot/camera/depth_rectify_depth/parameter_updates
/robot1/pepper_robot/camera/depth_registered/hw_registered/image_rect
/robot1/pepper_robot/camera/depth_registered/hw_registered/image_rect/compressed
/robot1/pepper_robot/camera/depth_registered/hw_registered/image_rect/compressed/parameter_descriptions
/robot1/pepper_robot/camera/depth_registered/hw_registered/image_rect/compressed/parameter_updates
/robot1/pepper_robot/camera/depth_registered/hw_registered/image_rect/compressedDepth
/robot1/pepper_robot/camera/depth_registered/hw_registered/image_rect/compressedDepth/parameter_descriptions
/robot1/pepper_robot/camera/depth_registered/hw_registered/image_rect/compressedDepth/parameter_updates
/robot1/pepper_robot/camera/depth_registered/hw_registered/image_rect/theora
/robot1/pepper_robot/camera/depth_registered/hw_registered/image_rect/theora/parameter_descriptions
/robot1/pepper_robot/camera/depth_registered/hw_registered/image_rect/theora/parameter_updates
/robot1/pepper_robot/camera/depth_registered/hw_registered/image_rect_raw
/robot1/pepper_robot/camera/depth_registered/hw_registered/image_rect_raw/compressed
/robot1/pepper_robot/camera/depth_registered/hw_registered/image_rect_raw/compressed/parameter_descriptions
/robot1/pepper_robot/camera/depth_registered/hw_registered/image_rect_raw/compressed/parameter_updates
/robot1/pepper_robot/camera/depth_registered/hw_registered/image_rect_raw/compressedDepth
/robot1/pepper_robot/camera/depth_registered/hw_registered/image_rect_raw/compressedDepth/parameter_descriptions
/robot1/pepper_robot/camera/depth_registered/hw_registered/image_rect_raw/compressedDepth/parameter_updates
/robot1/pepper_robot/camera/depth_registered/hw_registered/image_rect_raw/theora
/robot1/pepper_robot/camera/depth_registered/hw_registered/image_rect_raw/theora/parameter_descriptions
/robot1/pepper_robot/camera/depth_registered/hw_registered/image_rect_raw/theora/parameter_updates
/robot1/pepper_robot/camera/depth_registered/image
/robot1/pepper_robot/camera/depth_registered/image/compressed
/robot1/pepper_robot/camera/depth_registered/image/compressed/parameter_descriptions
/robot1/pepper_robot/camera/depth_registered/image/compressed/parameter_updates
/robot1/pepper_robot/camera/depth_registered/image/compressedDepth
/robot1/pepper_robot/camera/depth_registered/image/compressedDepth/parameter_descriptions
/robot1/pepper_robot/camera/depth_registered/image/compressedDepth/parameter_updates
/robot1/pepper_robot/camera/depth_registered/image/theora
/robot1/pepper_robot/camera/depth_registered/image/theora/parameter_descriptions
/robot1/pepper_robot/camera/depth_registered/image/theora/parameter_updates
/robot1/pepper_robot/camera/depth_registered/points
/robot1/pepper_robot/camera/depth_registered/sw_registered/camera_info
/robot1/pepper_robot/camera/depth_registered/sw_registered/image_rect
/robot1/pepper_robot/camera/depth_registered/sw_registered/image_rect/compressed
/robot1/pepper_robot/camera/depth_registered/sw_registered/image_rect/compressed/parameter_descriptions
/robot1/pepper_robot/camera/depth_registered/sw_registered/image_rect/compressed/parameter_updates
/robot1/pepper_robot/camera/depth_registered/sw_registered/image_rect/compressedDepth
/robot1/pepper_robot/camera/depth_registered/sw_registered/image_rect/compressedDepth/parameter_descriptions
/robot1/pepper_robot/camera/depth_registered/sw_registered/image_rect/compressedDepth/parameter_updates
/robot1/pepper_robot/camera/depth_registered/sw_registered/image_rect/theora
/robot1/pepper_robot/camera/depth_registered/sw_registered/image_rect/theora/parameter_descriptions
/robot1/pepper_robot/camera/depth_registered/sw_registered/image_rect/theora/parameter_updates
/robot1/pepper_robot/camera/depth_registered/sw_registered/image_rect_raw
/robot1/pepper_robot/camera/depth_registered/sw_registered/image_rect_raw/compressed
/robot1/pepper_robot/camera/depth_registered/sw_registered/image_rect_raw/compressed/parameter_descriptions
/robot1/pepper_robot/camera/depth_registered/sw_registered/image_rect_raw/compressed/parameter_updates
/robot1/pepper_robot/camera/depth_registered/sw_registered/image_rect_raw/compressedDepth
/robot1/pepper_robot/camera/depth_registered/sw_registered/image_rect_raw/compressedDepth/parameter_descriptions
/robot1/pepper_robot/camera/depth_registered/sw_registered/image_rect_raw/compressedDepth/parameter_updates
/robot1/pepper_robot/camera/depth_registered/sw_registered/image_rect_raw/theora
/robot1/pepper_robot/camera/depth_registered/sw_registered/image_rect_raw/theora/parameter_descriptions
/robot1/pepper_robot/camera/depth_registered/sw_registered/image_rect_raw/theora/parameter_updates
/robot1/pepper_robot/camera/depth_registered_rectify_depth/parameter_descriptions
/robot1/pepper_robot/camera/depth_registered_rectify_depth/parameter_updates
/robot1/pepper_robot/camera/front/camera_info
/robot1/pepper_robot/camera/front/image_raw
/robot1/pepper_robot/camera/front/image_raw/compressed
/robot1/pepper_robot/camera/front/image_raw/compressed/parameter_descriptions
/robot1/pepper_robot/camera/front/image_raw/compressed/parameter_updates
/robot1/pepper_robot/camera/front/image_raw/theora
/robot1/pepper_robot/camera/front/image_raw/theora/parameter_descriptions
/robot1/pepper_robot/camera/front/image_raw/theora/parameter_updates
/robot1/pepper_robot/camera/front/image_rect_color
/robot1/pepper_robot/camera/front/image_rect_color/compressed
/robot1/pepper_robot/camera/front/image_rect_color/compressed/parameter_descriptions
/robot1/pepper_robot/camera/front/image_rect_color/compressed/parameter_updates
/robot1/pepper_robot/camera/front/image_rect_color/compressedDepth
/robot1/pepper_robot/camera/front/image_rect_color/compressedDepth/parameter_descriptions
/robot1/pepper_robot/camera/front/image_rect_color/compressedDepth/parameter_updates
/robot1/pepper_robot/camera/front/image_rect_color/theora
/robot1/pepper_robot/camera/front/image_rect_color/theora/parameter_descriptions
/robot1/pepper_robot/camera/front/image_rect_color/theora/parameter_updates
/robot1/pepper_robot/camera/front_rectify_color/parameter_descriptions
/robot1/pepper_robot/camera/front_rectify_color/parameter_updates
/robot1/pepper_robot/camera/ir/camera_info
/robot1/pepper_robot/camera/ir/image_raw
/robot1/pepper_robot/camera/ir/image_raw/compressed
/robot1/pepper_robot/camera/ir/image_raw/compressed/parameter_descriptions
/robot1/pepper_robot/camera/ir/image_raw/compressed/parameter_updates
/robot1/pepper_robot/camera/ir/image_raw/theora
/robot1/pepper_robot/camera/ir/image_raw/theora/parameter_descriptions
/robot1/pepper_robot/camera/ir/image_raw/theora/parameter_updates
/robot1/pepper_robot/camera/ir/image_rect_ir
/robot1/pepper_robot/camera/ir/image_rect_ir/compressed
/robot1/pepper_robot/camera/ir/image_rect_ir/compressed/parameter_descriptions
/robot1/pepper_robot/camera/ir/image_rect_ir/compressed/parameter_updates
/robot1/pepper_robot/camera/ir/image_rect_ir/compressedDepth
/robot1/pepper_robot/camera/ir/image_rect_ir/compressedDepth/parameter_descriptions
/robot1/pepper_robot/camera/ir/image_rect_ir/compressedDepth/parameter_updates
/robot1/pepper_robot/camera/ir/image_rect_ir/theora
/robot1/pepper_robot/camera/ir/image_rect_ir/theora/parameter_descriptions
/robot1/pepper_robot/camera/ir/image_rect_ir/theora/parameter_updates
/robot1/pepper_robot/camera/ir_rectify_ir/parameter_descriptions
/robot1/pepper_robot/camera/ir_rectify_ir/parameter_updates
/robot1/pepper_robot/chest_touch
/robot1/pepper_robot/hand_touch
/robot1/pepper_robot/head_touch
/robot1/pepper_robot/imu/base
/robot1/pepper_robot/imu/torso
/robot1/pepper_robot/info
/robot1/pepper_robot/laser
/robot1/pepper_robot/odom
/robot1/pepper_robot/pose/body_pose/cancel
/robot1/pepper_robot/pose/body_pose/feedback
/robot1/pepper_robot/pose/body_pose/goal
/robot1/pepper_robot/pose/body_pose/result
/robot1/pepper_robot/pose/body_pose/status
/robot1/pepper_robot/pose/body_pose_naoqi/cancel
/robot1/pepper_robot/pose/body_pose_naoqi/feedback
/robot1/pepper_robot/pose/body_pose_naoqi/goal
/robot1/pepper_robot/pose/body_pose_naoqi/result
/robot1/pepper_robot/pose/body_pose_naoqi/status
/robot1/pepper_robot/pose/get_life_state
/robot1/pepper_robot/pose/joint_angles
/robot1/pepper_robot/pose/joint_angles_action/cancel
/robot1/pepper_robot/pose/joint_angles_action/feedback
/robot1/pepper_robot/pose/joint_angles_action/goal
/robot1/pepper_robot/pose/joint_angles_action/result
/robot1/pepper_robot/pose/joint_angles_action/status
/robot1/pepper_robot/pose/joint_stiffness
/robot1/pepper_robot/pose/joint_stiffness_trajectory/cancel
/robot1/pepper_robot/pose/joint_stiffness_trajectory/feedback
/robot1/pepper_robot/pose/joint_stiffness_trajectory/goal
/robot1/pepper_robot/pose/joint_stiffness_trajectory/result
/robot1/pepper_robot/pose/joint_stiffness_trajectory/status
/robot1/pepper_robot/pose/joint_trajectory/cancel
/robot1/pepper_robot/pose/joint_trajectory/feedback
/robot1/pepper_robot/pose/joint_trajectory/goal
/robot1/pepper_robot/pose/joint_trajectory/result
/robot1/pepper_robot/pose/joint_trajectory/status
/robot1/pepper_robot/sonar/back
/robot1/pepper_robot/sonar/front
/rosout
/rosout_agg
/speech
/tf
/tf_static
```
- What kind of change is required
I had to modify subscriber register in `naoqi_driver.launch` to allow group-name for its topics.
I modified boot_config.json.
[my branch is here](https://github.com/kochigami/naoqi_driver/tree/add-group-name-to-subscribe-topic-name): [allow group-name for subscribing topics](https://github.com/kochigami/naoqi_driver/commit/b752dd8c0559987f77f597d4a0f94894db686000#diff-25d902c24283ab8cfbac54dfa101ad31) + [enable to change the name of boot_config.json](https://github.com/kochigami/naoqi_driver/commit/923310e0520943588cc5bcccaeaea413f1016581#diff-25d902c24283ab8cfbac54dfa101ad31)

At first, I tried adding argument `group_namespace` in `naoqi_driver.launch` like [this](https://gist.github.com/kochigami/7ee2a1ceadd1813fc758b583aa4bd647), but this value is fetched in an independent file `external_registration.cpp`. (Other variables don't move to other files.)
I did not know how to deliver this variable to the other file (naoqi_driver.cpp), whose role is to register subscribers.

>    how to change group name in naoqi-interface (publisher side)

[with group-name]

```
roscore
roseus pepper-interface.l
pepper-init t "robot1"
```
```
rostopic list
/dummy_state
/joint_states
/pepper_dcm/LeftHand_controller/command
/pepper_dcm/RightHand_controller/command
/robot1/cmd_vel
/robot1/move_base_simple/goal
/robot1/pepper_robot/pose/joint_angles
/robot1/pepper_robot/pose/joint_stiffness_trajectory/cancel
/robot1/pepper_robot/pose/joint_stiffness_trajectory/feedback
/robot1/pepper_robot/pose/joint_stiffness_trajectory/goal
/robot1/pepper_robot/pose/joint_stiffness_trajectory/result
/robot1/pepper_robot/pose/joint_stiffness_trajectory/status
/robot1/pepper_robot/pose/joint_trajectory/cancel
/robot1/pepper_robot/pose/joint_trajectory/feedback
/robot1/pepper_robot/pose/joint_trajectory/goal
/robot1/pepper_robot/pose/joint_trajectory/result
/robot1/pepper_robot/pose/joint_trajectory/status
/robot1/speech
/robot_interface_marker_array
/rosout
/rosout_agg
/tf
/tf_static
```

[without group-name]

```
roscore
roseus pepper-interface.l
pepper-init t 
```
```
rostopic list
/dummy_state
/joint_states
/pepper_dcm/LeftHand_controller/command
/pepper_dcm/RightHand_controller/command
/robot1/cmd_vel
/robot1/move_base_simple/goal
/robot1/pepper_robot/pose/joint_angles
/robot1/pepper_robot/pose/joint_stiffness_trajectory/cancel
/robot1/pepper_robot/pose/joint_stiffness_trajectory/feedback
/robot1/pepper_robot/pose/joint_stiffness_trajectory/goal
/robot1/pepper_robot/pose/joint_stiffness_trajectory/result
/robot1/pepper_robot/pose/joint_stiffness_trajectory/status
/robot1/pepper_robot/pose/joint_trajectory/cancel
/robot1/pepper_robot/pose/joint_trajectory/feedback
/robot1/pepper_robot/pose/joint_trajectory/goal
/robot1/pepper_robot/pose/joint_trajectory/result
/robot1/pepper_robot/pose/joint_trajectory/status
/robot1/speech
/robot_interface_marker_array
/rosout
/rosout_agg
/tf
/tf_static
kanae@kanae-ThinkPad-T480s:~/catkin_ws/src/jsk_robot/jsk_naoqi_robot/peppereus$ rostopic list
/cmd_vel
/dummy_state
/joint_states
/move_base_simple/goal
/pepper_dcm/LeftHand_controller/command
/pepper_dcm/RightHand_controller/command
/pepper_robot/pose/joint_angles
/pepper_robot/pose/joint_stiffness_trajectory/cancel
/pepper_robot/pose/joint_stiffness_trajectory/feedback
/pepper_robot/pose/joint_stiffness_trajectory/goal
/pepper_robot/pose/joint_stiffness_trajectory/result
/pepper_robot/pose/joint_stiffness_trajectory/status
/pepper_robot/pose/joint_trajectory/cancel
/pepper_robot/pose/joint_trajectory/feedback
/pepper_robot/pose/joint_trajectory/goal
/pepper_robot/pose/joint_trajectory/result
/pepper_robot/pose/joint_trajectory/status
/robot_interface_marker_array
/rosout
/rosout_agg
/speech
/tf
/tf_static
```

>  add a sample

Two robots speak respectively in one PC.
gist is [here](https://gist.github.com/kochigami/c71c4b441f8f664475e110ccf5a5acfb)

In this sample, robot1: Pepper, robot2: NAO,
- put two json file under `naoqi_driver/share/`
- set NAO_IP1(pepper) and NAO_IP2(nao) in `.bashrc`

**Comment by kochigami** [comment]
> considerate dcm-controller (I forgot the relationship between dcm and others now)

dcm系はgazebo上で関節角を動かすためのもの．
実機とgazeboで立ち上げるlaunchファイルが違うので，お互いがお互いに影響を及ぼしたりしない．

このPRでは，gazeboの方ではgroup-nameが設定されないようになっていて，ロボットは１台しかgazebo上に出せない．
dcmへのgroup-nameの設定は，いつか複数台をgazebo上に出現させたくなった時に考えるので良いと思う．（その前にロボットが転ぶ問題や，`:go-pos`など色々考えないといけないことがある．）

むしろ，実機でgroup-nameを使うための`naoqi_driver`側の変更が，悪さをしていないか調べる必要がある．
その上で，この変更をkochigami-developブランチに含めて，READMEで説明する必要がある．(masterにプルリクエストするのは，しばらく使ってみてからにする．)

**Comment by kochigami** [comment]
`git rebase origin/master` してコンフリクトを直して，
`git rebase --continue`, `git add <file>`, `git push -u kochigami <this branch>`したら，
```
To https://github.com/kochigami/jsk_robot.git
 ! [rejected]        allow-set-group-ns-to-naoqi-interface -> allow-set-group-ns-to-naoqi-interface (non-fast-forward)
error: failed to push some refs to 'https://github.com/kochigami/jsk_robot.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```
となったので，
```
kanae@kanae-ThinkPad-T480s:~/catkin_ws/src/jsk_robot/jsk_naoqi_robot/naoqieus$ git pull
Merge made by the 'recursive' strategy.
```
して，
```
kanae@kanae-ThinkPad-T480s:~/catkin_ws/src/jsk_robot/jsk_naoqi_robot/naoqieus$ git push -u kochigami allow-set-group-ns-to-naoqi-interface 
```
したら，コミットログがぐしゃぐしゃになってしまいました．  
直し方が分からないので，閉じて新しいものを作ろうと思います・・・すみません．
（自分のレポジトリで練習します．）

**Pull request closed without merging**
