### PR TITLE
add self_filter launch and config to jsk_baxter

### PR DESCRIPTION
**Pull request by aginika**
Hand-made parameter tuning for padding.

Is there any way to publish colorized pointcloud?
self_filter_baxter

### CODE REVIEW

**Comment by garaemon** [comment]
There shoud be parameter like use_color or somethin like that.
Please check it

**Comment by garaemon** [comment]
These PRs

* https://github.com/PR2/pr2_navigation/pull/12
* https://github.com/PR2/pr2_navigation/pull/11

**Comment by garaemon** [comment]
Please update it by the next PR

**Comment by aginika** [comment]
Ok, Thanks!

**Comment by garaemon** [comment]
And... Could you check PR2 uses organized filter?

**Comment by aginika** [comment]
I'm afraid that I couldn't understand fully what you mean .

Now PR2 use pr2_navigation_self_filter only for tilt_laser and base_laser in pr2.launch.
However, there is a openni_cloud_self_filter_color.launch in jsk_pr2_startup, so we can use it to publish self_filter with just launching it.( need to modify a little for not using use_rgb and keep_organized)

I will confirm whether it works or not and update to use the use_rgb and keep_organized.

**Comment by garaemon** [comment]
> However, there is a openni_cloud_self_filter_color.launch in jsk_pr2_startup, so we can use it to publish self_filter with just launching it.( need to modify a little for not using use_rgb and keep_organized)

Please add it to default, because the filter does not subscribe input if there is no subscriber of output topic.

**Pull request merged**
