### PR TITLE
[fetcheus] do not set :wait-until-update when :worldcoords

### PR DESCRIPTION
**Pull request by knorth55**
do not set `:wait-until-update` when `(send *ri* :state :worldcoords)`.
it occurs error.

### CODE REVIEW

**Comment by k-okada** [comment]
please add test

**Comment by knorth55** [comment]
I want to add test but waiting for pr2eus move base test.
https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/420

**Comment by knorth55** [comment]
Sorry, it was my misunderstanding. I will add test.

**Comment by knorth55** [comment]
I updated and added the test.

**Comment by knorth55** [comment]
@k-okada I update and add a test. please merge this.

**Comment by tkmtnt7000** [comment]
@k-okada Please merge this PR! we need this PR for fetch semi demo.

**Pull request merged**
