### PR TITLE
[jsk_fetch_startup] Use email address instead of yaml for smach_to_mail

### PR DESCRIPTION
**Pull request by tkmtnt7000**
This change depends on https://github.com/jsk-ros-pkg/jsk_robot/pull/1588 .
We use rosparam instead of yaml file to set email information.

### CODE REVIEW

**Review by knorth55 — CHANGES_REQUESTED** [review]
this is not good because, it only supports fetch1075.
how about generating email_topic yaml in CMakeLists.txt?
like this: 

https://github.com/jsk-ros-pkg/jsk_robot/blob/68ae4be417c94d9d397c123f8d6daa08ade5dcdb/jsk_fetch_robot/jsk_fetch_startup/CMakeLists.txt#L78-L91

https://github.com/jsk-ros-pkg/jsk_robot/blob/68ae4be417c94d9d397c123f8d6daa08ade5dcdb/jsk_fetch_robot/jsk_fetch_startup/CMakeLists.txt#L95-L96

**Comment by tkmtnt7000** [comment]
Thank you very much for reviewing. I mistakenly set email address without thinking fetch1075 and fetch15.
I think it may be good to generate a email config file from CMakeLists.txt.

**Comment by tkmtnt7000** [comment]
Sorry for force-pushing...
Config yaml file is generated when we build workspace.

**Review by knorth55 — APPROVED** [review]

**Comment by k-okada** [comment]
@tkmtnt7000 @knorth55 
Sorry, I did not look the changes of this PR carefully, I originaly intend to use rosparam directly within launch file, instead of using yaml file, 

see  
https://github.com/k-okada/jsk_robot/commit/37b71cea2c79abd31398073709e86d4fb36a7489, may be this is too complex....

**Pull request merged**
