### PR TITLE
[fetcheus] Use attached object for collision object

### PR DESCRIPTION
**Pull request by 708yamaguchi**
I use attached collision object for fetch's default collision objects.

### CODE REVIEW

**Review by k-okada — CHANGES_REQUESTED** [review]
@708yamaguchi can you paste the picture of new attached collision object?

**Comment by 708yamaguchi** [comment]
I checkout to current `708yamaguchi/use-attached-object-` branch, and then add collision objects.

|overview|front|side|under|
|--|--|--|--|
|||||

**Comment by 708yamaguchi** [comment]
Melodic test fails because installation of jsk-pcl-ros failed
```
2021-07-16T15:46:06.3074172Z E: Unable to locate package ros-melodic-jsk-pcl-ros
```
https://pipelines.actions.githubusercontent.com/0HdTXshvf0cYXsudvQge3vQkmBBjhb4DdvH1k2RT0qXsZUv3d0/_apis/pipelines/1/runs/854/signedlogcontent/3?urlExpires=2021-07-16T16%3A12%3A31.3490671Z&urlSigningMethod=HMACV1&urlSignature=0ksZ1JBCjxTvGifOuZ5VJrl5tDxOiIhMplD30OczfnY%3D

It seems that jsk-pcl-ros build failed at build.ros.org
https://build.ros.org/view/Mbin_uB64/job/Mbin_uB64__jsk_pcl_ros__ubuntu_bionic_amd64__binary/180/

The log says
```
22:33:17 c++: internal compiler error: Killed (program cc1plus)
```

It means lack of memory during build?

Thank you for your help @knorth55

**Review by k-okada — APPROVED** [review]
LGTM

**Pull request merged**
