### PR TITLE
[jsk_robot_startup][initial_pose_publisher.l] set map_tf

### PR DESCRIPTION
**Pull request by furushchev**
This pull request adds function to set initial "current floor" information from parameters.
Now we support using `jsk_maps` without serving map. 
Also some minor bugfixes are included.

- add function to set "current floor" on init
- (minor bug fix) use variable for topic names
- (minor bug fix) exit with 1 when failed to change initial pose
- (minor fix) comment in some args for fetch gazebo (change on upstream https://github.com/fetchrobotics/fetch_gazebo/pull/16 was now merged)
- (improvement) use `jsk_maps` for fetch

### CODE REVIEW

**Comment by furushchev** [comment]
waiting for https://github.com/jsk-ros-pkg/jsk_planning/pull/56

**Comment by furushchev** [comment]
waiting for https://github.com/jsk-ros-pkg/jsk_demos/pull/1213

**Comment by furushchev** [comment]
@k-okada please review and merge if there is no problem.

**Comment by k-okada** [comment]
```
Get:1 http://packages.ros.org/ros-shadow-fixed/ubuntu/ trusty/main ros-indigo-fetch-gazebo amd64 0.7.1-0trusty-20170313-124824-0700 [2,565 kB]
Fetched 2,565 kB in 1s (1,770 kB/s)               
(Reading database ... 689451 files and directories currently installed.)
Preparing to unpack .../ros-indigo-fetch-gazebo_0.7.1-0trusty-20170313-124824-0700_amd64.deb ...
Unpacking ros-indigo-fetch-gazebo (0.7.1-0trusty-20170313-124824-0700) over (0.7.1-0trusty-20170228-182610-0800) ...
Setting up ros-indigo-fetch-gazebo (0.7.1-0trusty-20170313-124824-0700) ...
k-okada@p40-yoga:~/catkin_ws/ws_fetch/src/jsk_robot/jsk_fetch_robot/jsk_fetch_startup/launch$ roslaunch fetch_gazebo_bringup.launch 
... logging to /home/k-okada/.ros/log/447933be-138b-11e7-9416-e4a7a00bd84e/roslaunch-p40-yoga-21833.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

unused args [yaw, z] for include of [/opt/ros/indigo/share/fetch_gazebo/launch/include/fetch.launch.xml]
The traceback for the exception was written to the log file
```
Is this working?

**Comment by k-okada** [comment]
am i missing something?
```
transparent: body #<room83b1-scene #X663a9e0 83b1  1010.0 3600.0 0.0 / 0.0
0.0 0.0> param 0.3 face-color :darkviolet
transparent: body #<scene-model #X8ad58c8 83b2  1010.0 10500.0 0.0 / 0.0
0.0 0.0> param 0.3 face-color :dodgerblue
transparent: body #<scene-model #X8d66060 83d1  36349.0 150.0 0.0 / 0.0 0.0
0.0> param 0.3 face-color :dodgerblue
could not found object(room73b2-x-leg-desk)[ERROR] [1490756217.821687904,
4.253000000]: [jsk_maps/publish_spot.l] map-selected is empty! please
publish /map_tf_mux/selected
[ERROR] [1490756217.834663713, 4.274000000]: [jsk_maps/publish_spot.l]
map-selected is empty! please publish /map_tf_mux/selected
[ERROR] [1490756217.844343214, 4.280000000]: [jsk_maps/publish_spot.l]
map-selected is empty! please publish /map_tf_mux/selected
[ERROR] [1490756217.845825389, 4.280000000]: [jsk_maps/publish_spot.l]
map-selected is empty! please publish /map_tf_mux/selected

```
```
$ rosversion jsk_maps
0.0.4
```

--
◉ Kei Okada


2017-03-28 17:23 GMT+09:00 Furushchev <notifications@github.com>:

**Comment by furushchev** [comment]
@k-okada

Hmm, is that on your local environment?
If so I'd like to check gazebo screen shows up.
We also need to wait for a while until selecting current map.

**Comment by k-okada** [comment]
Ok
i have confirmed the map is selected, see https://github.com/jsk-ros-pkg/jsk_demos/pull/1214 to notify the map is selected.
1. we can see pin text but could not see pin body, is it correct? do we add Marker array to rviz.config?
2. we can not see 73b2 model on gazebo/rviz is it correct? even though we see `could not found object(room73b2-x-leg-desk)` error message
screenshot from 2017-03-31 11 02 56
```
diff --git a/jsk_fetch_robot/jsk_fetch_startup/config/jsk_startup.rviz b/jsk_fetch_robot/jsk_fetch_startup/config/jsk_startup.rviz
index 78e2e30..8300614 100644
--- a/jsk_fetch_robot/jsk_fetch_startup/config/jsk_startup.rviz
+++ b/jsk_fetch_robot/jsk_fetch_startup/config/jsk_startup.rviz
@@ -1,11 +1,11 @@
 Panels:
   - Class: rviz/Displays
-    Help Height: 75
+    Help Height: 78
     Name: Displays
     Property Tree Widget:
       Expanded: ~
       Splitter Ratio: 0.625293
-    Tree Height: 403
+    Tree Height: 379
   - Class: rviz/Selection
     Name: Selection
   - Class: rviz/Tool Properties
@@ -24,7 +24,7 @@ Panels:
     Experimental: false
     Name: Time
     SyncMode: 0
-    SyncSource: KinectCamera
+    SyncSource: BaseScan
 Visualization Manager:
   Class: ""
   Displays:
@@ -227,6 +227,7 @@ Visualization Manager:
       Size (m): 0.07
       Style: Spheres
       Topic: /base_scan
+      Unreliable: false
       Use Fixed Frame: true
       Use rainbow: true
       Value: true
@@ -237,6 +238,7 @@ Visualization Manager:
       Enabled: true
       Name: Map
       Topic: /map
+      Unreliable: false
       Value: true
     - Class: rviz/MarkerArray
       Enabled: false
@@ -251,6 +253,9 @@ Visualization Manager:
       Class: rviz/Path
       Color: 255; 0; 127
       Enabled: true
+      Head Diameter: 0.3
+      Head Length: 0.2
+      Length: 0.3
       Line Style: Billboards
       Line Width: 0.05
       Name: NavigationPath
@@ -258,13 +263,21 @@ Visualization Manager:
         X: 0
         Y: 0
         Z: 0
+      Pose Style: None
+      Radius: 0.03
+      Shaft Diameter: 0.1
+      Shaft Length: 0.1
       Topic: /move_base/NavfnROS/plan
+      Unreliable: false
       Value: true
     - Alpha: 1
       Buffer Length: 1
       Class: rviz/Path
       Color: 255; 0; 0
       Enabled: true
+      Head Diameter: 0.3
+      Head Length: 0.2
+      Length: 0.3
       Line Style: Billboards
       Line Width: 0.03
       Name: GlobalPath
@@ -272,13 +285,21 @@ Visualization Manager:
         X: 0
         Y: 0
         Z: 0
+      Pose Style: None
+      Radius: 0.03
+      Shaft Diameter: 0.1
+      Shaft Length: 0.1
       Topic: /move_base/TrajectoryPlannerROS/global_plan
+      Unreliable: false
       Value: true
     - Alpha: 1
       Buffer Length: 1
       Class: rviz/Path
       Color: 25; 255; 0
       Enabled: true
+      Head Diameter: 0.3
+      Head Length: 0.2
+      Length: 0.3
       Line Style: Lines
       Line Width: 0.03
       Name: LocalPath
@@ -286,7 +307,12 @@ Visualization Manager:
         X: 0
         Y: 0
         Z: 0
+      Pose Style: None
+      Radius: 0.03
+      Shaft Diameter: 0.1
+      Shaft Length: 0.1
       Topic: /move_base/TrajectoryPlannerROS/local_plan
+      Unreliable: false
       Value: true
     - Alpha: 1
       Class: rviz/Polygon
@@ -294,6 +320,7 @@ Visualization Manager:
       Enabled: true
       Name: FootPrint
       Topic: /move_base/global_costmap/footprint
+      Unreliable: false
       Value: true
     - Alpha: 0.3
       Class: rviz/Map
@@ -302,6 +329,7 @@ Visualization Manager:
       Enabled: false
       Name: SafeCostMap
       Topic: /safe_teleop_base/local_costmap/costmap
+      Unreliable: false
       Value: false
     - Alpha: 0.35
       Class: rviz/Map
@@ -310,6 +338,7 @@ Visualization Manager:
       Enabled: true
       Name: LocalCostMap
       Topic: /move_base/local_costmap/costmap
+      Unreliable: false
       Value: true
     - Alpha: 0.35
       Class: rviz/Map
@@ -318,6 +347,7 @@ Visualization Manager:
       Enabled: true
       Name: GlobalCostMap
       Topic: /move_base/global_costmap/costmap
+      Unreliable: false
       Value: true
     - Arrow Length: 0.2
       Class: rviz/PoseArray
@@ -325,6 +355,7 @@ Visualization Manager:
       Enabled: false
       Name: PoseArray
       Topic: /particlecloud
+      Unreliable: false
       Value: false
     - Alpha: 1
       Autocompute Intensity Bounds: true
@@ -352,6 +383,7 @@ Visualization Manager:
       Size (m): 0.008
       Style: Flat Squares
       Topic: /kinect_head_c2/depth_registered/half/points
+      Unreliable: false
       Use Fixed Frame: true
       Use rainbow: true
       Value: false
@@ -363,6 +395,7 @@ Visualization Manager:
       Overlay Alpha: 0.7
       Queue Size: 2
       Transport Hint: raw
+      Unreliable: false
       Value: true
       Visibility:
         BaseScan: true
@@ -374,6 +407,7 @@ Visualization Manager:
         LocalCostMap: true
         LocalPath: true
         Map: true
+        MarkerArray: true
         NavigationPath: true
         PoseArray: true
         RobotModel: true
@@ -382,6 +416,14 @@ Visualization Manager:
         TF: true
         Value: true
       Zoom Factor: 1
+    - Class: rviz/MarkerArray
+      Enabled: true
+      Marker Topic: /spots_marker_array
+      Name: MarkerArray
+      Namespaces:
+        {}
+      Queue Size: 100
+      Value: true
   Enabled: true
   Global Options:
     Background Color: 48; 48; 48
@@ -433,7 +475,7 @@ Window Geometry:
   Hide Right Dock: false
   KinectCamera:
     collapsed: false
-  QMainWindow State: 000000ff00000000fd0000000400000000000001ad00000361fc020000000afb0000001200530065006c0065006300740069006f006e00000001e10000009b0000006100fffffffb0000001e0054006f006f006c002000500072006f007000650072007400690065007302000001ed000001df00000185000000a3fb000000120056006900650077007300200054006f006f02000001df000002110000018500000122fb000000200054006f006f006c002000500072006f0070006500720074006900650073003203000002880000011d000002210000017afb000000100044006900730070006c00610079007301000000280000021e000000d600fffffffb00000018004b0069006e00650063007400430061006d006500720061010000024c0000013d0000001600fffffffb0000002000730065006c0065006300740069006f006e00200062007500660066006500720200000138000000aa0000023a00000294fb00000014005700690064006500530074006500720065006f02000000e6000000d2000003ee0000030bfb0000000c004b0069006e0065006300740200000186000001060000030c00000261fb00000018004e006100720072006f007700430061006d0065007200610000000244000001460000000000000000000000010000010f00000361fc0200000003fb0000001e0054006f006f006c002000500072006f00700065007200740069006500730100000041000000780000000000000000fb0000000a00560069006500770073010000002800000361000000ac00fffffffb0000001200530065006c0065006300740069006f006e010000025a000000b200000000000000000000000200000780000000a9fc0100000001fb0000000a00560069006500770073030000004e00000080000002e100000197000000030000065c0000003efc0100000002fb0000000800540069006d006501000000000000065c000002f500fffffffb0000000800540069006d00650100000000000004500000000000000000000003940000036100000004000000040000000800000008fc0000000100000002000000010000000a0054006f006f006c00730100000000ffffffff0000000000000000
+  QMainWindow State: 000000ff00000000fd0000000400000000000001ad00000353fc020000000afb0000001200530065006c0065006300740069006f006e00000001e10000009b0000006900fffffffb0000001e0054006f006f006c002000500072006f007000650072007400690065007302000001ed000001df00000185000000a3fb000000120056006900650077007300200054006f006f02000001df000002110000018500000122fb000000200054006f006f006c002000500072006f0070006500720074006900650073003203000002880000011d000002210000017afb000000100044006900730070006c006100790073010000002800000215000000e800fffffffb00000018004b0069006e00650063007400430061006d0065007200610100000243000001380000001b00fffffffb0000002000730065006c0065006300740069006f006e00200062007500660066006500720200000138000000aa0000023a00000294fb00000014005700690064006500530074006500720065006f02000000e6000000d2000003ee0000030bfb0000000c004b0069006e0065006300740200000186000001060000030c00000261fb00000018004e006100720072006f007700430061006d0065007200610000000244000001460000000000000000000000010000012000000353fc0200000003fb0000001e0054006f006f006c002000500072006f00700065007200740069006500730100000041000000780000000000000000fb0000000a00560069006500770073010000002800000353000000c100fffffffb0000001200530065006c0065006300740069006f006e010000025a000000b200000000000000000000000200000780000000a9fc0100000001fb0000000a00560069006500770073030000004e00000080000002e100000197000000030000065c00000046fc0100000002fb0000000800540069006d006501000000000000065c000003ce00fffffffb0000000800540069006d00650100000000000004500000000000000000000003830000035300000004000000040000000800000008fc0000000100000002000000010000000a0054006f006f006c00730100000000ffffffff0000000000000000
   Selection:
     collapsed: false
   Time:
@@ -443,5 +485,5 @@ Window Geometry:
   Views:
     collapsed: false
   Width: 1628
-  X: 238
-  Y: 47
+  X: 228
+  Y: 37
```

**Comment by furushchev** [comment]
@k-okada 

> 1. we can see pin text but could not see pin body, is it correct? do we add Marker array to rviz.config?

@garaemon updated to use `jsk_rviz_plugins/PictogramArray` for visualizing pin body.

IMO, I suspect that `body+` in euslisp has a possible bug that causes segfault in some cases. (I could not reproduce it though.) and prefer that we can visualize in one topic rather than split pin body / label.
I have a code to use rviz primitive shape for visualizing pin body instead. Should I send pull request?

```lisp
(defun make-pin-marker (coords header
                        &key (name "no_name") (height 1800) (radius 100) (alpha 1.0) color lifetime id)
  (let ((cyl (make-cylinder radius (* radius 0.7) :segments 9 :pos (float-vector 0 0 (/ height 3))))
        (cub (make-cube (/ radius 3) (/ radius 3) (/ height 2.5) :pos (float-vector 0 0 (/ height 6)))))
    (send cyl :rotate -pi/2 :y)
    (send cyl :transform coords :world)
    (send cub :transform coords :world)
    (list
     (cylinder->marker-msg cyl header :color color :ns "pin_head" :lifetime lifetime :id id :alpha alpha)
     (cube->marker-msg cub header :color color :ns "pin_body" :lifetime lifetime :id id :alpha alpha)
     (text->marker-msg name
                       (send coords :translate (float-vector 0 0 (/ height 6)))
                       header :ns "pin_label" :lifetime lifetime :id id))))
```

> 1. we can not see 73b2 model on gazebo/rviz is it correct? even though we see could not found object(room73b2-x-leg-desk) error message
> 

Yes. for visualizing building model as a marker, please consider to use `eusurdf`

```bash
roslaunch eusurdf gazebo_spawn_scene.launch sene:=room73b2 tf_publish:=true
```

and you will have to add `RobotModel` on RViZ like:

robot_model

and set fixed frame to `room73b2/room73b2_root_link`.
If you want to integrate to real fetch, you might need to connect the world coords to this link:

```bash
rosrun tf static_tf_publisher 0 0 0 0 0 0 world room73b2/room73b2_root_link
```

**Comment by furushchev** [comment]
just for reminder:

`could not found object(room73b2-x-leg-desk) `

This is some bug for model conversion script from `euslib`

**Comment by k-okada** [comment]
>
> @garaemon updated to use jsk_rviz_plugins/PictogramArray for visualizing pin body.

what does this mean? are we publish pin as pictogram in this PR or
your proposed make-pin-marker code in
https://github.com/jsk-ros-pkg/jsk_robot/pull/754#issuecomment-290646811
>
> IMO, I suspect that body+ in euslisp has a possible bug that causes segfault in some cases. (I could not reproduce it though.) and prefer that we can visualize in one topic rather than split pin body / label.

> I have a code to use rviz primitive shape for visualizing pin body instead. Should I send pull request?

is this to avoid using body+, and use cylinder mode? if so I prefer to
use body+ version and wait for someone who can reproduce this bug(?).




--
◉ Kei Okada

**Comment by furushchev** [comment]
> what does this mean? are we publish pin as pictogram in this PR or

Change was at https://github.com/jsk-ros-pkg/jsk_demos/commit/24b56764839aba0fea6a7260c55ab957064dc25d

> is this to avoid using body+, and use cylinder mode? if so I prefer to
use body+ version and wait for someone who can reproduce this bug(?).

I see.

**Comment by furushchev** [comment]
now better to wait https://github.com/jsk-ros-pkg/jsk_robot/pull/790

**Comment by furushchev** [comment]
@k-okada Checked with real fetch robot and now it works well.

**Comment by furushchev** [comment]
@k-okada Please merge if there is no problem.

**Pull request merged**
