### PR TITLE
[fetch] Enable to use diagnostic aggregator on fetch

### PR DESCRIPTION
**Pull request by 708yamaguchi**
This Pull Request enables to publish `/diagnostic_agg` topic by default on `fetch` robot.
(This is based on https://github.com/fetchrobotics/fetch_robots/blob/indigo-devel/fetch_bringup/config/analyzers.yaml)

You can view this information by typing the command below:
```
rosrun rqt_robot_monitor rqt_robot_monitor
```

diagnostic_agg

### CODE REVIEW

**Comment by knorth55** [comment]
Travis passed :100:

**Comment by k-okada** [comment]
please add CPU usage as same as PR2, so that we can check too much cpu usage

**Comment by 708yamaguchi** [comment]
@k-okada 
Thank you for your review.
I updated PR to show CPU usage in `rqt_robot_monitor`.

fetch_diagnostics_aggregator

**Comment by k-okada** [comment]
why sensors shows error?
--
◉ Kei Okada



2018年10月28日(日) 14:08 Naoya Yamaguchi <notifications@github.com>:

**Comment by 708yamaguchi** [comment]
From few days ago, I do not launch some `camera nodelet` in `fetch` robot (because of CPU high load problem), so the figure you mentioned says that number of  `camera nodelet` is insufficient.
Now, I temporally changed `yaml` file for `diagnostic aggregator` in `fetch` robot, and `rqt_robot_monitor` does not display error. (I edited figure in [this comment](https://github.com/jsk-ros-pkg/jsk_robot/pull/979#issuecomment-433676962))

**Comment by 708yamaguchi** [comment]
This Pull Request seems to work properly and Travis test passed.
@k-okada 
Could you please merge this?

**Pull request merged**
