### PR TITLE
Expand limit

### PR DESCRIPTION
**Pull request by aginika**

### CODE REVIEW

**Comment by aginika** [comment]
Please merge this one

**Comment by k-okada** [comment]
@aginika why did you expand limit? and did you send PR to URDF model?

**Comment by aginika** [comment]
Hmm.. Sorry, I can't remind...

**Comment by wkentaro** [comment]
Is this PR really opened by @aginika?
The commit is merged from @k-okada 's fork.
screen shot 2016-04-19 at 03 02 33

**Comment by aginika** [comment]
!

**Pull request merged**
