### PR TITLE
[baxtereus] add wait key in :start-grasp

### PR DESCRIPTION
**Pull request by knorth55**
add `:wait` key as `:stop-grasp`

### CODE REVIEW

**Comment by k-okada** [comment]
on pr2, we always call with `:wait t`, and it is not configurable  https://github.com/jsk-ros-pkg/jsk_pr2eus/blob/0.3.10/pr2eus/pr2-interface.l#L244
on fetch, `:wait t` is default behavior, https://github.com/jsk-ros-pkg/jsk_robot/blob/1.0.9/jsk_fetch_robot/fetcheus/fetch-interface.l#L68

**Comment by knorth55** [comment]
default value of `:wait`should be `t`?

**Comment by knorth55** [comment]
Why `stop-grasp` only has `:wait` key word and default value is `nil`?
https://github.com/jsk-ros-pkg/jsk_pr2eus/blob/0.3.10/pr2eus/pr2-interface.l#L301

**Comment by k-okada** [comment]
>Why stop-grasp only has :wait key word and default value is nil?

 not sure, but maybe 
```
(send *ri* :start-grasp)
(send *ri* :anlge-vector #f(...))
```
we have to wait until the robot actually grasp, when move arm to next position, but
```
(send *ri* :stop-grasp)
(send *ri* :anlge-vector #f(...))
```
the robot drop object just ofter :stop-grasp has called, and we can move arm, while the robot is trying to move gripper to initial position. May be because of speed up???

So we need to fix #769 ???

**Comment by knorth55** [comment]
You mean `:stop-grasp` method should have default `:wait` value `t`?
Now I think default `:wait` value should be `t` in all gripper method.

**Pull request merged**
