### PR TITLE
Update jsk_travis to 0.5.6

### PR DESCRIPTION
**Pull request by YutoUchimi**

### CODE REVIEW

**Comment by knorth55** [comment]
do you know the reason why current Travis CI build is failing?

**Comment by pazeshun** [comment]
It seems that current indigo test (`ROS_DISTRO=indigo USE_DEB=false EXTRA_DEB="ros-indigo-convex-decomposition ros-indigo-ivcon"`) takes too much time.

I compared results of that test in this PR and #1173.

|   | [This PR](https://travis-ci.org/jsk-ros-pkg/jsk_robot/jobs/610646326) | [#1173](https://travis-ci.org/jsk-ros-pkg/jsk_robot/jobs/612181303) |
|:-:|:-:|:-:|
| Whole test time | 48 min 37 sec | More than 50 min (Timeout) |
| rosdep_install |  16 min 40 sec | 16 min 51 sec |
| catkin_build | 13 min 44 sec | 14 min 15 sec |
| catkin_run_tests | 10 min 52 sec | ? (Timeout) |

We can do...
- Change cache settings to speed up rosdep install
  - [Current settings](https://github.com/jsk-ros-pkg/jsk_robot/blob/1.1.0/.travis.yml#L2-L6) doesn't seem to have `apt-cacher-ng` setting
  - But this solution works in each test after that test succeeds once
- Increase `CATKIN_PARALLEL_JOBS` or `ROS_PARALLEL_JOBS` to speed up catkin build
  - But this sometimes makes build unstable
- Split test packages like https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/417

**Comment by YutoUchimi** [comment]
The main purpose of this PR is to upload cache correctly.
jsk_travis 0.5.5 and upper exits from docker container successfully, so caches specified in `.travis.yml` will be uploaded to server.
You can check uploaded cache of this repository by: https://travis-ci.org/jsk-ros-pkg/jsk_robot/caches?utm_medium=notification&utm_source=github_status

**Comment by pazeshun** [comment]
In catkin_run_tests...
```
Finished <<< aeroeus                                   [ 0.1 seconds ]
Finished <<< fetcheus                                  [ 1 minute and 42.6 seconds ]
Finished <<< jsk_baxter_web                            [ 0.2 seconds ]
Finished <<< jsk_fetch_diagnosis                       [ 0.1 seconds ]
Finished <<< jsk_pr2_calibration                       [ 0.1 seconds ]
Finished <<< jsk_robot_startup                         [ 0.2 seconds ]
Finished <<< jsk_robot_utils                           [ 18.6 seconds ]
Finished <<< naoqieus                                  [ 8.7 seconds ]
Finished <<< pr2_base_trajectory_action                [ 5.7 seconds ]
Finished <<< roseus_remote                             [ 0.2 seconds ]
Finished <<< jsk_baxter_startup                        [ 0.1 seconds ]
Finished <<< jsk_aero_startup                          [ 1.5 seconds ]
Finished <<< jsk_fetch_startup                         [ 5.2 seconds ]
Finished <<< jsk_pepper_startup                        [ 1.5 seconds ]
Finished <<< jsk_nao_startup                           [ 0.3 seconds ]
Finished <<< naoeus                                    [ 4.6 seconds ]
Finished <<< peppereus                                 [ 0.2 seconds ]
Finished <<< jsk_pr2_startup                           [ 0.2 seconds ]
Finished <<< baxtereus                                 [ 8 minutes and 20.0 seconds ]
```
baxtereus seems too heavy... I'll find what we can reduce.

**Comment by pazeshun** [comment]
Building some packages in jsk_3rdparty is slow:
```
Finished <<< downward                                  [ 5 minutes and 40.7 seconds ]
Finished <<< assimp_devel                              [ 7 minutes and 14.2 seconds ]
```

**Comment by pazeshun** [comment]
@YutoUchimi @knorth55 I created #1177 and #1179 to reduce travis test time.
Both seem effective.

**Pull request merged**
