### PR TITLE
jsk_pr2_desktop: fix typo

### PR DESCRIPTION
**Pull request by furushchev**
Forgot to quote

### CODE REVIEW

**Comment by furushchev** [comment]
Restarted more than 3 times, and still test failed either because it exceeds build time limit or tests on baxter with gazebo failed.

```
Still running (22 of 60): catkin run_tests -i --no-deps --no-status baxtereus fetcheus jsk_baxter_startup jsk_baxter_desktop jsk_baxter_web jsk_fetch_startup jsk_nao_startup jsk_pepper_startup jsk_pr2_calibration jsk_robot_startup jsk_robot_utils naoqieus naoeus peppereus jsk_201504_miraikan pr2_base_trajectory_action jsk_pr2_startup jsk_pr2_desktop roseus_remote -p1 --make-args -j4 --

The job exceeded the maximum time limit for jobs, and has been terminated.
```

How about spliting test case for each robots? (e.g. indigo/baxter, indigo/pr2, indigo/naoqi, ...)
Or any idea? @k-okada @wkentaro

**Comment by k-okada** [comment]
I'm afraid this is because of some test stucks , can we output some of the log data?

**Comment by furushchev** [comment]
@k-okada OK, I temporally enabled to test on jenkins where output log. Let's see...

**Comment by furushchev** [comment]
@k-okada @wkentaro 
Using jenkins, the test did not finish within 50 mins.
The full log is now available: http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis-jsk-ros-pkg-jsk-robot-indigo-deb-true-true-echo-ros-indigo-nao-meshes-ros-nao-meshes-accepted-ros-nao-meshes-boolean-true-sudo-debconf-set-selections-sudo-apt-get-install-y-qq-ros-indigo-nao-meshes/1/consoleText

```
-------------------------------------------------
baxtereus/test_results/baxtereus/rostest-test_baxter-moveit.xml: 1 tests, 1 errors, 0 failures, 0 skipped
baxtereus/test_results/baxtereus/rostest-test_test-baxter.xml: 1 tests, 1 errors, 0 failures, 0 skipped
baxtereus/test_results/baxtereus/rosunit-baxter_lisp.xml: 8 tests, 0 errors, 1 failures, 0 skipped
baxtereus/test_results/baxtereus/rosunit-baxter_moveit_test.xml: 2 tests, 0 errors, 1 failures, 0 skipped
fetcheus/test_results/fetcheus/rostest-test_fetch-moveit.xml: 1 tests
fetcheus/test_results/fetcheus/rostest-test_fetcheus.xml: 1 tests
fetcheus/test_results/fetcheus/rosunit-fetch_moveit_test.xml: 1 tests
fetcheus/test_results/fetcheus/rosunit-fetcheus_test.xml: 4 tests
jsk_fetch_startup/test_results/jsk_fetch_startup/roslaunch-check_launch_fetch_gazebo_bringup.launch.xml: 1 tests
jsk_fetch_startup/test_results/jsk_fetch_startup/roslaunch-check_launch_rviz.launch.xml: 1 tests
jsk_fetch_startup/test_results/jsk_fetch_startup/roslaunch-check_test_roslaunch-check-fetch_bringup.xml.xml: 1 tests
jsk_pepper_startup/test_results/jsk_pepper_startup/roslaunch-check_jsk_pepper_startup__ROS_IP_10.68.0.2 NAO_IP_10.68.0.3.launch.xml: 1 tests
jsk_robot_utils/test_results/jsk_robot_utils/rostest-test_angle_vector_compress.xml: 1 tests
jsk_robot_utils/test_results/jsk_robot_utils/rostest-test_joint_state_compressor.xml: 1 tests
jsk_robot_utils/test_results/jsk_robot_utils/rosunit-angle_vector_compress_error_test.xml: 1 tests
jsk_robot_utils/test_results/jsk_robot_utils/rosunit-angle_vector_compress_test.xml: 1 tests
naoeus/test_results/naoeus/rostest-test_naoeus.xml: 1 tests
naoeus/test_results/naoeus/rosunit-naoeus_test.xml: 1 tests
naoqieus/test_results/naoqieus/rostest-test_naoqieus.xml: 1 tests
naoqieus/test_results/naoqieus/rosunit-naoqieus_test.xml: 1 tests
pr2_base_trajectory_action/test_results/pr2_base_trajectory_action/gtest-spline_test.xml: 1 tests
Summary: 32 tests, 2 errors, 2 failures, 0 skipped
```

Tests on baxter lisp and moveit seems failed.

```
*** Error in `/opt/ros/indigo/lib/moveit_ros_move_group/move_group': corrupted double-linked list: 0x0000000001be0300 ***

[move_group-1] process has died [pid 46021, exit code -6, cmd /opt/ros/indigo/lib/moveit_ros_move_group/move_group joint_states:=/robot/joint_states __name:=move_group __log:=/workspace/jsk-ros-pkg/jsk_robot/log/790319cc-8cb9-11e7-a62b-0242ac110003/move_group-1.log].

log file: /workspace/jsk-ros-pkg/jsk_robot/log/790319cc-8cb9-11e7-a62b-0242ac110003/move_group-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done
```

Maybe moveit ends abnormally.

**Comment by k-okada** [comment]
@knorth55 can you check baxter tests -> https://gist.github.com/k-okada/ce4ff3ac69b30fb0da6d1a84c8c26796/raw/f195e194e33ed23d1ef4dc7c6ff55c767f75f2b7/consoleText.txt

**Comment by knorth55** [comment]
* ` jsk_baxter_robot/baxtereus/test/test-baxter.test`

`300` is too short. (it is modified in https://github.com/jsk-ros-pkg/jsk_robot/commit/10906589f61a6d33599d05dd5710cbd49cab64e6)

```
<testsuite errors="1" failures="0" name="unittest.suite.TestSuite" tests="1" time="301.013">
  <testcase classname="rostest.runner.RosTest" name="testbaxter_lisp" time="301.0125">
    <error type="RLTestTimeoutException">max time [300.0s] allotted for test [baxter_lisp] of type [baxtereus/test-baxter.l]
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/runner.py", line 148, in fn
    self.test_parent.run_test(test)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/rostest_parent.py", line 132, in run_test
    return self.runner.run_test(test)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/launch.py", line 681, in run_test
    (test.time_limit, test.test_name, test.package, test.type))
    </error>
  </testcase>
```

* `jsk_baxter_robot/baxtereus/test/baxter-moveit.test`

Currently, gazebo fails with segmentation fault.
I need to look more.

**Comment by knorth55** [comment]
it looks `moveit` dies
```
*** Error in `/opt/ros/indigo/lib/moveit_ros_move_group/move_group': corrupted double-linked list: 0x0000000001be0300 ***




[move_group-1] process has died [pid 46021, exit code -6, cmd /opt/ros/indigo/lib/moveit_ros_move_group/move_group joint_states:=/robot/joint_states __name:=move_group __log:=/workspace/jsk-ros-pkg/jsk_robot/log/790319cc-8cb9-11e7-a62b-0242ac110003/move_group-1.log].



log file: /workspace/jsk-ros-pkg/jsk_robot/log/790319cc-8cb9-11e7-a62b-0242ac110003/move_group-1*.log





all processes on machine have died, roslaunch will exit
```

**Comment by furushchev** [comment]
@knorth55 OK. Temporally disabled tests on baxtereus since all pull requests are left unmerged due to the failure. Please fix test codes.

**Comment by furushchev** [comment]
@k-okada Please merge if there is no problem. :+1:

**Comment by k-okada** [comment]
@furushchev @knorth55 when the disabled test will re-activated, and who have responsibilities for that?

**Comment by knorth55** [comment]
i will

**Comment by knorth55** [comment]
now it seems that `baxter-moveit.test` is build passing on `master`.

**Comment by k-okada** [comment]
ok, @furushchev please remove https://github.com/jsk-ros-pkg/jsk_robot/pull/826/commits/7030af6fc88a3dc6ea6814b4e9ecd52feba6baf2 commit

**Comment by furushchev** [comment]
@knorth55 I want to know why it was fixed. Is upstream updated?
@k-okada Removed the commit!

**Comment by knorth55** [comment]
> @knorth55 I want to know why it was fixed. Is upstream updated?

I have no idea...

**Pull request merged**
