### PR TITLE
[jsk_fetch_startup] Update trashcan front position in kitchen demo

### PR DESCRIPTION
**Pull request by tkmtnt7000**
~~Please merge after jsk-ros-pkg#1458.~~
I cherry-picked https://github.com/knorth55/jsk_robot/pull/142 and https://github.com/knorth55/jsk_robot/pull/153.

I updated trashcan front position for Fetch to move faster around the trashcan than before.

### CODE REVIEW

**Comment by k-okada** [comment]
please see comments https://github.com/jsk-ros-pkg/jsk_robot/pull/1463#issuecomment-1104610190

**Comment by tkmtnt7000** [comment]
I rebased `708yamaguchi/use-relative-coords` to resolve conflicts and syncronize upstream branch.

**Comment by k-okada** [comment]
NeedDiscussion -> Did we embed images within the mail?

**Comment by tkmtnt7000** [comment]
I rebased current jsk-ros-pkg/jsk_robot master branch to resolve conflicts.

**Pull request merged**
