### PR TITLE
[jsk_pr2_startup] add face_recognition

### PR DESCRIPTION
**Pull request by furushchev**
temporally use `furushchev/face_recognition` (fix-show-screen-flag branch) forked from `procrob/face_recognition` until merge https://github.com/procrob/face_recognition/pull/6 to work PR2.

### CODE REVIEW

**Comment by furushchev** [comment]
@himlen1990 you can use face recognition like this

**Comment by furushchev** [comment]
Travis failed on indigo.

```
Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/wstool/common.py", line 283, in run

    result_dict = self.worker.do_work()

  File "/usr/lib/python2.7/dist-packages/wstool/multiproject_cmd.py", line 470, in do_work

    path_spec = self.element.get_versioned_path_spec(fetch=fetch)

  File "/usr/lib/python2.7/dist-packages/wstool/config_elements.py", line 414, in get_versioned_path_spec

    remote_revision = self._get_vcsc().get_remote_version(fetch=fetch)

AttributeError: 'GitClient' object has no attribute 'get_remote_version'

ERROR in config: Error processing 'jsk_robot' : 'GitClient' object has no attribute 'get_remote_version'
```

What should I fix when this error occurs?

**Comment by himlen1990** [comment]
Furuta san
Thanks for your help, I also found that eigenface demo recently and make a
little change so that it can work in ROS.

--LI

2015-09-11 11:41 GMT+09:00 Furushchev <notifications@github.com>:

**Comment by garaemon** [comment]
same error on https://github.com/jsk-ros-pkg/jsk_recognition/pull/1172
Please dig this issue > @furushchev

**Comment by garaemon** [comment]
https://github.com/vcstools/vcstools/blob/master/src/vcstools/git.py#L367
GitClient should have get_remote_version

**Comment by garaemon** [comment]
```
Preparing to unpack .../python-wstool_0.1.8-1_all.deb ...
Unpacking python-wstool (0.1.8-1) over (0.1.6-1) ...
```

**Comment by garaemon** [comment]
On my local environment:
```
$ aptitude show python-wstool
Package: python-wstool                   
New: yes
State: installed
Automatically installed: no
Version: 0.1.8-1
Priority: optional
Section: python
Maintainer: Tully Foote <tfoote@osrfoundation.org>
Architecture: all
Uncompressed Size: 247 k
Depends: python (>= 2.7), python (< 2.8), python:any (>= 2.7.1-0ubuntu2),
         python-vcstools (>= 0.1.34), python-yaml, subversion, mercurial,
         git-core, bzr
Conflicts: python3-wstool, python3-wstool
Description: workspace multi-SCM commands
 A tool for managing a workspace of multiple heterogenous SCM repositories
```

**Comment by garaemon** [comment]
BTW, currently jsk_pcl_ros's deb building on indigo fails and I will merge it by ignoring indigo error.

**Comment by garaemon** [comment]
https://github.com/procrob/face_recognition/pull/6 is merged and please update to use upstream repository

**Comment by furushchev** [comment]
@garaemon thanks, created PR https://github.com/jsk-ros-pkg/jsk_robot/pull/439

**Comment by furushchev** [comment]
@himlen1990 This package uses eigenface for face recognition algorithm. So you may not need to struggle to generate another one.

**Comment by k-okada** [comment]
@himlen1990, please compare your veresion with @furushchev version and
choose better one

--
◉ Kei Okada

**Comment by himlen1990** [comment]
@Furushchev @Kei Okada ，Thanks, @Furushchev's verson is more standard, and
I will pick that.

2015-09-12 14:25 GMT+09:00 Kei Okada <notifications@github.com>:

**Pull request merged**
