### PR TITLE
[pr2_base_trajectory_action] remove dependency to pr2_controller_msgs

### PR DESCRIPTION
**Pull request by furushchev**
What I did
* refactor codes
* remove pr2 related packages from dependencies
* use `control_msgs/FollowJointTrajectoryAction` instead of `pr2_controller_msgs`
* support publishing feedback message
* Write test codes
* Further Test on real robot / gazebo

### CODE REVIEW

**Comment by k-okada** [comment]
did you finished
> Write test codes
> Further Test on real robot / gazebo
??

Cc: @chiwunau

**Comment by furushchev** [comment]
@k-okada Sorry for late response. All has been done.

**Comment by furushchev** [comment]
@k-okada If this is merged, we can remove pr2 related packages from `robot-interface.l` (not `pr2-interface.l`). Should we move `robot-interface.l` to `jsk_roseus`?

**Comment by furushchev** [comment]
travis failed at `test/pr2_base_trajectory_action.test`.
I doubt that gazebo's `base_controller` does not work correctly. (at least different behavior from real robot)
@k-okada  Can I disable gazebo test?

**Comment by furushchev** [comment]
@k-okada How do you think of it?

**Comment by k-okada** [comment]
Why you have to disable gazebo test?

On Sunday, 10 July 2016, Furushchev <notifications@github.com> wrote:

> @k-okada <https://github.com/k-okada> How do you think of it?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_robot/pull/623#issuecomment-231585166>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAeG3KrWqYFjQ5QUKeCToMjKXnFKMA1Vks5qUN1fgaJpZM4I7YTc>
> .
>


-- 
--
◉ Kei Okada

**Comment by furushchev** [comment]
@k-okada maybe gazebo's realtime controller does not follow the actual /cmd_vel (slower than command), and it always causes failure of following trajectory in this action server.
But I could not yet inspect codes of pr2_gazebo.

**Comment by furushchev** [comment]
oh, closed wrongly...

**Comment by k-okada** [comment]
In that case you can send command with large error threshold

On Sunday, 10 July 2016, Furushchev <notifications@github.com> wrote:

> oh, closed wrongly...
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_robot/pull/623#issuecomment-231586793>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAeG3HUyZLC7h4LuRAhJKjgGCblsfjvMks5qUObogaJpZM4I7YTc>
> .
>


-- 
--
◉ Kei Okada

**Comment by furushchev** [comment]
@k-okada Yes, we can increase error threshold, but I think it actually does not test anything...just for check if publish /cmd_vel, we dont need gazebo..

**Comment by k-okada** [comment]
even so, it is important to check the code actually publish something and
simulated robot receive them

--
◉ Kei Okada

**Comment by furushchev** [comment]
@k-okada OK. I added note about this problem to test code and enabled test with broader thresholds.

**Comment by furushchev** [comment]
please merge after #644

**Comment by furushchev** [comment]
@k-okada I used pr2eus to test with gazebo, and it does not work until https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/237 is merged.
There are two choices.

1. merge https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/237
2. restart travis on this PR to test with new pr2eus

or.

1. merge this PR with temporally disable gazebo test
2. merge https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/237
3. create new PR to enable gazebo test

**Comment by k-okada** [comment]
ok, I'll merge  jsk-ros-pkg/jsk_pr2eus#237, before that please explain more
detail, because this will be a big change

1) which method has been changed, specially in robot-interface
2) since robot-interface is used in other robots, specially rtmros robots,
so why this change did not affect that robot, for example, I assume they
have override the information (
https://github.com/start-jsk/rtmros_common/blob/master/hrpsys_ros_bridge/euslisp/rtm-ros-robot-interface.l#L314),
so please list up such case in all method described in 1), and then they
will remove that code from rtm-ros-robot-interface in future.

Cc:@mmurooka


--
◉ Kei Okada

**Comment by snozawa** [comment]
Related:
- https://github.com/jsk-ros-pkg/jsk_pr2eus/issues/64
- https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/197

**Comment by furushchev** [comment]
@k-okada  Sorry for late reply.

> 1) which method has been changed, specially in robot-interface

in `robot-interface.l`, I only changed to use `control_msgs/FollowJointTrajectoryAction` instead of `pr2_controller_msgs/JointTrajectoryAction`. And moved `pr2_*` messages to `pr2-interface.l` from `robot-interface.l`.
changed methods are `:action-feedback-cb` in `controller-action-client` class, `:add-controller` and`:default-controller` in `robot-interface` class and `:init`, `:move-trajectory` in `robot-move-base-interface` class.

> 2) since robot-interface is used in other robots, specially rtmros robots,
> so why this change did not affect that robot, for example, I assume they
> have override the information (
> https://github.com/start-jsk/rtmros_common/blob/master/hrpsys_ros_bridge/euslisp/rtm-ros-robot-interface.l#L314),
> so please list up such case in all method described in 1), and then they
> will remove that code from rtm-ros-robot-interface in future.

Is there any robots that uses `pr2_controller_msgs` other than PR2?
In my thought, by this change, we will support wider variations of robot by using `control_msgs`, generalized messages, and removing `pr2_*` messages only can affect PR2 users.
And this PR removes dependency to `pr2_` messages for even PR2.
(Sorry basically I could not understand your second question)

**Comment by k-okada** [comment]
old robots uses `pr2_controller_msgs`, for example, hrp2
https://github.com/start-jsk/rtmros_common/blob/master/hrpsys_ros_bridge/src/HrpsysJointTrajectoryBridge.cpp#L223-L228
now they accept both `pr2_controller_msgs` and `controller_msgs`. 
This is why @snozawa 's originall PR at pr2eus depneds on pr2 ->  https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/197/files#diff-15f6920b924513f6027d36b361f85bbdR1066, 
but newer PR uses https://github.com/start-jsk/rtmros_common/pull/887/files#diff-d9351e39dede27bec86e5a1c49dcfaa0R312
So, I hope they now switched to `controller_msgs`, but also afraid that someone still using old message.

**Comment by furushchev** [comment]
Why not merge this pull request? If there is problem, please complain.
Merging only https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/237 breaks pr2 unsafe moving.

**Comment by furushchev** [comment]
@k-okada seems answered at https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/237

**Comment by k-okada** [comment]
I think this PR is ok to merge, because it is only base_trajectry_action

**Comment by furushchev** [comment]
@k-okada Thank you for review and merging!

**Pull request merged**
