### PR TITLE
[softhand_ros] use lower torque limit to avoid breakdown

### PR DESCRIPTION
**Pull request by knorth55**
I set lower torque limit for softhand to avoid breakdown.

cc. @YUKINA-3252 @soonhyo

### CODE REVIEW

**Comment by pazeshun** [comment]
Could you test this for a while?
I'm not sure this is really a good value.

**Comment by knorth55** [comment]
OK, I will test it.
this value is used about one year ago.

**Comment by pazeshun** [comment]
Is the root problem fixed by #1622?
If #1622 is enough, I think this PR should not be merged because this PR makes grasping looser.

**Comment by knorth55** [comment]
i thinks this pr is also needed because grasping torque is a bit high.
With this value, baxter can grasp object properly.

**Review by pazeshun — APPROVED** [review]

**Pull request merged**
