### PR TITLE
Fix calculation of imu orientation when imu parent link was moved

### PR DESCRIPTION
**Pull request by orikuma**
Please merge after https://github.com/jsk-ros-pkg/jsk_robot/pull/522

### CODE REVIEW

**Comment by garaemon** [comment]
merge origin/master

**Comment by orikuma** [comment]
looks like same error as https://github.com/start-jsk/rtmros_common/pull/876

**Comment by garaemon** [comment]
same error https://github.com/jsk-ros-pkg/jsk_travis/pull/206

I hope somebody fixes it.

**Comment by snozawa** [comment]
Yesterday successful rtmros_common travis log:
```
+++sudo easy_install pip
/usr/local/lib/python2.7/dist-packages/setuptools-12.0.5-py2.7.egg/pkg_resources/__init__.py:2510: PEP440Warning: 'python-apt (0.8.3ubuntu7)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
Searching for pip
Best match: pip 6.0.7
Processing pip-6.0.7-py2.7.egg
pip 6.0.7 is already the active version in easy-install.pth
Installing pip script to /usr/local/bin
Installing pip2.7 script to /usr/local/bin
Installing pip2 script to /usr/local/bin

Using /usr/local/lib/python2.7/dist-packages/pip-6.0.7-py2.7.egg
Processing dependencies for pip
Finished processing dependencies for pip
+++sudo pip install -U -q pip setuptools
[33mThe directory '/home/travis/.cache/pip/log' or its parent directory is not owned by the current user and the debug log has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want the -H flag.[0m
[33mThe directory '/home/travis/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want the -H flag.[0m
[33mYou are using pip version 6.0.7, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.[0m
[33mThe directory '/home/travis/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want the -H flag.[0m
```

Today's failure rtmros_common log:
```
+++sudo easy_install pip
Searching for pip
Best match: pip 7.1.2
Processing pip-7.1.2-py2.7.egg
pip 7.1.2 is already the active version in easy-install.pth
Installing pip script to /usr/local/bin
Installing pip2.7 script to /usr/local/bin
Installing pip2 script to /usr/local/bin

Using /usr/local/lib/python2.7/dist-packages/pip-7.1.2-py2.7.egg
Processing dependencies for pip
Finished processing dependencies for pip
+++sudo pip install -U -q pip setuptools
/usr/local/lib/python2.7/dist-packages/pip-7.1.2-py2.7.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 9, in <module>
    load_entry_point('pip==7.1.2', 'console_scripts', 'pip')()
  File "/usr/local/lib/python2.7/dist-packages/pip-7.1.2-py2.7.egg/pip/__init__.py", line 217, in main
    return command.main(cmd_args)
  File "/usr/local/lib/python2.7/dist-packages/pip-7.1.2-py2.7.egg/pip/basecommand.py", line 248, in main
    pip_version_check(session)
  File "/usr/local/lib/python2.7/dist-packages/pip-7.1.2-py2.7.egg/pip/utils/outdated.py", line 102, in pip_version_check
    installed_version = get_installed_version("pip")
  File "/usr/local/lib/python2.7/dist-packages/pip-7.1.2-py2.7.egg/pip/utils/__init__.py", line 858, in get_installed_version
    working_set = pkg_resources.WorkingSet()
  File "/usr/local/lib/python2.7/dist-packages/pip-7.1.2-py2.7.egg/pip/_vendor/pkg_resources/__init__.py", line 629, in __init__
    self.add_entry(entry)
  File "/usr/local/lib/python2.7/dist-packages/pip-7.1.2-py2.7.egg/pip/_vendor/pkg_resources/__init__.py", line 685, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/local/lib/python2.7/dist-packages/pip-7.1.2-py2.7.egg/pip/_vendor/pkg_resources/__init__.py", line 2075, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "/usr/local/lib/python2.7/dist-packages/pip-7.1.2-py2.7.egg/pip/_vendor/pkg_resources/__init__.py", line 1605, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "/usr/local/lib/python2.7/dist-packages/pip-7.1.2-py2.7.egg/pip/_vendor/pkg_resources/__init__.py", line 1963, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "/usr/local/lib/python2.7/dist-packages/pip-7.1.2-py2.7.egg/pip/_vendor/pkg_resources/__init__.py", line 1843, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "/usr/local/lib/python2.7/dist-packages/pip-7.1.2-py2.7.egg/pip/_vendor/pkg_resources/__init__.py", line 1783, in load
    mtime = os.stat(path).st_mtime
OSError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/setuptools-18.8-py2.7.egg'
```

pip versions are different.

**Comment by garaemon** [comment]
Specify version?
http://oxon.hatenablog.com/entry/20111227/1324957498

**Comment by snozawa** [comment]
- success
https://travis-ci.org/start-jsk/rtmros_common/jobs/96717014
- failure
https://travis-ci.org/start-jsk/rtmros_common/jobs/96933018

**Comment by garaemon** [comment]
https://blog.travis-ci.com/2015-11-27-moving-to-a-more-elastic-future

**Comment by garaemon** [comment]
travis environment is updated

**Comment by snozawa** [comment]
> travis environment is updated

Yes, in both logs, build image was different:
- success:
```
Build image provisioning date and time
Wed Feb  4 18:22:50 UTC 2015
```
- failure:
```
Build image provisioning date and time
Sat Dec 12 02:23:00 UTC 2015
```
(But it does not appear on doc https://docs.travis-ci.com/user/build-environment-updates...)

> Specify version?

It worthy to try.
According to https://urllib3.readthedocs.org/en/latest/security.html, 
recommended solution is upgrading python version or OpenSSL/PyOpenSSL solutions:
```
If you encounter this warning, it is strongly recommended you upgrade to a newer Python version, or that you use pyOpenSSL as described in the OpenSSL / PyOpenSSL section.
```

Upgrading python seems to be difficult.
pyOpenSSL description (https://urllib3.readthedocs.org/en/latest/security.html#pyopenssl) uses `pip` itself?

So, let's try to specify pip version as 6.0.7.

**Comment by garaemon** [comment]
I think `sudo easy_install pip` should be like `sudo easy_install pip=6.0.7` in jsk_travis

**Pull request merged**
