### PR TITLE
[develop/fetch] [jsk_robot_startup] Record image topic to mongodb every time

### PR DESCRIPTION
**Pull request by tkmtnt7000**
This PR enables robot to record image topic to mongodb every time.

Original PR to master branch is https://github.com/jsk-ros-pkg/jsk_robot/pull/1792, and I adopted to fetch's enviroment.

### CODE REVIEW

**Comment by tkmtnt7000** [comment]
Ready for review.

**Comment by tkmtnt7000** [comment]
Could you review this? @sktometometo @mqcmd196

**Review by mqcmd196 — APPROVED** [review]
lgtm

**Comment by tkmtnt7000** [comment]
Thank you!

**Pull request merged**
