### PR TITLE
Smach to email/twitter

### PR DESCRIPTION
**Pull request by k-okada**
add `jsk_robot_startup/scripts/smach_to_mail.py` which  sends smach message to `/email`, `/tweet`, etc...

based on @tkmtnt7000 's code https://github.com/k-okada/jsk_robot/pull/60#issuecomment-1194891312
This PR depends on https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/371

example SMACH examples can be found at  https://github.com/jsk-ros-pkg/jsk_robot/pull/1528
- https://github.com/k-okada/jsk_robot/blob/pepper_cross/jsk_naoqi_robot/jsk_pepper_startup/apps/meeting/scripts/meeting.l
- https://github.com/k-okada/jsk_robot/blob/pepper_cross/jsk_robot_common/jsk_robot_startup/lifelog/speaking-program-is-started-or-terminated.l

@mqcmd196 Can you add `_send_google_chat` function to this program ?

### CODE REVIEW

**Comment by tkmtnt7000** [comment]
I am sorry for late for send PR. This PR is related to https://github.com/knorth55/jsk_robot/pull/303 and more feature.

**Comment by k-okada** [comment]
```mermaid
flowchart TB
    subgraph S[Demo Code Running on SMACH]
      START --> State_1
      State_1 --> State_2
      State_2 --> END
    end
   subgraph E[SMACH To Notification]
      id1[(state list<br>DESCRIPTION / IMAGE<br>DESCRIPTION / IMAGE<br>...)]
     id1 --> email[[pub /email jsk_robot_startup::Email]]
     id1 --> tweet[[pub /tweet std_msgs::String]] 
   end
   S -->|"[{'DESCRIPTION': string, 'IMAGE': base64}]"| E
   email --> email_body(["DESCRIPTION[0]<br>DESCRIPTION[1]<br>IMAGE[1]<br>DESCRIPTION[1]<br>IMAGE[1]<br>..."])
   tweet --> tweet_body1(["DESCRIPTION[0]"])
   tweet_body1 --> tweet_body2(["DESCRIPTION[1]<br>IMAGE[1]"])
   tweet_body2 --> tweet_body3(["DESCRIPTION[2]<br>IMAGE[2]"])




```

**Comment by mqcmd196** [comment]
okay, I'll do it tonight

**Comment by k-okada** [comment]
@tkmtnt7000, please split https://github.com/knorth55/jsk_robot/pull/303  into smach-kitchen-demo  and smach-to-email, and if you find something to add here, please create PR, for example https://github.com/knorth55/jsk_robot/pull/303/commits/8bb35d4814f8196086a761cc4af3acaa28f34f43 ?

**Comment by mqcmd196** [comment]
Sorry for being late, please check https://github.com/k-okada/jsk_robot/pull/72

**Comment by k-okada** [comment]
note: we may remove `/var/lib/robot/email_topic.yaml` https://github.com/k-okada/jsk_robot/pull/71#issuecomment-1223487301

**Pull request merged**
