### PR TITLE
jsk_robot_startup: add LightweightLogger nodelet

### PR DESCRIPTION
**Pull request by furushchev**
Add nodelet to log messages.
Requires: https://github.com/jsk-ros-pkg/jsk_common/pull/1544 and https://github.com/strands-project/mongodb_store/pull/198

### CODE REVIEW

**Comment by k-okada** [comment]
it seems all upstream was merged, waiting for release?

**Comment by furushchev** [comment]
@k-okada Sorry for late reply. Rebased and restarted test.

**Comment by furushchev** [comment]
@k-okada Oh, you are right! `jsk_topic_tools` is need to be released.

```bash
Errors << jsk_robot_startup:make /home/travis/ros/ws_jsk_robot/logs/jsk_robot_startup/build.make.000.log
In file included from /home/travis/ros/ws_jsk_robot/src/jsk_robot/jsk_robot_common/jsk_robot_startup/src/lightweight_logger_nodelet.cpp:40:0:

/home/travis/ros/ws_jsk_robot/src/jsk_robot/jsk_robot_common/jsk_robot_startup/include/jsk_robot_startup/lightweight_logger.h:45:43: fatal error: jsk_topic_tools/stealth_relay.h: No such file or directory

 #include <jsk_topic_tools/stealth_relay.h>

                                           ^

compilation terminated.

**Comment by furushchev** [comment]
Created request issue to release https://github.com/jsk-ros-pkg/jsk_common/issues/1567

**Comment by furushchev** [comment]
requires https://github.com/jsk-ros-pkg/jsk_common/pull/1568

**Comment by furushchev** [comment]
Now test passed.

**Comment by k-okada** [comment]
Please explain what LightweightLogger is. Is this logger using nodelet? or doing some throttle function?

https://github.com/jsk-ros-pkg/jsk_robot/pull/827/files#diff-2dcae83bf7a6da0cf8305a58bafafbc2R36
```
+macro(add_lifelog_nodelet _cpp _cls _bin)
+add_lifelog_nodelet(src/lightweight_logger_nodelet.cpp "jsk_robot_lifelog/LightweightLogger" "lightweight_logger")
```
seems like you'll plan to add more nodelet using `add_lifelog_nodelet` macro

and also 
```
+add_executable(joint_states_throttle
````
seems you'll going add another throttle for joint_states?

**Comment by furushchev** [comment]
## Overview

So, in this pull request, I'm trying to add general logging feature by recording several topics that describe robot behaviors during their running task.

The entrypoint is `common_logger.launch` in `jsk_robot_startup/lifelog` that runs several nodes for logging robot states and sensor values.

I added two application of this launch file for PR2 and fetch robots, (located at `jsk_fetch_startup/launch/fetch_lifelog.xml`, `jsk_pr2_startup/jsk_pr2_lifelog/db_client.launch`) and checked that this feature works on real robots.
(I have a plan to add for more robots)

## Detail

This pull request also includes several nodes for logging:

- `jsk_robot_startup/lightweight_logger`

This is a nodelet that subscribes any topic(s) without serialization and send them to mongodb.
This nodelet inherits `jsk_topic_tools/StealthRelay` in order that it can treat itself as stealth node for publishers (It is useful for connection based nodelets)

- `jsk_robot_startup/tf_logger`

This is for logging transformation at each timepoint.
The difference from just recording `/tf` are:
- this node captures all transformations at a timepoint and aggregates into one topic, so we can lookup any available transformations by getting one logged document afterward.
- Support static tf (provided in TF2)
- `/tf` is published from multiple publishers with various frequencies, this nodes aggregates and records periodically not to load database and traffic.

- `jsk_robot_startup/joint_states_throttle_node`

This is utility node for logging joint states of robots.
Since a message of joint states is published very frequently regardless it differs in values of them or not, this node throttles by checking differences between incoming joint values and previous ones.
For joints that moves continuously like tilt laser of PR2, blacklist joints can be set not to count as differences.

- `jsk_robot_startup/mongo_record`

This is a supplemental node that can record any type of topics from both roslaunch / command line like `rosbag record`.

## Others

> seems like you'll plan to add more nodelet using add_lifelog_nodelet macro

Yes. I worried about mixing lifelog related nodelets with other type of nodelets in this package. (Just wanted to create isolated `.so` file for logging nodelets)

> seems you'll going add another throttle for joint_states?

Yes, since joint states has a special character that can be throttled, it is treated specially.
As far as I know, most of publishers that publishes joint states is not a nodelet, so I thought this node does not need to be nodelet. That is why I used `add_executable`.

**Comment by k-okada** [comment]
thank you!

**Comment by furushchev** [comment]
@k-okada Thank you for reviewing & merging this!

**Pull request merged**
