### PR TITLE
[jsk_pr2_startup/people_detection.launch] add people tracker

### PR DESCRIPTION
**Pull request by furushchev**
this PR enables people tracking using face/leg detection

### CODE REVIEW

**Comment by k-okada** [comment]
are you sure that you did not updated package.xml to install leg_detector?
what is the role of scan filter?

**Comment by furushchev** [comment]
@k-okada Thank you very much for confirming! Added deps to package.xml.
I added scan filter to get filtered data of `/base_scan` as `sensor_msgs/LaserScan` not as `PointCloud` in order to work with `leg_detector`

**Comment by k-okada** [comment]
just to confirm
- 
https://github.com/jsk-ros-pkg/jsk_3rdparty/blob/master/jsk_ros_patch/laser_filters_jsk_patch/launch/footobject_filter_example.launch 
try to extract table foot, filtering "shaow" (noise) from lasers
- 
https://github.com/furushchev/jsk_robot/blob/add-people-tracker/jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_sensors/lasers_and_filters.xml 
try to filter wall data ?

--
◉ Kei Okada

**Comment by furushchev** [comment]
@k-okada Sorry for late response. I fixed to use existing filtered pointcloud data with conversion to LaserScan instead of creating it again from /base_scan.

**Pull request merged**
