### PR TITLE
[fetcheus] skip undocking when subscribe timeout in go-to-spot

### PR DESCRIPTION
**Pull request by knorth55**
Because of message type difference between melodic and indigo, `go-to-spot` stacks in subscription of `/battery_state`.
I change to skip the subscription in `go-to-spot` when the subscription is timeout.

### CODE REVIEW

**Comment by 708yamaguchi** [comment]
Thank you.

In order to inform users of the purpose of your code, Please add a comment like
```
;; Because of message type difference between melodic and indigo
```

**Comment by knorth55** [comment]
Thx, I updated to add comment.

**Comment by knorth55** [comment]
@k-okada I want to use this for B3's seminor. Can you review and merge this?

**Comment by k-okada** [comment]
@knorth55 please check https://github.com/jsk-ros-pkg/jsk_roseus/pull/631 whether if we can rewrite this code with `AnyMsg`

**Pull request merged**
