### PR TITLE
[wait for upstream] [jsk_fetch_startup] add basic authentication in roswww on fetch

### PR DESCRIPTION
**Pull request by knorth55**
wait for upstream
depend on https://github.com/tork-a/roswww/pull/51

add basic authentication for all roswww pages

roswww_basic_auth

cc. @708yamaguchi

### CODE REVIEW

**Comment by 708yamaguchi** [comment]
I accessed this page with chrome, but at first topic list was not displayed.
It behaves correctly after two reloads. (I don't know the reason, but 2 reload seems important)

rwt_error

I use chrome browser.
When I use normal window, this only happens once.
When I create new incognito window, this happens repeatedly.

**Comment by knorth55** [comment]
@708yamaguchi I confirmed the issue, but I can get proper page at once when I connect to pr1040.
I checked with web developer and some css are failed to download.
maybe something got timeout.

**Comment by 708yamaguchi** [comment]
Thank you for thoughts. I agree with you.
It seems that not only css files but also ROSLIB or jQuery are sometimes not loaded.

The error says,
```
 Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH roslib.js:1
```
This may be cache problem (?)
https://cpoint-lab.co.jp/article/201809/5517/

**Review by k-okada — COMMENTED** [review]
do we need to add `tork-a/roswww`
https://github.com/jsk-ros-pkg/jsk_robot/blob/master/jsk_fetch_robot/jsk_fetch.rosinstall ?

**Comment by knorth55** [comment]
yes we need https://github.com/tork-a/roswww/pull/51.
@k-okada do you have a plan to merge https://github.com/tork-a/roswww/pull/51 ?

**Pull request merged**
