### PR TITLE
[WIP] Merge PR1040 branch to master

### PR DESCRIPTION
**Pull request by knorth55**
move from #1081 
this PR is now split into PRs below;

## Main changes

- [ ] #1342
- [ ] #1417
- [ ] #1491 

## New package dependency
- https://github.com/knorth55/app_manager_utils
- https://github.com/knorth55/coral_usb_ros

## Merged
- `jsk-ros-pkg/jsk_robot`
  - [x] #1121
  - [x] #1136
  - [x] #1141
  - [x] #1142
  - [x] #1144
  - [x] #1150
  - [x] #1178
  - [x] #1180
  - [x] #1182
  - [x] #1183
  - [x] #1184
  - [x] #1191
  - [x] #1192
  - [x] #1198
  - [x] #1223
  - [x] #1225
  - [x] #1227
  - [x] #1233
  - [x] #1234
  - [x] #1241
  - [x] #1247
  - [x] #1248
  - [x] #1255
  - [x] #1256
  - [x] #1258
  - [x] #1281
  - [x] #1282
  - [x] #1284
  - [x] #1286
  - [x] #1300
  - [x] #1308
  - [x] #1310
  - [x] #1314
  - [x] #1340
  - [x] #1341
  - [x] #1347
  - [x] #1359
  - [x] #1360
  - [x] #1361
  - [x] #1381
  - [x] #1392
  - [x] #1393
  - [x] #1401
  - [x] #1418
- `PR2/app_manager`
  - [x] https://github.com/PR2/app_manager/pull/25
  - [x] https://github.com/PR2/app_manager/pull/26
- `tork-a/roswww`
  - [x] https://github.com/tork-a/roswww/pull/51

cc. @YutoUchimi @Affonso-Gui @Kanazawanaoaki

### CODE REVIEW

**Comment by YutoUchimi** [comment]
Now this PR passed travis test, and all splitted PRs listed above passed travis as well!
Each component is ready to be reviewed / merged.

**Comment by knorth55** [comment]
@tkmtnt7000 are these commits included in some PRs?

[`98f25c5` (#1143)](https://github.com/jsk-ros-pkg/jsk_robot/pull/1143/commits/98f25c5a2807e478aec9724692de1f23550eb35c)
[`c742c0d` (#1143)](https://github.com/jsk-ros-pkg/jsk_robot/pull/1143/commits/c742c0d69143b466f876dc67ffe91e57f441a119)
[`4d37695` (#1143)](https://github.com/jsk-ros-pkg/jsk_robot/pull/1143/commits/4d376954ecd4c9b390104889d177ee3c1e998363)

**Comment by tkmtnt7000** [comment]
Thank you. I have made PR https://github.com/jsk-ros-pkg/jsk_robot/pull/1584

**Comment by knorth55** [comment]
this PR is moved to #1591

**Pull request closed without merging**
