### PR TITLE
refactor tweet nodes

### PR DESCRIPTION
**Pull request by furushchev**
Need https://github.com/ros-perception/image_pipeline/pull/391

### CODE REVIEW

**Comment by knorth55** [comment]
@furushchev  can you cherry-pick this commit?
https://github.com/furushchev/jsk_robot/pulls

**Comment by knorth55** [comment]
@k-okada I think this PR works without upstream change, too.
We need this PR, otherwise we need to disable twitter on all robots.

**Comment by k-okada** [comment]
is this refactor ? or bug fix?

**Comment by knorth55** [comment]
both. refactor and bug fix.

**Comment by k-okada** [comment]
so, what kind of bug did you have?
--
◉ Kei Okada



2019年4月18日(木) 11:25 Shingo Kitagawa <notifications@github.com>:

**Comment by knorth55** [comment]
im fixing bugs for fetch in https://github.com/jsk-ros-pkg/jsk_robot/pull/1049

**Comment by knorth55** [comment]
bugs:
- several  bugs in `active_user.l` ( which is also fixed in #1049)
- several bugs in `tweet_client.l` (which is also fixed in #1049)
- image_saver bug (fixed in upstream, or fix by waiting 10 seconds in #1049)

**Comment by k-okada** [comment]
@knorth55 can we close this?

**Comment by knorth55** [comment]
@k-okada yes you can.

**Pull request closed without merging**
