### PR TITLE
[jsk_robot_startup] Look at human for Fetch and PR2

### PR DESCRIPTION
**Pull request by 708yamaguchi**
Based on [this advice](https://github.com/jsk-ros-pkg/jsk_robot/pull/1297#issuecomment-747180855), I created robot-independent look-at-human program.

### CODE REVIEW

**Comment by k-okada** [comment]
@708yamaguchi This is not directory related to this PR, but I found something weird
with JTA/{state,status}. Is this OK?
```
[http://fetch1075:11311][133.11.216.191] k-okada@p51s:~$ rostopic info /torso_controller/follow_joint_trajectory/state
Type: control_msgs/JointTrajectoryControllerState

Publishers: None

Subscribers: 
 * /look_at_human (http://fetch1075:33621/)


[http://fetch1075:11311][133.11.216.191] k-okada@p51s:~$ rostopic info /torso_controller/follow_joint_trajectory/status
Type: actionlib_msgs/GoalStatusArray

Publishers: 
 * /robot_driver (http://fetch1075:46447/)

Subscribers: 
 * /teleop (http://fetch1075:45317/)
 * /look_at_human (http://fetch1075:33621/)


```

**Comment by pazeshun** [comment]
@k-okada
Could you describe what is weird more?
I think some robots don't publish JTA/state:
https://github.com/RethinkRobotics/baxter_interface/issues/76
But euslisp `*ri*` subscribes it for `:reference-vector`:
https://github.com/jsk-ros-pkg/jsk_robot/issues/738#issuecomment-264788132
So when we need `:reference-vector`, we have to request the manufacturer to publish JTA/state if the driver is closed code (or we have to fix `*ri*`).

**Comment by k-okada** [comment]
`/look_at_human` subscribes `rostopic info /torso_controller/follow_joint_trajectory/state`, but no one publishing.

**Comment by pazeshun** [comment]
OK.

***
> `/look_at_human` subscribes `rostopic info /torso_controller/follow_joint_trajectory/state`

`/look_at_human` uses `*ri*` and `*ri*` subscribes JTA/state, so it is not "weird".
`/look_at_human` uses `*ri*`:
https://github.com/jsk-ros-pkg/jsk_robot/blob/25ac99ab82539b0e95d20470db1675b5f2f58c56/jsk_fetch_robot/jsk_fetch_startup/launch/fetch_bringup.launch#L34-L38
https://github.com/jsk-ros-pkg/jsk_robot/blob/25ac99ab82539b0e95d20470db1675b5f2f58c56/jsk_fetch_robot/jsk_fetch_startup/euslisp/fetch-look-at-human.l#L8
`*ri*` subscribes JTA/state (for instance, `:reference-vector` uses it: https://github.com/jsk-ros-pkg/jsk_robot/issues/738#issuecomment-264788132):
https://github.com/jsk-ros-pkg/jsk_robot/blob/25ac99ab82539b0e95d20470db1675b5f2f58c56/jsk_fetch_robot/fetcheus/fetch-interface.l#L162

***

> but no one publishing

Current `/robot_driver` on Fetch doesn't seem to publish JTA/state.
But as I wrote in https://github.com/RethinkRobotics/baxter_interface/issues/76, it is "weird" because JTAs of PR2 and ros_control publish JTA/state.

@k-okada
Current situation is surely "weird".
On the other hand, it doesn't cause an issue unless someone wants to use `:reference-vector` on Fetch.
Do you have any suggestions?
Should we create an issue to https://github.com/fetchrobotics/robot_controllers/issues at least?

**Pull request merged**
