### PR TITLE
[jsk_fetch_startup] add robot_pose_publisher in fetch_bringup.launch

### PR DESCRIPTION
**Pull request by knorth55**
I add `robot_pose_publisher` in `fetch_bringup.launch` for `rwt_nav`

https://github.com/tork-a/visualization_rwt/pull/96

cc. @708yamaguchi

### CODE REVIEW

**Review by 708yamaguchi — COMMENTED** [review]
Thank you for this PR.
I think this is OK.

By the way, is `rwt_nav` currently running on Fetch15 or Fetch1075?
I cannot find the port number...

**Comment by 708yamaguchi** [comment]
Thank you for your offline talk.
I can access `rwt_nav`!

**Review by 708yamaguchi — APPROVED** [review]

**Review by k-okada — COMMENTED** [review]
@708yamaguchi should we add 
```
#robot_pose_publisher is not released in melodic
# https://github.com/GT-RAIL/robot_pose_publisher/issues/8
# robot_pose_publisher is needed for rwt_nav
- git:
    local-name: GT-RAIL/robot_pose_publisher
    uri: https://github.com/GT-RAIL/robot_pose_publisher.git
    version: 0.2.4
```
to https://github.com/jsk-ros-pkg/jsk_robot/blob/master/jsk_fetch_robot/jsk_fetch_user.rosinstall.melodic ?

**Comment by 708yamaguchi** [comment]
In my understanding, we can access `/robot_pose` topic published in fetch's PC from web browser, so `robot_pose_publisher` is needed only in fetch's PC.

So I think `robot_pose_publisher` does not need to be added to jsk_fetch_user.rosinstall.melodic.

@knorth55 
Please teach me if my understanding is wrong...

**Comment by knorth55** [comment]
@708yamaguchi 
>So I think robot_pose_publisher does not need to be added to jsk_fetch_user.rosinstall.melodic.

Yes, you are right.

**Comment by k-okada** [comment]
oh, I mean `jsk_fetch.rosinstall`

**Comment by 708yamaguchi** [comment]
Thank you, `robot_pose_publisher` is now added to `jsk_fetch.rosinstall.melodic`
https://github.com/jsk-ros-pkg/jsk_robot/blob/master/jsk_fetch_robot/jsk_fetch.rosinstall.melodic#L100-L104

For kinetic or older, `robot_pose_publisher` can be installed by apt.
https://index.ros.org/p/robot_pose_publisher/github-GT-RAIL-robot_pose_publisher/#indigo
https://index.ros.org/p/robot_pose_publisher/github-GT-RAIL-robot_pose_publisher/#kinetic

**Comment by k-okada** [comment]
@708yamaguchi So can we close this PR?

**Comment by knorth55** [comment]
we want to run pose_publisher infetch_bringup.launch

**Pull request merged**
