### PR TITLE
[.travis] update to latest

### PR DESCRIPTION
**Pull request by furushchev**
This will fix recent error
https://github.com/jsk-ros-pkg/jsk_robot/pull/526#issuecomment-164995158

### CODE REVIEW

**Comment by furushchev** [comment]
test failed

```
]2;[build] 16/16]2;[build] 16/16[jsk_pepper_startup] ... logging to /home/travis/.ros/log/rostest-testing-gce-097c92b1-9b0d-4df5-af87-fbc29c712c4f-24478.log 
]2;[build] 16/16]2;[build] 16/16[jsk_pepper_startup] Traceback (most recent call last): 
]2;[build] 16/16[jsk_pepper_startup]   File "/opt/ros/hydro/share/rostest/cmake/../../../bin/rostest", line 53, in  
]2;[build] 16/16[jsk_pepper_startup]     rostestmain()  
]2;[build] 16/16[jsk_pepper_startup]   File "/opt/ros/hydro/lib/python2.7/dist-packages/rostest/__init__.py", line 268, in rostestmain 
]2;[build] 16/16[jsk_pepper_startup]     _main()        
]2;[build] 16/16[jsk_pepper_startup]   File "/opt/ros/hydro/lib/python2.7/dist-packages/rostest/rostest_main.py", line 149, in rostestmain 
]2;[build] 16/16[jsk_pepper_startup]     testCase = rostest.runner.createUnitTest(pkg, test_file) 
]2;[build] 16/16[jsk_pepper_startup]   File "/opt/ros/hydro/lib/python2.7/dist-packages/rostest/runner.py", line 227, in createUnitTest 
]2;[build] 16/16[jsk_pepper_startup]     config = roslaunch.parent.load_config_default([test_file], _DEFAULT_TEST_PORT) 
]2;[build] 16/16[jsk_pepper_startup]   File "/opt/ros/hydro/lib/python2.7/dist-packages/roslaunch/config.py", line 430, in load_config_default 
]2;[build] 16/16[jsk_pepper_startup]     raise RLException(e) 
]2;[build] 16/16[jsk_pepper_startup] roslaunch.core.RLException: environment variable 'CATKIN_TEST_RESULTS_DIR' is not set 
]2;[build] 16/16[jsk_pepper_startup] -- run_tests.py: verify result "/home/travis/ros/ws_jsk_robot/build/jsk_pepper_startup/test_results/jsk_pepper_startup/rostest-test_check_launch.xml" 
]2;[build] 16/16[jsk_pepper_startup] Cannot find results, writing failure results to '/home/travis/ros/ws_jsk_robot/build/jsk_pepper_startup/test_results/jsk_pepper_startup/MISSING-rostest-test_check_launch.xml' 
```

**Comment by garaemon** [comment]
Same error on indigo.
Fix it.
I think add_rostest should be after of catkin_package

https://groups.google.com/forum/#!topic/ros-sig-buildsystem/suBvWzoGODU

**Comment by furushchev** [comment]
@garaemon Thank you for information. Fixed.

**Comment by furushchev** [comment]
wait for https://github.com/ros-naoqi/pepper_robot/pull/18

**Comment by furushchev** [comment]
@garaemon @k-okada
Until this PR is merged, all builds don't pass test, but upstream is not released for now, so I disabled roslaunch check test on `jsk_pepper_startup` for a while. Is this OK?

**Comment by garaemon** [comment]
> so I disabled roslaunch check test on jsk_pepper_startup for a while. Is this OK?

yeah, sounds resonable

**Comment by furushchev** [comment]
maybe no apt-key on jenkins?

```bash
+ sh -c 'echo "ros-indigo-pepper-meshes ros-pepper-meshes/accepted-ros-pepper-meshes boolean true" | sudo debconf-set-selections; sudo apt-get install -y -qq ros-indigo-pepper-meshes; '

WARNING: The following packages cannot be authenticated!

  ros-indigo-pepper-meshes

E: There are problems and -y was used without --force-yes
```

**Comment by k-okada** [comment]
how about keep test file without updating to latest jsk_travis

--
◉ Kei Okada

**Comment by k-okada** [comment]
```
 sh -c 'echo "ros-indigo-pepper-meshes ros-pepper-meshes/accepted-ros-pepper-meshes boolean true" | sudo debconf-set-selections; sudo apt-get install --force-yes -y -qq ros-indigo-pepper-meshes; '
```
?

**Comment by orikuma** [comment]
Is this PR ready to be merged?
.travis is needed to be updated to run other tests.

**Comment by k-okada** [comment]
how other test depends on this?
usually newer jsk_travis has strict rule than olders, so using newer one
means you'll have to more work to pass the test.
So smart people will use old jsk_travis and concentrate on graduation >
write paper > do experiment > calibration > fix to pass test > update
jsk_travis

--
◉ Kei Okada

**Comment by orikuma** [comment]
I needed this change: https://github.com/jsk-ros-pkg/jsk_travis/pull/211

**Pull request merged**
