### PR TITLE
[jsk_robot_startup] add jenkins/musca to database replication node

### PR DESCRIPTION
**Pull request by furushchev**

### CODE REVIEW

**Comment by k-okada** [comment]
restarted travis, but why you need musca?

**Comment by furushchev** [comment]
@k-okada thanks. I'd like to add musca to replication server because ISTCloud is more unstable than I thought. ( https://github.com/jsk-ros-pkg/jsk_robot/issues/407 )

**Comment by k-okada** [comment]
I see, so robot-database is ist cloud machine, can you use Jenkins or pr2base machine for dis purpose?

**Comment by furushchev** [comment]
@k-okada OK. I also added jenkins.  tested on PR1012.

**Pull request merged**
