### PR TITLE
[baxtereus] support tm :fast in moveit angle-vector methods

### PR DESCRIPTION
**Pull request by knorth55**
Requires https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/297

# Changes
- support tm `:fast` in moveit `:angle-vector` and `:angle-vector-sequence` methods

# Minor Changes
- update doc

### CODE REVIEW

**Comment by knorth55** [comment]
Add test for `angle-vector-sequence` and `tm :fast`.
Currently, test fails because of https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/297.

**Comment by knorth55** [comment]
waiting for upstream

**Comment by knorth55** [comment]
Update and follow https://github.com/jsk-ros-pkg/jsk_robot/pull/791#pullrequestreview-45324124

**Comment by k-okada** [comment]
whad do you think if we support old API like https://github.com/jsk-ros-pkg/jsk_robot/pull/795 ? new api (av tm ctype start-time :...) are already used in apc?

**Comment by knorth55** [comment]
I use new API in order to pass keyword arguments, but `start-time` is always `0`.
I prefer old API, which pass `start-time` in keyword argument.

**Comment by knorth55** [comment]
@k-okada Test passed! Please merge this.

**Pull request merged**
