### PR TITLE
jsk_robot_startup: use synchronized_throttle for camera

### PR DESCRIPTION
**Pull request by furushchev**
Merge this after #919 
Replaces `jsk_topic_tools/LightweightThrottle` with `jsk_topic_tools/SynchronizedThrottle`.

### CODE REVIEW

**Comment by k-okada** [comment]
please update package.xml something like `<depend gte="1.x.x">jsk_topic_tools</depend>`

**Comment by furushchev** [comment]
@k-okada Added `gte` attribute to `jsk_topic`tools` .
Since https://github.com/jsk-ros-pkg/jsk_common/pull/1579 is not yet released, I incremented the minor version from the current version.

**Comment by k-okada** [comment]
```
- The "run_depend" tag must not have the following attributes: gte
```
please read my comment very carefully , 'something like' means the information is not correct. may be it should be "something like" 'version_gte'
http://www.ros.org/reps/rep-0127.html#build-depend-multiple

**Comment by furushchev** [comment]
@k-okada Sorry, updated.

**Pull request merged**
