### PR TITLE
update jsk_travis

### PR DESCRIPTION
**Pull request by garaemon**

### CODE REVIEW

**Comment by garaemon** [comment]
drc_valve_task failed to run run_tests?
```
[drc_valve_task] ==> '/home/travis/ros/ws_jsk_robot/build/drc_valve_task/build_env.sh /usr/bin/make run_tests -j32 -l32' in '/home/travis/ros/ws_jsk_robot/build/drc_valve_task'
make: *** No rule to make target `run_tests'.  Stop.
[drc_valve_task] <== '/home/travis/ros/ws_jsk_robot/build/drc_valve_task/build_env.sh /usr/bin/make run_tests -j32 -l32' failed with return code '2'
```

**Comment by k-okada** [comment]
https://github.com/k-okada/jsk_demos/commit/ff7f5f481a26b446f2f83ea3f630ff4bdc696644
will solve this

--
◉ Kei Okada

**Comment by garaemon** [comment]
nice catch!

✉︎ Ryohei

**Comment by garaemon** [comment]
taken over by https://github.com/jsk-ros-pkg/jsk_robot/pull/250

**Pull request closed without merging**
