### PR TITLE
[jsk_fetch_startup/scripts/warning.py] bugfix: error with no robot_state msg is subscribed

### PR DESCRIPTION
**Pull request by furushchev**
to fix:

```
[ERROR] [WallTime: 1475047567.560302] [147.195000] bad callback: <bound method Warning.cmd_vel_callback of <__main__.Warning instance at 0x7fa7df108cb0>>
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 720, in _invoke_callback
    cb(msg)
  File "/home/furushchev/ros/indigo/src/jsk-ros-pkg/jsk_robot/jsk_fetch_robot/jsk_fetch_startup/scripts/warning.py", line 92, in cmd_vel_callback
    breaker_status = filter(lambda n: n.name=='base_breaker', self.robot_state_msgs.breakers)[0]
AttributeError: Warning instance has no attribute 'robot_state_msgs'
```

### CODE REVIEW

**Comment by k-okada** [comment]
how about just to add 
```
when self.robot_state_msgs:
```

**Comment by furushchev** [comment]
`filter(lambda n: n.name=='base_breaker', self.robot_state_msgs.breakers)[0]`

this part also occurs error if no breakers with name of "base_breaker".

Would you like to add `when self.robot_state_msgs is not None:` and `when filter(lambda n: n.name=='base_breaker', self.robot_state_msgs.breakers) is not None:`?

**Comment by k-okada** [comment]
I just thought what you do is something like
```
   when self.robot_state_msgs:
        breaker_status = filter(lambda n: n.name=='base_breaker', self.robot_state_msgs.breakers)[0]
        if ( fabs(msg.linear.x) > 0 or fabs(msg.linear.y) > 0 or fabs(msg.angular.z) > 0 ) and \
           self.battery_state_msgs.is_charging == True and breaker_status.state == BreakerState.STATE_ENABLED:
            rospy.logerr("Try to run while charging!")
            self.base_breaker(BreakerCommandRequest(enable=False))
            sound.play(4) # play builtin sound Boom!
            time.sleep(5)
            self.base_breaker(BreakerCommandRequest(enable=True))
```
or you're thinking more complex case.

**Comment by furushchev** [comment]
@k-okada I think the code you mentioned may occurs error at `filter(lambda n: n.name=='base_breaker', self.robot_state_msgs.breakers)[0]` if `filter(lambda n: n.name=='base_breaker', self.robot_state_msgs.breakers)` is `None`.

**Comment by furushchev** [comment]
@k-okada Thank you for reviewing and merging!

**Pull request merged**
