### PR TITLE
[develop/fetch] run `go-to-kitchen.l` in kinematics simulation

### PR DESCRIPTION
**Pull request by knorth55**
this PR depends on https://github.com/jsk-ros-pkg/jsk_demos/pull/1381
this PR enables to run `go-to-kitchen.l` in `kinematics simulator`.
this is useful for debugging.

@Affonso-Gui please use this for behavior tree debugging.
@mqcmd196 @tkmtnt7000 please use this for debugging.

https://user-images.githubusercontent.com/9300063/203280720-6e9fd5cf-b678-4612-86d0-85ce740cd110.mp4

### CODE REVIEW

**Comment by knorth55** [comment]
@mqcmd196 please check this commit. 
I recommend to use `go-to-spot` function rather than `:move-to`
[`3ed3dcf` (#1739)](https://github.com/jsk-ros-pkg/jsk_robot/pull/1739/commits/3ed3dcf739420f454fa08f2a7bb9a38848e2e92e)

**Comment by knorth55** [comment]
i ckecked this pr working with the real robot, too.

**Comment by mqcmd196** [comment]
I've checked it works well at simulator env

**Review by mqcmd196 — APPROVED** [review]
LGTM

**Pull request merged**
