### PR TITLE
Add fetch virtual joint for fetch moveit config

### PR DESCRIPTION
**Pull request by knorth55**
add virtual joint from fetch to map for adding collision objects from map frame

### CODE REVIEW

**Comment by 708yamaguchi** [comment]
I am sorry, but I cannot understand what you are doing.
Could you please explain the details?

Is robot fetch?
https://github.com/jsk-ros-pkg/jsk_robot/pull/1188/files#diff-acd4fe7d4341f28eb43599e661425bd7R2

**Comment by knorth55** [comment]
Thanks, I fixed the typo: `baxter` -> `fetch`

**Comment by knorth55** [comment]
without this PR, collision object moves when fetch moves.
with this PR, collision objects are associated with map frame, so that objects do not move when fetch moves.

**Comment by knorth55** [comment]
but be careful that all collision objects are associated to map frame, so you cannot add the collisiob object associated to robot base frame as easily as before.
maybe we need to support adding collision object with specific frame in moveit for the future.

**Pull request merged**
