### PR TITLE
Update hook and finger models

### PR DESCRIPTION
**Pull request by sktometometo**
Add side hook and finger tips to Fetch models.

### CODE REVIEW

**Comment by k-okada** [comment]
@sktometometo 
can you show image of collision model? Is finger thp is precise model ? or it is approximate model so that we do not have to change model when we chang the fingertip?

**Comment by knorth55** [comment]
sorry but please resolve the conflicts.
I also want to check the collision model, too.

**Comment by sktometometo** [comment]
@knorth55 I have rebased.

**Comment by knorth55** [comment]
I merged.

**Comment by knorth55** [comment]
## Visualization model
Screenshot from 2022-10-22 18-36-09

## Collision model
Screenshot from 2022-10-22 18-36-20

**Pull request closed without merging**
